### ISSUE TITLE
Support removing volumes after container stop/delete

### ISSUE THREAD

**Issue by fraz3alpha** [jenkinsci/docker-plugin#102]
I have a number of docker images that have a data VOLUME configured which is only needed for the lifetime of the container. When starting the container manually, unless the run command has --rm included, these containers will not delete the volume after the container has exited - as a result, I have a lot of files building up on the remote docker host.

As far as I can tell I can't see a mechanism to provide the --rm argument. Is there one? If not, is there a workaround?

**Comment by fraz3alpha** [comment]
Does anyone know if this was added when the code was migrated to use docker-java? Or if the new 0.9 version will include this change request?

**Comment by m1no** [comment]
I wrote a patch to support an additional option to remove future dangling volumes when the docker slave gets shutdown. I will send it upstream in the next hours.

**Comment by KostyaSha** [comment]
Should work since 0.10.1

**Comment by maksonlee** [comment]
Slave deletion will hang until the volume has been deleted, in our case, the volume contains lots of data, so it takes minutes to remove it, at the meantime, if you try to request a new job run, it will not be scheduled into build queue.

jenkins: 1.651
docker plugin: 0.16.0
