### ISSUE TITLE
Default command is /usr/sbin/sshd -D

### ISSUE THREAD

**Issue by bartmeuris** [jenkinsci/docker-plugin#105]
When starting a container and the command is empty, "/usr/sbin/sshd -D" is automatically added as CMD. However, my containers already use "/usr/sbin/sshd -D"  as ENTRYPOINT - which makes sshd quit because it receives an unknown parameter "/usr/sbin/sshd".

ENTRYPOINTS and CMD's in docker work as following: ENTRYPOINT and CMD are appended when launching a container. CMD can be overridden on commandline by simply providing parameters. ENTRYPOINT can be overriddden with the --entrypoint cmdline flag.

*Using version 0.8 of the plugin

**Comment by jgriffiths1993** [comment]
In the image's advanced configuration, specify Docker Command as "--"

**Comment by KostyaSha** [comment]
Is it still actual?
