### ISSUE TITLE
Unable to run Jenkins build node if I set "User Jenkins" in the dockerfile

### ISSUE THREAD

**Issue by flybd5** [jenkinsci/docker-plugin#1058]
### Jenkins and plugins versions report

<details>
<summary>Jenkins: 2.440.1 - details</summary>
<pre>
OS: Linux - 4.18.0-477.27.1.el8_8.x86_64
Java: 11.0.22 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
42crunch-security-audit:5.8
AnchorChain:1.0
ApicaLoadtest:1.10
BlazeMeterJenkinsPlugin:4.21
ColumnsPlugin:1.0
CustomHistory:1.6
Exclusion:0.15
Matrix-sorter-plugin:1.3
NegotiateSSO:105.vf0d0de2a_b_8a_5
Office-365-Connector:4.21.0
Parameterized-Remote-Trigger:3.2.0
PrioritySorter:5.1.0
SBuild:1.0.2
SSSCM:1.0
Surround-SCM-plugin:1.12
TestComplete:2.9.2
TestFairy:6-325.vf39d32b268fe
TwilioNotifier:0.2.1
URLSCM:1.6
abap-ci:1.21
absint-astree:1.0.8
accelerated-build-now-plugin:1.0.1
accelq-ci-connect:132.v4b_f3197e02c1
accurev:0.7.24
active-directory:2.35
acunetix:1.2.14
acunetix-360-scan:2.1.14
adaptive-disconnector:0.2
add-changes-to-build-changelog:21.v537f074cf2cc
additional-identities-plugin:30.ve898b_a_9b_f104
additional-metrics:67.vcb_823d3999a_2
adobe-cloud-manager:43.v4560e7fa191c
adoptopenjdk:1.5
advanced-installer-msi-builder:2.1.1
agent-loadbalance:1.0
agent-maintenance:2.163.v08874cd79262
aio-tests:1.11
alibabacloud-credentials:1.3
alibabacloud-ecs:1.21
alibabacloud-edas:1.0.0
alibabacloud-pkg-deployment:1.0
aliyun-oss-uploader:1.4
all-changes:1.5
allure-jenkins-plugin:2.31.1
amazon-ecr:1.114.vfd22430621f5
amazon-ecs:1.49
amazon-inspector-image-scanner:218.ve27f068f3f55
amqp-build-trigger:1.0
analysis-model-api:12.1.0
anchore-container-scanner:2.0.0
android-apk-size-watcher:1.0.1
anka-build:2.10.0
ansible:307.va_1f3ef06575a_
ansible-tower:0.16.0
ansicolor:1.0.4
ant:497.v94e7d9fffa_b_9
ant-in-workspace:1.2.2
antexec:196.v306c59b_7ca_ef
antisamy-markup-formatter:162.v0e6ec0fcfcf6
any-buildstep:14.ve115ec1484f0
anything-goes-formatter:19.v3e2b_1b_3e0ee5
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.3.1-1.0
apifortress:1.0
apimap:1-rc26.87a_0f950121f
app-detector:1.0.9
appaloosa-plugin:1.4.12
appcenter:0.11.1
appdome-build-2secure:1.2.0
appdome-validate-2secure:1.0.0
appdynamics-dashboard:1.0.15
appetize:1.1.0
applitools-eyes:1.16.0
appray:1.1.1
appscan:1.3.0
aqua-microscanner:1.0.8
aqua-security-scanner:3.2.5
aqua-serverless:1.0.6
arachni-scanner:1.0.0
archived-artifact-url-viewer:1.1
arestocats:2.1
argus-notifier:1.1
aribot:76.vf71346f9ea_d8
artifact-diff-plugin:1.3
artifact-promotion:0.5.2
artifact-repository-parameter:2.0.1
artifactdeployer:1.3
artifactory:4.0.5
artifactz:1.2.1-46.vc4e3448e4340
asakusa-satellite-plugin:0.1.1
ascentialtest-cmd-line:1.1
asm-api:9.6-3.v2e1fa_b_338cd7
assembla:1.4
assembla-auth:1.14
assembla-merge-request-builder:1.1.13
assertthat-bdd-jira:1.7
associated-files:0.2.1
async-job:1.3
atlassian-bitbucket-server-integration:4.0.0
atlassian-jira-software-cloud:2.0.13
attention:1.1
audit-log:1.3
audit-trail:361.v82cde86c784e
audit2db:0.5
authentication-tokens:1.53.v1c90fd9191a_b_
authorize-project:1.7.1
autify:101.v475e8b_111a_5e
autoaction-step:1.1
autocancel:1.0.5
autonomiq:1.22
avatar:1.2
aws-batch:2.8
aws-beanstalk-releaser:1.0.4
aws-bucket-credentials:1.0.0
aws-cloudwatch-logs-publisher:1.2.0
aws-codebuild:0.59
aws-codepipeline:0.49
aws-credentials:218.v1b_e9466ec5da_
aws-global-configuration:130.v35b_7b_96f53c3
aws-java-sdk:1.12.671-439.veec746c91fcb_
aws-java-sdk-cloudformation:1.12.671-439.veec746c91fcb_
aws-java-sdk-codebuild:1.12.671-439.veec746c91fcb_
aws-java-sdk-ec2:1.12.671-439.veec746c91fcb_
aws-java-sdk-ecr:1.12.671-439.veec746c91fcb_
aws-java-sdk-ecs:1.12.671-439.veec746c91fcb_
aws-java-sdk-efs:1.12.671-439.veec746c91fcb_
aws-java-sdk-elasticbeanstalk:1.12.671-439.veec746c91fcb_
aws-java-sdk-iam:1.12.671-439.veec746c91fcb_
aws-java-sdk-kinesis:1.12.671-439.veec746c91fcb_
aws-java-sdk-logs:1.12.671-439.veec746c91fcb_
aws-java-sdk-minimal:1.12.671-439.veec746c91fcb_
aws-java-sdk-secretsmanager:1.12.671-439.veec746c91fcb_
aws-java-sdk-sns:1.12.671-439.veec746c91fcb_
aws-java-sdk-sqs:1.12.671-439.veec746c91fcb_
aws-java-sdk-ssm:1.12.671-439.veec746c91fcb_
azure-credentials:312.v0f3973cd1e59
azure-credentials-ext:1.0
azure-sdk:157.v855da_0b_eb_dc2
badge:1.9.1
bitbucket:241.v6d24a_57f9359
blueocean:1.27.11
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.27.11
blueocean-commons:1.27.11
blueocean-config:1.27.11
blueocean-core-js:1.27.11
blueocean-dashboard:1.27.11
blueocean-display-url:2.4.2
blueocean-events:1.27.11
blueocean-git-pipeline:1.27.11
blueocean-github-pipeline:1.27.11
blueocean-i18n:1.27.11
blueocean-jira:1.27.11
blueocean-jwt:1.27.11
blueocean-personalization:1.27.11
blueocean-pipeline-api-impl:1.27.11
blueocean-pipeline-editor:1.27.11
blueocean-pipeline-scm-api:1.27.11
blueocean-rest:1.27.11
blueocean-rest-impl:1.27.11
blueocean-web:1.27.11
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1152.v6f101e97dd77
build-blocker-plugin:1.7.9
build-monitor-plugin:1.14-860.vd06ef2568b_3f
build-name-setter:2.4.1
build-timeout:1.32
build-timestamp:1.0.3
build-token-root:151.va_e52fe3215fc
build-user-vars-plugin:1.9
build-with-parameters:76.v9382db_f78962
built-on-column:1.4
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.0.2
cloud-stats:336.v788e4055508b_
cloudbees-bitbucket-branch-source:880.vcf4056c5a_71f
cloudbees-disk-usage-simple:203.v3f46a_7462b_1a_
cloudbees-folder:6.901.vb_4c7a_da_75da_3
command-launcher:107.v773860566e2e
commons-httpclient3-api:3.1-3
commons-lang3-api:3.13.0-62.v7d18e55f51e2
commons-text-api:1.11.0-95.v22a_d30ee5d36
conditional-buildstep:1.4.3
config-file-provider:968.ve1ca_eb_913f8c
configuration-as-code:1775.v810dc950b_514
configurationslicing:548.ve92d48e66b_f8
copyartifact:722.v0662a_9b_e22a_c
coverage:1.13.0
credentials:1337.v60b_d7b_c7b_c9f
credentials-binding:657.v2b_19db_7d6e6d
cucumber-reports:5.8.1
cvs:2.19.1
dark-theme:439.vdef09f81f85e
dashboard-view:2.508.va_74654f026d1
data-tables-api:2.0.2-1
dependency-check-jenkins-plugin:5.5.0
deploy:1.16
description-setter:239.vd0a_6b_785f92d
disk-usage:1.2
display-url-api:2.200.vb_9327d658781
docker-build-publish:1.4.0
docker-build-step:2.11
docker-commons:439.va_3cb_0a_6a_fb_29
docker-java-api:3.3.4-86.v39b_a_5ede342c
docker-plugin:1.6
docker-workflow:572.v950f58993843
dtkit-api:3.0.2
durable-task:550.v0930093c4b_a_6
ec2:1648.vf3d852e00486
echarts-api:5.5.0-1
email-ext:2.105
emailext-template:1.5
embeddable-build-status:467.v4a_954796e45d
envinject:2.908.v66a_774b_31d93
envinject-api:1.199.v3ce31253ed13
extended-read-permission:53.v6499940139e5
extensible-choice-parameter:1.8.1
external-monitor-job:215.v2e88e894db_f8
favorite:2.208.v91d65b_7792a_c
file-operations:214.v2e7dc7f25757
flexible-publish:0.16.1
font-awesome-api:6.5.1-3
forensics-api:2.4.0
generic-webhook-trigger:2.0.2
git:5.2.1
git-client:4.7.0
git-parameter:0.9.19
git-server:114.v068a_c7cc2574
github:1.38.0
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1781.va_153cda_09d1b_
github-oauth:597.ve0c3480fcb_d0
github-pullrequest:0.7.0
gitlab-api:5.3.0-91.v1f9a_fda_d654f
gitlab-branch-source:703.vc5fd7effcc6b_
gitlab-oauth:1.19
gitlab-plugin:1.8.0
google-oauth-plugin:1.330.vf5e86021cb_ec
gradle:2.10
groovy:457.v99900cb_85593
groovy-postbuild:228.vcdb_cf7265066
gson-api:2.10.1-15.v0d99f670e0a_7
h2-api:11.1.4.199-12.v9f4244395f7a_
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
hashicorp-vault-plugin:364.vf5d54b_3dc313
htmlpublisher:1.33
http_request:1.18
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.16.2-378.v7e79818f53ce
jacoco:3.3.5
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javadoc:243.vb_b_503b_b_45537
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
jdk-tool:73.vddf737284550
jenkins-design-language:1.27.11
jersey2-api:2.41-133.va_03323b_a_1396
jira:3.13
jjwt-api:0.11.5-77.v646c772fddb_0
jnr-posix-api:3.1.19-2
job-dsl:1.87
job-import-plugin:3.6
job-restrictions:0.8
jobConfigHistory:1229.v3039470161a_d
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery:1.12.4-1
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-52.v57de85cc4722
junit:1259.v65ffcef24a_88
kubernetes:4199.va_1647c280eb_2
kubernetes-client-api:6.10.0-240.v57880ce8b_0b_2
kubernetes-credentials:0.11
label-linked-jobs:6.0.1
ldap:711.vb_d1a_491714dc
locale:431.v3435fa_8f8445
localization-support:1.2
lockable-resources:1243.v346d600eea_24
log-parser:2.3.3
m2release:0.16.4
mailer:472.vf7c289a_4b_420
mapdb-api:1.0.9-28.vf251ce40855d
mask-passwords:173.v6a_077a_291eb_5
matrix-auth:3.2.2
matrix-project:822.824.v14451b_c0fd42
maven-plugin:3.23
mercurial:1260.vdfb_723cdcc81
metrics:4.2.21-449.v6960d7c54c69
mina-sshd-api-common:2.12.0-90.v9f7fb_9fa_3d3b_
mina-sshd-api-core:2.12.0-90.v9f7fb_9fa_3d3b_
monitoring:1.98.0
msbuild:1.30
naginator:1.436.vb_e769dcb_cdf6
nested-view:1.33
nexus-artifact-uploader:2.14
node-iterator-api:55.v3b_77d4032326
nodejs:1.6.1
nodelabelparameter:1.12.0
oauth-credentials:0.646.v02b_66dc03d2e
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pam-auth:1.10
parameterized-scheduler:262.v00f3d90585cc
parameterized-trigger:787.v665fcf2a_830b_
performance:957.v658a_7065b_92a_
pipeline-aws:1.43
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-github:2.8-159.09e4403bc62f
pipeline-github-lib:42.v0739460cda_c4
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:704.vc58b_8890a_384
pipeline-input-step:491.vb_07d21da_1a_fb_
pipeline-maven:1390.v66456b_ea_3467
pipeline-maven-api:1390.v66456b_ea_3467
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2184.v0b_358b_953e69
pipeline-model-definition:2.2184.v0b_358b_953e69
pipeline-model-extensions:2.2184.v0b_358b_953e69
pipeline-multibranch-defaults:2.1
pipeline-rest-api:2.34
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2184.v0b_358b_953e69
pipeline-stage-view:2.34
pipeline-utility-steps:2.16.2
plain-credentials:179.vc5cb_98f6db_38
plugin-usage-plugin:4.2
plugin-util-api:4.1.0
postbuild-task:1.9
postbuildscript:3.2.0-550.v88192b_d3e922
powershell:2.1
prism-api:1.29.0-13
prometheus:2.5.1
promoted-builds:945.v597f5c6a_d3fd
publish-over:0.22
publish-over-ssh:1.25
pubsub-light:1.18
rebuild:330.v645b_7df10e2a_
resource-disposer:0.23
robot:3.5.1
role-strategy:713.vb_3837801b_8cc
run-condition:1.7
s3:466.vf5b_3db_8e3eb_2
saferestart:0.7
saml:4.464.vea_cb_75d7f5e0
scm-api:689.v237b_6d3a_ef7f
script-security:1326.vdb_c154de8669
simple-theme-plugin:176.v39740c03a_a_f5
slack:684.v833089650554
snakeyaml-api:2.2-111.vc6598e30cc65
sonar:2.17.2
sse-gateway:1.26
ssh-agent:346.vda_a_c4f2c8e50
ssh-credentials:322.v124df57ed808
ssh-slaves:2.948.vb_8050d697fec
ssh-steps:2.0.68.va_d21a_12a_6476
sshd:3.322.v159e91f6a_550
stashNotifier:1.464.va_9203f84a_417
structs:337.v1b_04ea_4df7c8
subversion:2.17.3
testng-plugin:835.v51ed3da_fcc35
text-finder:1.26
theme-manager:215.vc1ff18d67920
thinBackup:1.19
throttle-concurrents:2.14
timestamper:1.26
token-macro:400.v35420b_922dcb_
trilead-api:2.142.v748523a_76693
uno-choice:2.8.1
validating-string-parameter:183.v3748e79b_9737
variant:60.v7290fc0eb_b_cd
view-job-filters:369.ve0513a_a_f5524
warnings-ng:11.2.1
workflow-aggregator:596.v8c21c963d92d
workflow-api:1291.v51fd2a_625da_7
workflow-basic-steps:1049.v257a_e6b_30fb_d
workflow-cps:3883.vb_3ff2a_e3eea_f
workflow-durable-task-step:1331.vc8c2fed35334
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:773.vc4fe1378f1d5
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:657.v03b_e8115821b_
workflow-support:865.v43e78cc44e0d
ws-cleanup:0.45
xunit:3.1.4
</pre>
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux RedHat 8.8, agent is 7.9.

### Reproduction steps

Put "User jenkins" in dockerfile, build container, try to run it

### Expected Results

For it to run

### Actual Results

Complains that the agent cannot be executed in the node

### Anything else?

I need for the container to switch to or run entirely as the Jenkins user because there are commands in my pipelines that cannot run as root.

### Are you interested in contributing a fix?

I don't know the code well enough to do that.

**Comment by MarkEWaite** [comment]
As an additional item, the Jenkins project no longer supports Red Hat Enterprise Linux 7 or any of its derivatives.  More details are available in the [operating system end of life](https://www.jenkins.io/blog/2023/05/30/operating-system-end-of-life/) blog post.

**Comment by flybd5** [comment]
> As an additional item, the Jenkins project no longer supports Red Hat Enterprise Linux 7 or any of its derivatives (like CentOS 7, Amazon Linux 2, or Oracle Linux 7). More details are available in the [operating system end of life](https://www.jenkins.io/blog/2023/05/30/operating-system-end-of-life/) blog post.

Not relevant, as I am not running Jenkins on 7.9, only a build node with Java 11.

**Comment by flybd5** [comment]
> The agent container image that you are using must have a mistake in it. The Jenkins agent container images always run as the 'jenkins' users. They never run as root.
> 
> I just confirmed with my installation that the following Pipeline job:
> 
> ```groovy
> pipeline {
>     agent {
>         label 'alpine'
>     }
>     stages {
>         stage('Hello') {
>             steps {
>                 sh 'whoami'
>             }
>         }
>     }
> }
> ```
> 
> results in the following output:
> 
> ```
> 14:37:10  Started by user Mark Waite
> 14:37:10  [Pipeline] Start of Pipeline
> 14:37:10  [Pipeline] node
> 14:37:16  Running on alpine-jdk21-00005ve0gil95 on mark-pc2
> 14:37:16  [Pipeline] {
> 14:37:16  [Pipeline] stage
> 14:37:16  [Pipeline] { (Hello)
> 14:37:16  [Pipeline] sh
> 14:37:17  + whoami
> 14:37:17  jenkins
> 14:37:17  [Pipeline] }
> 14:37:17  [Pipeline] // stage
> 14:37:17  [Pipeline] }
> 14:37:17  [Pipeline] // node
> 14:37:17  [Pipeline] End of Pipeline
> 14:37:17  Finished: SUCCESS
> ```
> 
> That output shows that the agent is running as the user 'jenkins'.
> 
> I use the agent Docker image 'jenkins/inbound-agent:latest-alpine-jdk21' with remote file system root '/home/jenkins/agent'

I got the Jenkins controller image from the Docker Hub, so if it has an error, looks like someone released it with bugs. I am not having problems with Jenkins controller in a container, I am having problems with a container I built trying to run as a cloud build node. It most definitely does NOT start as the Jenkins users, it starts up as root.

**Comment by MarkEWaite** [comment]
> I am having problems with a **container I built** trying to run as a cloud build node. It most definitely does NOT start as the Jenkins users, it starts up as root.

The container you built to run as a cloud build node has an error in its container definition.  The error is that you have configured it to run as the user "root" instead of using an unprivileged account.

Refer to the [Jenkins Docker agent repository](https://github.com/jenkinsci/docker-agent) for examples of container definitions that run as an unprivileged user.  Some of those examples include:

* [Alpine Linux](https://github.com/jenkinsci/docker-agent/blob/master/alpine/Dockerfile)
* [Debian Linux](https://github.com/jenkinsci/docker-agent/blob/master/debian/Dockerfile)

**Comment by flybd5** [comment]
I tried using the USER command in the Dockerfile to tell it to switch to the Jenkins user after it has done all the setup work. What happens when I do that is that Jenkins complains that it cannot run the agent, and goes into an endless loop of instantiating one container after another, until I kill the job. And then I have to manually remove the containers it created.

I see the line that reads: 

### `ADD --chown="${user}":"${group}" "https://repo.jenkins-ci.org/public/org/jenkins-ci/main/remoting/${VERSION}/remoting-${VERSION}.jar" /usr/share/jenkins/agent.jar`

Does this mean that every container I build this way has to have the remoting agent baked in?

**Comment by MarkEWaite** [comment]
> Does this mean that every container I build this way has to have the remoting agent baked in?

Yes, the Jenkins docker plugin expects that the container it launches as an inbound agent must run the Jenkins agent.jar to initiate the connection from the agent to the controller.

**Comment by flybd5** [comment]
I got that part,  but the user and perms of the agent jar I thought would have been set as permissive as possible. I will try this tomorrow.

**Comment by flybd5** [comment]
In looking at the dockerfile for the debian example, I see this:

`ARG VERSION=3206.vb_15dcf73f6a_9`

There doesn't seem to be any correlation to the Jenkins I am using, 2.440.1. I am also using jdk11, because jdk17 or higher are not certified for use in our organization.

Where does that version for the agent come from??

**Comment by MarkEWaite** [comment]
> Where does that version for the agent come from??

It is updated by `updatecli` whenever there is a new release of Jenkins remoting.

**Comment by flybd5** [comment]
I got it fixed. Had to copy the remoting agent to the agent root folder and set some permissions before setting the user to jenkins at the end of the docker file. Thanks!
