### ISSUE TITLE
Pipeline withDockerContainer()  report an Error：Cannot run program "docker": error=2, No such file or directory

### ISSUE THREAD

**Issue by leifengyang** [jenkinsci/docker-plugin#1069]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

1. CentOS 7.9
2. Docker 26.1.0
3. Install Jenkins Using Docker。
```sh
docker run \
-d \
--privileged \
-p 8080:8080 \
-p 50000:50000 \
--name jenkins \
--restart=always \
-v jenkins-data:/var/jenkins_home \
-v /var/run/docker.sock:/var/run/docker.sock \
jenkins/jenkins:2.419-alpine-jdk17
```
4. Installed Plugins：
    - Docker API Plugin  3.3.4-86.v39b_a_5ede342c
    - Docker Commons Plugin  439.va_3cb_0a_6a_fb_29
    - Docker Pipeline 572.v950f58993843
    - Docker plugin 1.5
    - Blue Ocean 1.27.11
    - All Recommend Plugin
 

### Reproduction steps

1. Manage Jenkins -> Clouds -> New cloud
    - Cloud Name: docker； Type：Docker
    - Docker Cloud Details：
       -  Docker Host URI： unix:///var/run/docker.sock
       - click "Test Connection"； Successfully print： Version = 26.1.0, API Version = 1.45
       - checked "Enabled"；
2. New Item； 
   - name: demo01
   - type: Pipeline
   - define Pipeline Script as：
```groovy
pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                withDockerContainer('maven:3.9.3-eclipse-temurin-17') {
                    sh 'mvn -v'
                }
            }
        }
    }
}
```
3. Open Blue Ocean Dashboard，and then run..

### Expected Results

print mvn version info

### Actual Results

```sh
docker pull maven:3.9.3-eclipse-temurin-17

/var/jenkins_home/workspace/demo01@tmp/durable-bad98370/script.sh.copy: line 1: docker: not found

script returned exit code 127
```

### Anything else?

About 2 years ago , I used jenkinsci/blueocean:1.25.5，They worked successfully。

**Comment by MarkEWaite** [comment]
Not a bug.  Refer to [current Jenkins docker install instructions](https://www.jenkins.io/doc/book/installing/docker/) for a technique that allows it to work, but is risky because it uses Docker in Docker.  Refer to the [Jenkins tutorials](https://www.jenkins.io/doc/tutorials/#tools) for a technique uses runs the controller and a custom defined agent with Docker compose and avoids Docker in Docker.
