### ISSUE TITLE
Not working for Jenkins in MacOs

### ISSUE THREAD

**Issue by Priyo-prog** [jenkinsci/docker-plugin#1096]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

MacOs Ventura 13.2.1

### Reproduction steps

check the docker version in jenkins

Step 1: Create a pipeline

Step2: Write the below code

pipeline{
    agent any
    stages{
        stage("Docker Test Version"){
            steps{
                sh "docker -v"
            }
        }
    }
} 

### Expected Results

show docker version in the console output

### Actual Results

docker command not found

**Comment by MarkEWaite** [comment]
The bug description does not involve this plugin.  This plugin does not provide the `docker` command on a controller or on an agent.  It uses an existing `docker` installation to provide a cloud that can start and stop Jenkins agents on demand.
