### ISSUE TITLE
DNS Search option

### ISSUE THREAD

**Issue by kirk-fitzsimons** [jenkinsci/docker-plugin#1104]
### What feature do you want to see added?

Hi,

Is there any option to pass in these dns options that can be passed in to a docker run command via the docker plugin agent template? I can see you can pass in dns server e.g.

- connector: "attach"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          dnsHosts:
          - "[kirk.internal.ie](http://kirk.internal.ie/)"
          dnsString: "[kirk.internal.ie](http://kirk.internal.ie/)"
          
          
![image](https://github.com/user-attachments/assets/4dc29b8b-7fde-42dc-8441-f84ffbbeed28)

 but i don't see and option in the plugin to pass in domain search etc, the below can be add as arguments to a docker run command for example
 
 --dns-search="${DNS_SEARCH}" \
--dns-opt="${DNS_NDOTS}" \

Kirk

### Are you interested in contributing this feature?

Would be happy to work with a maintainer

**Comment by MarkEWaite** [comment]
Included in [docker-plugin 1.7](https://github.com/jenkinsci/docker-plugin/releases/tag/docker-plugin-1.7)
