### ISSUE TITLE
Git SCM "Included Regions" broken with docker-plugin 0.7

### ISSUE THREAD

**Issue by tehranian** [jenkinsci/docker-plugin#111]
Hi there,

We hit an issue while transitioning our build jobs over from static slave VMs to dynamically provisioned Docker containers... Using Docker containers seems to break the functionality of restricting SCM-triggered builds to a certain path in the repo.

Ex:
* We have a Git repo with many subdirectories
* There are several Jenkins jobs defined, each job building a separate module from that repo. The modules themselves live in isolated subdirectories in that repo.
* Since it's wasteful to rebuild "module A" every time **anything** in the repo is changed, we only want "module A" to be rebuilt when files under the "moduleA" subdirectory are changed. Like while for "module B".
* To that end, we use the "Included Regions" functionality of the Git SCM plugin and define a file path (via regex) for each job such that each job only gets triggered when files under the respective directory of that module are changed.

This worked well with static slaves. For some reason, this seems to be broken when using dynamically provisioned Docker containers. :(

FWIW - We've currently on the following:
* Jenkins 565.2
* Docker plugin 0.7
* Docker 1.1.2

**Comment by KostyaSha** [comment]
Keeping workspaces is not a docker or ANY cloud issue. 
1) don't use polling that require workspace
2) assign this jobs to static host

**Comment by tehranian** [comment]
@atsymbala - Here's an idea to work around this, but admittedly it's a complete hack... What if you had a non-Dockerized "initial" job for each Dockerized job that held the workspace, was able to determine if a change was made, and then triggered the Dockerized job as a downstream?

**Comment by cimi** [comment]
@KostyaSha as far as I can tell, it is impossible to use `Included/Excluded regions` with ephemeral workers and Git polling. 

If I try to add an included region, the polling no longer uses `git ls-remote` and instead tries to look at the local workspace. Since the workers go away after every build, there is no workspace so the polling thinks there are always changes and constantly triggers the build:

```
Started on Jan 10, 2019 6:09:00 PM
Workspace is offline.
Scheduling a new build to get a workspace. (nonexisting_workspace)
Done. Took 0 ms
Changes found
```
