### ISSUE TITLE
jenkins could not run job on slave container

### ISSUE THREAD

**Issue by joshff9** [jenkinsci/docker-plugin#113]
I set up the docker cloud on jenkins and the test connection has no problems. When I try to run a simple script in a jenkins job, I notice that the there're containers spawned, but the build job just says "waiting for next available executor", and the docker host keeps spawning new containers every few seconds..

I validated the jenkins slave container by manually start one container, and configure it by jenkins manage slave tab, and the build job runs on it without problem..

**Comment by KostyaSha** [comment]
Expected to be changed/fixed >= 0.10.0

**Comment by vasuems** [comment]
I am also facing the same issue. My jenkins is 2.7.2 and my docker plugin version is 0.16.1.

**Comment by leenadharmik** [comment]
Commit message: "Update index.html"
 > git rev-list --no-walk 90e5bbae6d033ea7a98cb030b19ac1a109b5f3b1 # timeout=10
[job-slave2] $ /bin/sh -xe /tmp/jenkins10410287492249074781.sh
+ sudo cp /mnt/jenkins_slave/workspace/job-slave2/index.html /mnt/lee_volume
+ docker run -itdp 80:80 --name httpdc1 -v /mnt/lee_volume:/usr/local/apache2/htdocs httpd
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Head "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by MarkEWaite** [comment]
> Commit message: "Update index.html"

@leenadharmik posting a question on a closed issue is not an effective way to get an answer to your question.  Post your question to https://community.jenkins.io with enough details that will allow others to duplicate the issue.  You're more likely to receive an answer there than here.
