### ISSUE TITLE
Ability to use jenkins variable like $BUILD_NUMBER in DockerTemplate

### ISSUE THREAD

**Issue by dawidmalina** [jenkinsci/docker-plugin#116]
Is it possible to use $BUILD_NUMBER in DockerTemplate e.g. Port bindings?

I'd like to generate port number which depends on build number e.g.
Port bindings $BUILD_NUMBER:8080

But when I do it I'm getting this error:
ERROR: Processing failed due to a bug in the code. Please report this to jenkinsci-users@googlegroups.com
java.lang.NumberFormatException: For input string: "$BUILD_NUMBER"

**Comment by KostyaSha** [comment]
@samrocketman could you give a screenshot where you trying to enter this variables? 
DockerTemplate is used in multiple places.

**Comment by samrocketman** [comment]
That would be in a bash shell step before doing any docker specific steps.  It will evaluate variables in the tmpl as bash environment variables in the bash here document.  Think of it as a hack for templating.

**Comment by KostyaSha** [comment]
@dawidmalina if it about DockerTemplate that used for slave provisioning - then no. When slave provisioned build object not yet exist, so nothing can be substituted. 
If you mean DockerTemplate run that is in build/post-build step, then it can be possible.

Please clarify your use case.

**Comment by dawidmalina** [comment]
Then I'm closing issue.
