### ISSUE TITLE
[Idea] Security improvements

### ISSUE THREAD

**Issue by ninja-** [jenkinsci/docker-plugin#123]
Hi, I am currently trying to harden my Jenkins instance a bit and docker-plugin is a great core to it.
I got it running recently and have a few ideas to improve security:
There are some assertions first:
1) I am the only one with admin permissions for the Jenkins
2) I am the only one who setups new projects etc.

In that environment, I am trying to assure that no project can...
1) Access Jenkins files, including config files
2) Access files of another project
3) Access docker socket without authentication
4) Access build files of another project that was build before on that slave. They need to be wiped out & restart after a single build.
5) Access any running slave with the "jenkins:jenkins" password. It would be better to generate them on master and pass to 'docker run' via '-e SSH_PASSWORD=password_generated_on_master'
6) Building on master MUST be disabled.

Some of these are possible with default setup and others can be easily implemented.
I am planning to start implementing this myself and come back with a PR but commits from project maintainers would be of course welcome.

**Comment by ninja-** [comment]
@magnayn what do you think about creating a tutorial @ readme for creating an secure isolated env with docker-plugin?
I could write it based on what I did(minor changes to docker-plugin).
But we also need more testing, like checking if there are no race conditions that would - for example - cause the container to be resued?

**Comment by samrocketman** [comment]
This project has a wiki.  It could be written there.

**Comment by ninja-** [comment]
what do you guys think about the checklist now? is it any better? can docker-plugin now be used for real project build isolation?

**Comment by samrocketman** [comment]
> 1) Access Jenkins files, including config files

Regarding this point.  It sounds like you're running builds on the master.  This is a bad practice.  You should set the executors on master to `0` and add a build slave to build software on a completely separate machine.  By doing that you'll have completely isolated builds from the server.

The same can be said about using docker.  Do not run docker on the master either.  Docker containers run within the host kernel.  That means any vulnerability in the kernel could allow the bucks to break out of the docker container and affect the master.  You should treat docker containers as if they're not isolated at all.  That is, follow the same practices you would if it weren't isolated.

* Builds should run under a restricted user.
* the user should not be able to become root.
* you should run an init process which is PID 1 in a container.  It will handle cleaning up abandoned child processes, etc.  see base image docker by phusion.

**Comment by ninja-** [comment]
@samrocketman no worries I disabled building on master. do you think that at this point docker-plugin is capable of real build isolation?

**Comment by samrocketman** [comment]
> do you think that at this point docker-plugin is capable of real build isolation?

Sure, anything with ephemeral builds (i.e. slaves are brought up, built, and torn down) is capable of real build isolation.  As long as you follow those practices I outlined it should be fine.  There are other plugins for ephemeral builds such as the cloud plugin or the mesos plugin.

**Comment by ndeloof** [comment]
as long as template are defined by administrator you can prevent access to unauthorized ressources. Docker API itself is secured for a long time. 
I'm working on a fix for ssh slaves so a public key is injected at startup so there's no "public secret" built into docker image that could be abused, and ensure only jenkins master can connect a slave
