### ISSUE TITLE
Extraneous docker images created

### ISSUE THREAD

**Issue by wsoula** [jenkinsci/docker-plugin#133]
My problem is very similar to #80.  I have two freestyle jobs: a and b.  a is restricted to only run on label a and b is restricted to only run on label b.  I have two images in the docker section of the global config, jenkins-2 with label a and jenkins-go-6 with label b.  When I kick off job a, then only the one container is spun up and the build runs and is done.  If I kick off job b, then two containers are created, one for each type and the one that has the correct label gets the job and builds then destroys itself and the other one just hangs around till it is destroyed by being idle.  I tried making two docker cloud sections in the global config but that didn't produce any different results.  If I list b first in the docker images then a build of b only creates a container for b but a build of a creates a container for b and a.

Jenkins: 1.580.1
docker-plugin: 0.9-SNAPSHOT (private-2055fa25-) built from latest HEAD

I'm using the snapshot because 0.8 would spin up 3 containers before one would connect.

I believe my docker is 1.0.1, this is what I get when I click the test connection button: Version = 1.0.1

**Comment by KostyaSha** [comment]
Please try #210 and reopen if issue still exists.
