### ISSUE TITLE
Functionality to only run jobs with specific label on docker container

### ISSUE THREAD

**Issue by pascal01** [jenkinsci/docker-plugin#135]
We would like to use the docker plugin in our production environment, but we have a lot of jobs without lables that we would still build on our physical build slaves. But currently the docker plugin starts containers for all jobs that have no labels.
I don't see an option like "only build jobs with label restrictions matching this node".
Is it possible to implement this feature or is it already possible and i didn't see how?
Thanks for the greate plugin!

**Comment by sebastiangraf** [comment]
Implemented in https://github.com/jenkinsci/docker-plugin/pull/139 .

**Comment by KostyaSha** [comment]
Resolved with 09ee2daf034aaf0e761aee85786da5307b84baf1 relates #139
