### ISSUE TITLE
0.9-SNAPSHOT: Cloud>Docker settings not passed to docker

### ISSUE THREAD

**Issue by wiese** [jenkinsci/docker-plugin#137]
Hello,
in our example we mount a cache directory (previously successfully and w/o a change in configuration since v0.8) via the docker cloud's "Volumes" setting.
Unfortunately, in 0.9-SNAPSHOT, this setting is not passed to the docker API (mydockerhost:4243/containers/create) on on-demand slave creation (inspected the Jenkins System Log), an empty JSON object is passed instead:
`"Volumes":{}`
This seems to apply for all of the following configuration settings:
* Volumes
* LxcConf
* WorkingDir

while most other settings, e.g. VolumesFrom, work.

Thanks

Jenkins ver. 1.580.2
plugin 0.9-SNAPSHOT (docker-plugin-0.9-20141224.085745-1.hpi)

**Comment by tunix** [comment]
Related to #128

**Comment by KostyaSha** [comment]
Volumes was fixed in some versions.... Closing.

**Comment by wiese** [comment]
Fix confirmed. Thanks a lot!
docker-plugin-0.10
