### ISSUE TITLE
Canceling job of dead docker server hangs Jenkins

### ISSUE THREAD

**Issue by thomassuckow** [jenkinsci/docker-plugin#147]
When a Docker server dies/becomes unresponsive, if you cancel a job that was running on that server jenkins hangs.

The logs show attempts to delete the instance which inevitably timeout. Until they timeout jenkins is unusable.

Threading?

**Comment by KostyaSha** [comment]
Do you have any stacktrace?

**Comment by KostyaSha** [comment]
Please take threadDump using 'jstack' tool

**Comment by thomassuckow** [comment]
I cannot easily recreate this scenario, closing for now but will keep this in mind if it crops back up.
