### ISSUE TITLE
Docker containers are killed even if there is Flyweight tasks on it

### ISSUE THREAD

**Issue by guilhem** [jenkinsci/docker-plugin#148]
Sometimes, jobs are launched in same docker container (like if there is >1 executor on slave).

This lead to failure when 1 finish, it stops container with other job in it.

More information:
* example: http://i.imgur.com/LfarPRw.png
* error: https://gist.github.com/guilhem/6cb6d0049eb42dce7653
* context:
  * Jenkins ver. 1.580.2
  * plugin 0.8 && a2222d954e6e1cb770b2775340d52a71b9110e85
  * Master without any executor (all is done in docker)
  * Use [debian-package-builder](https://github.com/jenkinsci/debian-package-builder-plugin) and [matrix project](https://github.com/jenkinsci/matrix-project-plugin) (building package for ubuntu 12.04/14.04)
  * Docker image look like this one: https://registry.hub.docker.com/u/guilhem/jenkins-slave/

**Comment by KostyaSha** [comment]
Please try reproduce without "debian-package-builder" with plain matrix-project.

**Comment by guilhem** [comment]
@KostyaSha ok I will do this.

I manage to launch 3 job on same docker: http://i.imgur.com/LgQH15O.png

I launched a first job. Wait for docker to be up, then launched 2 other job and each one go to this docker container

I reproduce bug with 3 "test job", without anything in it, just launching 2 slaves (each one).
http://i.imgur.com/rfp8J0r.png

**Comment by KostyaSha** [comment]
Are they are all matrix jobs? Do you have any labels? Please add system logger for class package.
Also i can advice wait new release because there are many commits on top of latest release.

**Comment by guilhem** [comment]
@KostyaSha all are matrix job. "master" job has no pinning, no label, nothing at all :) except launching 2 slaves with 2 different label.

I also test with docker HEAD~3 without success. I don't know if problem come from matrix or from docker plugin...

You can reproduce problem very easily

**Comment by KostyaSha** [comment]
Matrix project like multiple scm always has issues. And there are some reports in other issues/PRs.

**Comment by guilhem** [comment]
I fix it by adding 1 executor on master... This bug seems to be from matrix.

Thank you @KostyaSha :)

**Comment by thomassuckow** [comment]
They are called Flyweight tasks. We should not be killing the container in the presence of a flyweight, that may be an issue with Durable-Task-Plugin or it may not.

Flyweights usually are unlabeled, so if you allow unlabeled jobs on your docker container then flyweights will come along. There is a way to forbid it, maybe we should add an option for that. There is an Exclude Flyweight/"Matric Parent" Plugin for normal slaves, we would just need to adopt that.

**Comment by guilhem** [comment]
@thomassuckow Oh ok, I wasn't aware of this type of task.

I reopen issue with correct description.
