### ISSUE TITLE
Passing --add-host option to run command

### ISSUE THREAD

**Issue by sisao** [jenkinsci/docker-plugin#154]
Hi,

is it possible to use the docker "--add-host" option in the plugin?
I did't find anything about it in the plugin documentation...

Regrads,
Stefan

**Comment by pcas** [comment]
I need this one as well. Looks like its a bit of a hassle and would need a change in https://github.com/kpelykh/docker-java/blob/26b4069bb1985a8c293a016aaf9b56979771d75b/src/main/java/com/kpelykh/docker/client/model/HostConfig.java  to be able to add the parameter.

Looks like "--add-host" maps to "ExtraHosts"

**Comment by pcas** [comment]
Alright! I've got something working. Can anyone weigh in on what to do about jDocker? It looks like that repo isn't being maintained anymore and it needed some code changes for this.

**Comment by pcas** [comment]
Alright looks like my pull request to the Nirima API is in limbo, so if anyone actually needs this you'll need to pull nirimas repo, and apply my changes. Build it.
https://github.com/nirima/jDocker/pull/7 

Pull my changes to docker-plugin (force committed over tag-8 below)
https://github.com/pcas/docker-plugin

And rebundle it all into a plugin. You'll need to tweak maven a bit to force it to use the a local version of  the nirima api.

**Comment by KostyaSha** [comment]
@sisao i will look on this, but we have more critical issues now
