### ISSUE TITLE
Container hangs and never gets the slave

### ISSUE THREAD

**Issue by kusold** [jenkinsci/docker-plugin#155]
I've spent some time today trying to get this working, but I keep getting stuck.

Here is the log that the slaves have been spitting out. I am able to ssh in to 10.20.101.6:49239 although it takes a little while to connect when I try.
```
just before slave 1c1a7bc94f0a@docker-slave gets launched ...
executing pre-launch scripts ...
[02/04/15 18:08:56] [SSH] Opening SSH connection to 10.20.101.6:49239.
[02/04/15 18:08:57] [SSH] Authentication successful.
[02/04/15 18:08:57] [SSH] The remote users environment is:
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_EXECUTION_STRING=set
BASH_LINENO=()
BASH_SOURCE=()
(spinny wheel)
```

My Dockerfile:
```
FROM evarga/jenkins-slave
ADD authorized_keys /root/.ssh/authorized_keys
# Copied from https://github.com/GoogleCloudPlatform/golang-docker/blob/master/base/Dockerfile
RUN apt-get update -y && apt-get install --no-install-recommends -y -q curl build-essential ca-certificates git 
mercurial bzr
RUN mkdir /goroot && curl https://storage.googleapis.com/golang/go1.4.linux-amd64.tar.gz | tar xvzf - -C /goroot --strip-components=1
RUN mkdir /gopath
ENV GOROOT /goroot
ENV GOPATH /gopath
ENV PATH $PATH:$GOROOT/bin:$GOPATH/bin
```

Any help would be appreciated, because I am banging my head on this.

Jenkins 1.598, Docker Plugin 0.8, Docker 1.4.1

**Comment by KostyaSha** [comment]
Firstly, try to use real evarga/jenkins-slave container. And then compare behavior with your.

**Comment by Kusold** [comment]
I retested and obtained the same exact result using the base `evarga/jenkins-slave` with user/pass ssh auth.

**Comment by Intrepidd** [comment]
I'm seeing this problem too, if I watch docker ps closely, I can see that containers are spawned, die after ~ 10 seconds, a lot of times before finally succeeding

**Comment by denouche** [comment]
Hi!

The same issue for me.

Sometimes 5 or 6 containers are spawned and died before Jenkins can connect to the next one.
I guess it's a time problem.

Maybe Jenkins tries to connect to the slave before that sshd is totally up ?
```
$ time docker run -it --rm denouche/jenkins-agents:base-debian8.1 /usr/sbin/sshd

real	0m1.292s
user	0m0.032s
sys	0m0.080s
```

I think the problem is that if Jenkins tries to connect before sshd listen it just stop the container and try again with another one.

Is it possible to delay a little bit the moment where Jenkins tries to connect to the slave ?

Thanks in advance

**Comment by denouche** [comment]
Ok for me the point was:

In the agent Dockerfile the line 
```dockerfile
EXPOSE 22
```

is VERY important.

**Comment by KostyaSha** [comment]
Connections handling was improved in 0.10, please try 0.10.1 after this weekend.
