### ISSUE TITLE
Feature request: Inject environment variables

### ISSUE THREAD

**Issue by bartmeuris** [jenkinsci/docker-plugin#158]
As the title says, there should be a way to inject environment variables into a container. This is currently possible for normal nodes, and using containers as a drop-in replacement for 'real' nodes impossible when they have custom environment variables defined.

**Comment by KostyaSha** [comment]
Please provide real use cases

**Comment by bartmeuris** [comment]
My usecase is as mentioned to replace current "real" nodes with containers. Since these nodes have environment variables injected in their configuration, builds depending on these environment variables fail when they build in Docker containers..

I currently have to inject these ENV vars in each build (currently 300+) - which I would like to avoid.

Since permanent nodes support this feature, it would seem logical that containers would also support this.

**Comment by imasen** [comment]
This is a feature which will also be useful for us. Currently we are not using Docker-Plugin. One reason is, that we need to expose ports which are randomly assigned to containers on their creation and make them available as environment variable in a build.  A project can use this environment variable to startup a tomcat on a specific port and run Selenium Grid tests against it.

**Comment by KostyaSha** [comment]
For ports there is an entry, bind them manually.

**Comment by imasen** [comment]
@KostyaSha the -p is not enough to use !dynamic! ports in build-jobs. We assign one on the docker host uniq, but randomly generated port to make tomcat servers available for integration tests. On a container start we set a ENV variable inside the container to value of the randomly generated port. The tomcat start and uses for -Dtomcat.http.port=${randomport}.

**Comment by maxmeyer** [comment]
@KostyaSha 

Here's my real world example:

I would like to setup docker registry + jenkins in a closed setup environment. The only way out is via a central coporate proxy.

    jenkins slave container -> local proxy container -> coporate proxy -> the internet

The "jenkins slave container" is going to be run on the same host as jenkins. To download system packages etc. it needs access to the internet. We're using a coporate proxy requiring user authentication. To not share credentials between each and every "jenkins slave container" I'm going to setup up a local proxy container and pass in http://local_proxy:3128 into every "jenkins slave container". But to make this possible I need a form field to do so.

**Comment by denouche** [comment]
Hi!

+1 for this feature !

I would like to be able to do something like:
```
$ docker run -it --rm -e "DOCKER_GROUP_ID=$(getent group docker | cut -d':' -f3)" -v /var/run/docker.sock:/var/run/docker.sock denouche/jenkins-agents:base-debian8.1
```

Thanks in advance!

**Comment by 1beb** [comment]
Use case, passing github authentication tokens to a dockerfile that requires them.

**Comment by Manuri** [comment]
@KostyaSha
 +1 for this feature.
There is a configuration for this for normal nodes in jenkins and we use it. For docker containers also, it would be great to have it because otherwise we'll need to have those environment variables in docker images and when it is needed to change them we'll need to edit the image. But if we can have such a configuration option for environment variables in jenkins configuration it would make life easy.

**Comment by ndeloof** [comment]
Can't you use Docker agent template's "Container settings > Environment" for this purpose ?
please reopen if still relevant
