### ISSUE TITLE
Decouple images and cloud configuration

### ISSUE THREAD

**Issue by bartmeuris** [jenkinsci/docker-plugin#159]
Currently, an image configuration is attached to a "cloud" configuration. However when using multiple Docker build hosts, this duplicates a lot of work. Images should be pulled anyway, so images could be configured once centrally, for example on the `/docker-plugin/` (Manage Jenkins -> Docker) page.

This would greatly increase flexibility regarding adding more capacity to your build farm.

**Comment by KostyaSha** [comment]
This is mostly a docker lack of clustering support. Assuming that there are hot discussions about it i see no reason to refactor current docker-plugin code. You can try look on mesos-plugin that adds flexibility.

**Comment by bartmeuris** [comment]
Docker/swarm would then probably be the better choice, since it acts like a docker bridge.

**Comment by hawky-4s-** [comment]
We are using the docker-plugin with Swarm. Using Swarm solved some issues for us with the docker-plugin but created new ones when you run a cluster of heterogeneous machines.

**Comment by KostyaSha** [comment]
Could you describe how it used? What is running what for what? :)

**Comment by KostyaSha** [comment]
Seems swarm is a solution.

**Comment by dreilly1982** [comment]
I initially opened issue #257 as the language in this issue didn't quite hit what I was aiming for.  That being said, docker swarm is not a suitable solution for the decoupling of an images from cloud configuration as it is now.

Decoupling moving the image configuration out to a separate menu, similar to how the nodes are currently configured, would make management of multiple templates for differing projects much more manageable.  Even though the use case of multiple build hosts/swarms is valid, even if you are only using one build host/swarm, managing several different images is cumbersome in its current implementation.

**Comment by KostyaSha** [comment]
Sorry, seems wrong linking.

**Comment by dreilly1982** [comment]
LOL, ok thanks, that one I did miss entirely.
