### ISSUE TITLE
Fix Shading / Tests

### ISSUE THREAD

**Issue by magnayn** [jenkinsci/docker-plugin#163]
As partially expected, #157 didn't quite fix the guava/shading issue.

I have created a work branch (shade-dependencies) to attempt to fix this. I think it might be working for Jenkins, but it fails if you run the tests, which I don't understand. I have not tried with any kind of security.

Broadly, the issue is this:

We use docker-java. docker-java has a number of dependencies. Some of these dependencies (notably guava and http commons) clash with Jenkins' own, and because the plugin infrastructure follows a 'jenkins first, then plugin', this causes all manner of class-not-found fails. 

We are not the first people to come across this. I have cheerfully ripped the pattern from jclouds-plugin, which generates a shaded jar and then uses that.

I have not tested thoroughly. Particularly it is currently failing when the tests are run, with (for example)

```bash
com/nirima/jenkins/plugins/docker/DockerSlave/configure-entries.jelly(org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: <?jelly escape-by-default='true'?> is missing
	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyCheck.runTest(JellyTestSuiteBuilder.java:98)
```

@jglick had useful stuff to say on the mailing list and may have some insight into what's going on above; @thomassuckow was also working on this.

**Comment by KostyaSha** [comment]
`<?jelly escape-by-default='true'?> is missing` fix it.

**Comment by magnayn** [comment]
Ah, great! I wonder why it only started complaining about that now..

I've pushed that update.

Could people give this branch a spin? If everything looks OK, I'll merge into -master, then I think we should release it as 0.9 (as there's lots of fixes) and move on to a 0.10 for new stuff.

WDYT?

**Comment by KostyaSha** [comment]
Maybe you changed core dep and new tests appeared.What do you mean about branch? You can fix jelly directly and check that there is no plain html in some variable (then they need to be not escaped). 
We can release some 0.9-beta-1 for testing. I'm very busy right now, but can join for testing.

**Comment by magnayn** [comment]
I've pushed what I *think* should be fixes for the shading problems to a separate branch (shade-dependencies) as I was a bit worried that it might not be totally correct. If you can try that just as a sanity check (I.E: that you don't get wierd classnotfounds), a 0.9-beta1 sounds a good idea.

**Comment by KostyaSha** [comment]
For dependencies i think better consult with @jglick because i don't know classloading internals in jenkins.

**Comment by thomassuckow** [comment]
I agree that we should seek the blessing of someone in the Jenkins core community that has more experience with this.

**Comment by thomassuckow** [comment]
We do need to get a 0.9 out the door. I've been running a build of the master branch (With @magnayn docker-plugin in the snapshot repo) for a while without issue (except shading).

On the branch I am getting Could not find artifact com.github.jnr:jnr-x86asm:jar:1.0.2
Did you build that package by hand?

**Comment by KostyaSha** [comment]
I also using custom patched build. For me it was absolutely ruined by tags #144 and #164

**Comment by magnayn** [comment]
>
>
> On the branch I am getting Could not find artifact
> com.github.jnr:jnr-x86asm:jar:1.0.2
> Did you build that package by hand?
>

​That sounds like it's possibly another dependency that's duplicated in
jenkins.. :

(docker-java uses it) :

 +- com.github.jnr:jnr-unixsocket:jar:0.3:compile

[INFO]    |  +- com.github.jnr:jnr-ffi:jar:1.0.3:compile

[INFO]    |  |  +- com.github.jnr:jffi:jar:1.2.8-SNAPSHOT:compile

[INFO]    |  |  +- com.github.jnr:jffi:jar:native:1.2.8-SNAPSHOT:runtime

[INFO]    |  |  +- org.ow2.asm:asm:jar:4.0:compile

[INFO]    |  |  +- org.ow2.asm:asm-commons:jar:4.0:compile

[INFO]    |  |  +- org.ow2.asm:asm-analysis:jar:4.0:compile

[INFO]    |  |  +- org.ow2.asm:asm-tree:jar:4.0:compile

[INFO]    |  |  +- org.ow2.asm:asm-util:jar:4.0:compile

[INFO]    |  |  \- com.github.jnr:jnr-x86asm:jar:1.0.2:compile

[INFO]    |  +- com.github.jnr:jnr-constants:jar:0.8.4:compile
[INFO]    |  \- com.github.jnr:jnr-enxio:jar:0.4:compile
​

The way Jenkins doesn't properly isolate plugins is a serious PITA!
​

**Comment by magnayn** [comment]
I do apologise, I thought you meant that was a shading issue.

No, it ought to be a dep in central:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jnr-x86asm%22

**Comment by thomassuckow** [comment]
Strange. When I get a chance I'll have to look into it further. It does appear to be in Central, but maven isn't downloading it.

Until then, I will blame the corporate firewall... because I can, even though it is probably something else.

**Comment by magnayn** [comment]
Closing as the jelly tag fix seems to work.

I have been running this branch in production for a week or so, and it seems to be ok so merging it in.

**Comment by KostyaSha** [comment]
@magnayn could you merge next your branches through PR?
