### ISSUE TITLE
check integration with jobConfigHistory plugin

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#167]
seems config history store every created/deleted slave change that polutes config history

**Comment by KostyaSha** [comment]
@jglick mentioned this will be solved by with splitting out Cloud configuration  to separate directory.

**Comment by jglick** [comment]
1.607+ stores each `Node` in its own XML file.

**Comment by KostyaSha** [comment]
@jglick thanks for info
