### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by yarikoptic** [jenkinsci/docker-plugin#169]
I think I am hit by https://github.com/jenkinsci/docker-plugin/issues/121 but it is not included in any release yet.  Would it be possible to cut a new release since it has been awhile since 0.8. thanks in advance

**Comment by lexandro** [comment]
+1

**Comment by chiaen** [comment]
+1

**Comment by magnayn** [comment]
Can you try the -beta1 in the experimental repository?

**Comment by yarikoptic** [comment]
sorry guys...  not using it any more
 cheers

**Comment by thomassuckow** [comment]
Out of curiosity, what are you using?
I am keeping an eye on Kubernetes, but unfortunately it may be October before I can put together a test environment.

**Comment by yarikoptic** [comment]
@thomassuckow decided to get back to buildbot.  FWIW here is my initial setup for new project:  https://github.com/datalad/buildbot
