### ISSUE TITLE
[FeatureRequest] Commit/Tag/Push on failure

### ISSUE THREAD

**Issue by electrical** [jenkinsci/docker-plugin#175]
Use case for this is that we use docker containers for testing and we want to save the container when it fails.
This way a developer can pull in the image and run it and find out what went wrong internally.

**Comment by electrical** [comment]
I just saw there is already a PR for this at https://github.com/jenkinsci/docker-plugin/pull/132
From what i see it should do what I need.

**Comment by KostyaSha** [comment]
Duplicate for #132
