### ISSUE TITLE
Build stability

### ISSUE THREAD

**Issue by hawky-4s-** [jenkinsci/docker-plugin#176]
Hi,

Could we please get the plugin to a point, where it is stable to build the plugin. Everyone who wants to help in the development / sending PRs should be able to build it with `mvn clean install` without any special knowledge where to get any missing artifacts. For example, add the Sonatype OSS snapshot repository to the pom or use released versions of the `docker-java` plugin.

We are maintaining our own branch with many fixes but won't invest in sending PRs when the plugin is in an uncertain state.

Cheers

**Comment by KostyaSha** [comment]
As it was already described @magnayn has some patches that are waiting upstream merges. This duplicates this issue https://issues.jenkins-ci.org/browse/JENKINS-26517
