### ISSUE TITLE
volumes binding is no longer working

### ISSUE THREAD

**Issue by tjamet** [jenkinsci/docker-plugin#182]
Setting the 'Volumes' advanced option inside a cloud with a value  of "/tmp/docker-jenkins:/tmp/docker-test-volume" does not bind container /tmp/docker-test-volume to  host /tmp/docker-jenkins any longer.

It can  be reproduced cloning "https://github.com/tjamet/jenkins-docker-master.git" branch " test/docker-volume" and launching a build on docker-volume after having updating the docker plugin

**Comment by KostyaSha** [comment]
Please move issue description to PR and close this issue. PR itself is issue no need in duplicating. Thanks.
