### ISSUE TITLE
Exception while provisioning leaks container

### ISSUE THREAD

**Issue by maafy6** [jenkinsci/docker-plugin#188]
From time to time, the docker plugin will attempt to provision a slave and, after creating and starting the container, will hit an exception trying to inspect the container. When this happens, no slave is created in Jenkins and the container is not cleaned up. A few of my images use an instance count of 1, and so this effectively blocks that image from being used until I manually clean up the containers.

**Comment by KostyaSha** [comment]
Please provide logs, in what state container exist on docker host?
Was ssh slave connection attempt performed?

**Comment by maafy6** [comment]
Container is up and running, exception was thrown at the end of `DockerTemplateBase.provisionNew()` inside `DockerSlave.provision()`, before it even tried the ssh connection. (Sorry, logs are a pain for an air-gapped network.)

I'm trying out a fix right now, if everything looks good after lunch I'll submit a PR with what I'm running. Short version of the plan for the PR is to have `DockerTemplateBase.provisionNew()` just return a string and do the inspect container later, then if that hits an exception, try and clean up the container.

**Comment by KostyaSha** [comment]
`docker ps -a` after issue happen please

**Comment by KostyaSha** [comment]
Moving discussion to #189
