### ISSUE TITLE
DockerComputerLauncher always connects to docker host

### ISSUE THREAD

**Issue by srwalter** [jenkinsci/docker-plugin#190]
DockerComputerLauncher gets the port for SSH from the binding as it should, but then it always assumes that the IP to connect to is the same as the docker host itself.  This is incorrect behavior in several scenarios, such as when the port is only bound to one interface, or the docker host is actually a Docker Swarm.

**Comment by KostyaSha** [comment]
PR itself is Issue, closing this.
