### ISSUE TITLE
Problem with parsing version in 0.8

### ISSUE THREAD

**Issue by mbogner** [jenkinsci/docker-plugin#193]
Please see https://issues.jenkins-ci.org/browse/JENKINS-24408

There seems to be a bug in version parsing function. Is this already fixed in 0.9.0-SNAPSHOT?

**Comment by jgriffiths1993** [comment]
This was fixed with the API migration to java-docker (commit: b1377e7bca80c6be49668e4d114469736d6b9262) so yes, it's fixed now :smiley_cat:

**Comment by mbogner** [comment]
Thanks for quick answere. Any idea when 0.9 will be ready for use?

**Comment by KostyaSha** [comment]
@mbogner 0.9 beta available in experimental update center.

**Comment by mbogner** [comment]
Works for me =)
