### ISSUE TITLE
Container ID variable

### ISSUE THREAD

**Issue by laetificat** [jenkinsci/docker-plugin#194]
I cannot find out what the container ID is for the current running job, so I am not able to use commands like docker cp. I have read the documentation but I haven't found anything. Is there a way to get the container ID?

**Comment by jgriffiths1993** [comment]
Do you mean when using a docker container as a slave?

**Comment by laetificat** [comment]
Yes exactly, I dynamically create a container to test a project in, but I need to extract some files. The docker cp command would be really useful in this case, but I need a way to pass the container ID.

**Comment by jgriffiths1993** [comment]
The container ID should be in the name of the slave (e.g. 321afecb5ca7@mycloud1) whilst the job is running.

The container (should be) stopped/removed once the job finishes so probably select to commit the container once the build has finished and inspect it later.

I've submitted PR #192 to keep containers running after jobs complete.

**Comment by laetificat** [comment]
Hmm, I could work with the slave name. Right now I am trying to see if I can mount the folder with those logs and copy those logs to my build folder while the container is still busy, it's not pretty, but it should work.

I do not want to commit the container, this is purely just spinning up a slave, run tests, and then destroy it. All I want are the test results.

**Comment by thomassuckow** [comment]
Why not publish the results as artifacts?

**Comment by KostyaSha** [comment]
You should use post-build actions if you want something copy to external place, parse test results or attach to build as artifact.

Fully duplicates #195

**Comment by KostyaSha** [comment]
About variables: afaik node contribute properties to variables and labels.
