### ISSUE TITLE
Help: Eclipse import build error

### ISSUE THREAD

**Issue by phuna** [jenkinsci/docker-plugin#196]
Hi,
Sorry for a newbie question. I import parent project into eclipse using "Import existing Maven projects" so it creates 3 projects: ```docker-java-shaded```, ```docker-plugin```, ```docker-plugin-parent```.
```docker-plugin``` project is failed to build because it can not find ```shade.com.google.*``` class.
Also when opening ```pom.xml``` of ```docker-plugin```, errors say:
```
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:build-helper-maven-plugin:1.7:add-source (execution: add-source, phase: generate-sources)
```
Building using command line works well though.

**Comment by KostyaSha** [comment]
Just remove this duplicated trash
https://github.com/KostyaSha/docker-plugin/commit/666a9efc68944a0ac07538299000049a7d1fb326#diff-f7e98988edc6cf6e8760d3fd2f3e436cL96

**Comment by KostyaSha** [comment]
For projects order you should compile java-shaded firstly, call build for it directly, or just call package on parent.

**Comment by phuna** [comment]
I've tried to clean/rebuild each project separately (```docker-java-shaded```, ```docker-plugin```) but it still show error at ```shaded.com.google.*``` class. Clean/rebuild on parent project (```docker-plugin-parent```) does not help either.
I've searched through issue list and found no one ask about this so I'm curious what tool/build steps other use?

**Comment by KostyaSha** [comment]
Are you trying current master?

**Comment by phuna** [comment]
Yes, I pulled from current master.

**Comment by phuna** [comment]
Just to be clear: When I open ```DockerCloud.java``` file I see error marked on ```shaded...``` imports.
In my previous answer, Clean/Build means clicking on menu Project > Clean
If I right click, choose ```Run As``` then input goal ```clean package``` then it report success just like running mvn from commandline

**Comment by KostyaSha** [comment]
Idea also can't compile starting from parent
https://github.com/jenkinsci/docker-plugin/commit/bdde16c512c9f72eabc209b7d369f258c987a7af#commitcomment-10513414

**Comment by KostyaSha** [comment]
Package call on parent works, to skip this errors you need manually attach docker-java-shaded.jar as library for docker-plugin module. Shading is used wrong in this plugin so you need do this tricks.

**Comment by jgriffiths1993** [comment]
It's probably a stupid question, but why is the shading necessary for this plugin?

**Comment by KostyaSha** [comment]
@jgriffiths1993 long story, use search with "shade/shading" keywords https://github.com/jenkinsci/docker-plugin/pull/156 Libraries need to be shaded to exclude classloading conflicts

**Comment by phuna** [comment]
@KostyaSha Thank you. manually adding docker-java-shaded.jar to build path of docker-plugin project solves the compile error. 
Is this the problem of m2e in handle module dependency? Is there any solutions which make this dependency understandable to eclipse?

**Comment by KostyaSha** [comment]
@phuna Well, this is nature of shading. Shading instrument bytecode and relocates package names. Somebody need fix maven-hpi-plugin to support maven-shade-plugin. This will exclude using shaded package names in sources.

**Comment by phuna** [comment]
@KostyaSha Thank you. I think this can be closed now.

**Comment by KostyaSha** [comment]
@phuna i provided some cleanups in #199 i think i will merge them and people will provide feedback  :blush:

**Comment by KostyaSha** [comment]
Merged, please try master. As side affect of manual attachment shaded jar you will see class conflicts during shading. See no better ways right now, but i will try investigate shading issue more later.
