### ISSUE TITLE
Error when test connection: Can't find any implementation of 'com.github.dockerjava.api.command.DockerCmdExecFactory'

### ISSUE THREAD

**Issue by phuna** [jenkinsci/docker-plugin#197]
I pull latest code, build (```mvn clean package``` on parent project), install to jenkins, then test connection and this error occur:
```javax.servlet.ServletException: java.lang.RuntimeException: Fatal: Can't find any implementation of 'com.github.dockerjava.api.command.DockerCmdExecFactory' in the current classpath```
I've checked the generated ```.hpi``` file and can see ```docker-java-shaded-0.9.0-SNAPSHOT.jar``` included.
Did I miss some build steps?

Thank you,

**Comment by jgriffiths1993** [comment]
This is a bug. It only affects the Test Connection as far as I can see.

In the DockerCloud.java doTestConnection:

    DockerClient dc = DockerClientBuilder.getInstance(config.build()).build();

Should be:

    DockerClient dc = DockerClientBuilder.getInstance(config.build())
                    .withDockerCmdExecFactory(new DockerCmdExecFactoryImpl())
                    .build();

I'll submit a PR
