### ISSUE TITLE
Be able to fix public IP

### ISSUE THREAD

**Issue by guilhem** [jenkinsci/docker-plugin#20]
Currently all ports are bind on `0.0.0.0`
It may be useful (and secured) to be able to fix another IP (for example the IP used to call API ;) )

In my case, Host server have a public address and a internal bridge. I only want to see docker vm accessible by internal bridge :)

More generally, be able to pu our own config in API can be great.

**Comment by KostyaSha** [comment]
@guilhem do you want enter address manually or resolve from interface name, etc?

**Comment by pjdarton** [comment]
I believe that the ability to specify which network a container is visible on was added in [this commit](https://github.com/jenkinsci/docker-plugin/commit/d5553d47c95defbb70079a5eb263fd6a61ebbc31) in March 2016.
