### ISSUE TITLE
Question: Docker in Docker Builds failing ...

### ISSUE THREAD

**Issue by hcguersoy** [jenkinsci/docker-plugin#212]
Hi Folks,

just wanted to ask if someone else is observing the behavior below.

Jenkins:  1.596.2
Docker : 1.6
Slave Image: Docker in Docker Image based on https://github.com/jpetazzo/dind, based on trusty
Plugin: 0.9-rc1

Building the official MySQL 5.6 image from scratch with Docker 1.6 on my system works fine (Ubuntu 14.04).

Then I try to build this image in a Docker Slave (running in a DinD Image) then this build fails without any error message:
```bash
Docker Build Response : {"stream":"Step 0 : FROM debian:wheezy\n"}
{"stream":" ---\u003e b3d362b23ec1\n"}
{"stream":"Step 1 : RUN groupadd -r mysql \u0026\u0026 useradd -r -g mysql mysql\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e f077a75e4421\n"}
{"stream":"Step 2 : RUN apt-get update \u0026\u0026 apt-get install -y perl --no-install-recommends \u0026\u0026 rm -rf /var/lib/apt/lists/*\n"}
{"stream":" ---\u003e Running in 90fa56ffd604\n"}

Build step 'Build / Publish Docker Containers' marked build as failure
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

All other image builds run fine. 
I've no idea why this fails - any suggestions?

**Comment by hcguersoy** [comment]
closed with to create a issue with more info.

**Comment by KostyaSha** [comment]
Well, you can reopen and update info. But from this description i have no idea what fails
