### ISSUE TITLE
DinD build fails

### ISSUE THREAD

**Issue by hcguersoy** [jenkinsci/docker-plugin#213]
(supersede https://github.com/jenkinsci/docker-plugin/issues/212 ) 
Hi Folks,

I'm observing a strange behavior with the 0.9-rc1 then building Images in Docker Slaves.

Jenkins:  1.596.2
Docker : 1.6
Slave Image: Docker in Docker Image based on https://github.com/jpetazzo/dind, similar to https://github.com/tehranian/dind-jenkins-slave
Plugin: 0.9-rc1

Building the official MySQL 5.6 image from scratch with Docker 1.6 on my system works fine (Ubuntu 14.04). The dockerfile can be found here: https://github.com/docker-library/mysql/tree/master/5.6

Then I try to build the same image in a Docker Slave (running in a DinD Image, see above) then this build fails without any error message:

``` bash
Docker Build Response : {"stream":"Step 0 : FROM debian:wheezy\n"}
{"stream":" ---\u003e b3d362b23ec1\n"}
{"stream":"Step 1 : RUN groupadd -r mysql \u0026\u0026 useradd -r -g mysql mysql\n"}
{"stream":" ---\u003e Using cache\n"}
{"stream":" ---\u003e f077a75e4421\n"}
{"stream":"Step 2 : RUN apt-get update \u0026\u0026 apt-get install -y perl --no-install-recommends \u0026\u0026 rm -rf /var/lib/apt/lists/*\n"}
{"stream":" ---\u003e Running in 90fa56ffd604\n"}

Build step 'Build / Publish Docker Containers' marked build as failure
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

This fails always on the same step.

The I build a custom mysql Image this happens:

```
{"stream":"Step 13 : RUN DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes install mysql-client\n"}
{"stream":" ---\u003e Running in 54cab64d048c\n"}
{"stream":"Reading package lists..."}
{"stream":"\n"}
{"stream":"Building dependency tree..."}
{"stream":"\nReading state information..."}
{"stream":"\n"}
{"stream":"The following extra packages will be installed:\n  mysql-common mysql-community-client\n"}
{"stream":"The following NEW packages will be installed:\n  mysql-client mysql-common mysql-community-client\n"}
{"stream":"0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 22.2 MB of archives.\nAfter this operation, 72.9 MB of additional disk space will be used.\nGet:1 http://repo.mysql.com/apt/ubuntu/ precise/mysql-5.6 mysql-common amd64 5.6.24-1ubuntu12.04 [708 kB]\n"}
{"stream":"Get:2 http://repo.mysql.com/apt/ubuntu/ precise/mysql-5.6 mysql-community-client amd64 5.6.24-1ubuntu12.04 [21.5 MB]\n"}

Build step 'Build / Publish Docker Containers' marked build as failure
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

In the Jenkins log I can find this:

```
May 04, 2015 11:39:49 AM SEVERE hudson.remoting.SynchronousCommandTransport$ReaderThread run
I/O error in channel 91357111650f@slave1
java.io.IOException: Unexpected termination of the channel
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:50)
Caused by: java.io.EOFException
    at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2325)
    at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2794)
    at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
    at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
    at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
    at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
    at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
```

On the docker host running the slaves dead containers can be found:

``` bash
CONTAINER ID        IMAGE                                                                     COMMAND                CREATED             STATUS                           PORTS               NAMES
54cab64d048c        ad80b16467c0ba8909b0717c3c024903f0b82772c15bc8a03bd17df7c1c80f4f:latest   "/bin/sh -c 'DEBIAN_   9 minutes ago       Exited (137) 8 minutes ago                           hopeful_lalande
```

These dockerfiles build without any problems triggered from docker cli (`docker build ....`).
And these jobs run fine without any change to the configuration with the version 0.8 of the plugin.

@KostyaSha Did you need more Info? I couldn't post the dockerfile for the custom mysql image but could send it via mail...

**Comment by KostyaSha** [comment]
I have no time to investigate it right now. But i will be glad to see minimised instruction for reproducing based on evarga/jenkins-slave. Could you also provide steps for configuration?
Thanks.

**Comment by hcguersoy** [comment]
Hi,

I'll provide you a way to reproduce this but it would not be the original everga/jenkins-slave as it has no DinD support.

**Comment by hcguersoy** [comment]
Hi,

changing the Version of the docker-java lib from 1.3 to 1.4 and build from master (commit 024877a) this error doesn't show up in my first tests.
I'm going to test with limited bandwidth on the interfaces to ensure that I've no timeout issues, too.

BTW, why the docker-java is not upgraded to 1.4?

**Comment by KostyaSha** [comment]
docker-java likes breaking APIs, so probably i had no time to update it. I plan update it and do hotfix release on this weekend.

**Comment by KostyaSha** [comment]
Docker-java updated in master

**Comment by DusteDdk** [comment]
I'm able to successfully build docker images with docker inside container slaves spun up via this plugin.
There is one caveat (which I'm going to add as an issue):
Within the context of your slave container (when run by the master) the DOCKER_HOST environment variable is set, meaning that the docker daemon inside your slave container is the same docker daemon as used outside.
This can be fixed by doing unset DOCKER_HOST as the first thing before starting docker inside the slave container.

**Comment by ndeloof** [comment]
closing as obsolete
