### ISSUE TITLE
Don't run slave during maintenance mode

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#214]
Blocked by https://issues.jenkins-ci.org/browse/JENKINS-20967

**Comment by thomassuckow** [comment]
This more a bug in Jenkins core... You don't necessarily want to not spawn the slave if the job MUST run.  The matrix subtasks are an example, otherwise the system will never reach idle because the parent job is waiting on the subtasks.

**Comment by KostyaSha** [comment]
But any subtask will be just in queue and will continue building when maintenance mode ends

**Comment by thomassuckow** [comment]
But the matrix parent task isn't in the queue, it is in progress waiting on all the subtasks to complete. When jenkins is trying to restart and ends up in maintenance mode it will deadlock and never restart.

**Comment by KostyaSha** [comment]
Hm, in my case i have no matrix jobs and running slaves has no sense...

**Comment by thomassuckow** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-20967

Those subtasks have a specific type that is not blocked by maintenance mode.
