### ISSUE TITLE
Round robin for different docker clouds

### ISSUE THREAD

**Issue by tisoft** [jenkinsci/docker-plugin#216]
We have 2 different docker hosts configured inside jenkins as docker clouds. Both clouds can each have 4 docker containers running simultainiously. Unfortunatly the second docker host is only used, when the first one is completly filled up. So only when we have more than 4 parallel builds, the 2nd host is used. Is it possible to implement a round robin system, that evenly distributes the load to all clouds, that can provide a container with a specific label?

**Comment by KostyaSha** [comment]
AFAIK swarm supports docker api. https://docs.docker.com/swarm/scheduler/strategy/

**Comment by thomassuckow** [comment]
I have also debated kubernetes for this use case, but haven't had time to investigate. If you try it, I would love to hear your findings.
