### ISSUE TITLE
For version 0.9.1-rc1, on nodes with Availability 'keep on-line as much as possible' Jenkins default Env Vars seems to be invalid 

### ISSUE THREAD

**Issue by bencao** [jenkinsci/docker-plugin#217]
## The problem
At least 3 env vars are showing **previous Job's value** for Jobs running on Docker nodes which the Availability is 'keep on-line as much as possible'.
- JOB_NAME
- BUILD_TAG
- BUILD_ID

Other default Jenkins Env Vars may also have the problem as well.

## Steps for recurrence
- setup a Docker cloud slave node which has Availability set to 'keep this slave on-line as much as possible' 
- run 2 jobs named 'test' and 'test1' sequentially, the shell content for each job is simply 
```shell
env
```
- The output for Job 'test' will be as expected
```shell
+ env
JOB_NAME=test
BUILD_ID=13
BUILD_TAG=jenkins-test-13
```
while for Job 'test1' it still shows the same value for previous Job 'test'
```shell
JOB_NAME=test
BUILD_ID=13
BUILD_TAG=jenkins-test-13
```
which seems a bug of docker plugin.

**Comment by KostyaSha** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue#Howtoreportanissue-WhatinformationtoprovideforEnvironmentandDescription
