### ISSUE TITLE
retentionStrategy idleMinutes resets with every Save in Jenkins configuration

### ISSUE THREAD

**Issue by j4b0l** [jenkinsci/docker-plugin#220]
## Environment
Jenkins 1.613
Docker plugin 0.9.0-rc1
## Steps to reproduce
Go to 'Manage Jenkins' -> 'Configure System' and create docker Cloud with at least one template, set Availability to Docker Once Retention Strategy and Idle timeout to any value greater than 0. Save configuration.
Go to 'Manage Jenkins' -> 'Configure System' again and save configuration without changing anything.
## Expected result
Configuration is logically unchanged.
## Current behaviour
Configuration resets value of idleMinutes to 0.
If 'Advanced...' options for template are displayed, value is filled with 0 in the filed regardless configuration in xml file, even before the second Save.
Example difference in config.xml from before and after the second save in configuration:
```
$ diff -C 1 before_config.xml after_config.xml
*** before_config.xml	2015-05-18 12:58:54.739415374 +0200
--- after_config.xml	2015-05-18 13:00:48.395410480 +0200
***************
*** 184,186 ****
            <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
!             <idleMinutes>1</idleMinutes>
              <idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">0</idleMinutes>
--- 184,186 ----
            <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
!             <idleMinutes>0</idleMinutes>
              <idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">0</idleMinutes>
***************
```

**Comment by KostyaSha** [comment]
Seems found why

**Comment by KostyaSha** [comment]
For having configurable values that are hardcoded in any other cloud provides i was forced to inherit classes. idleMinutes was used but not persisted. It should be fixed in master now.
I will be very glad to get any feedback for this experimental features :smiley:

**Comment by j4b0l** [comment]
Will check after weekend.
Anyway, I've also checked the other retention strategies before filing this bug. Only 'Docker Once' was resetting configuration, all of the others seemed fine. Will check that.
