### ISSUE TITLE
0.9-rc1 does not send volume values in /containers/create query

### ISSUE THREAD

**Issue by ptorkko** [jenkinsci/docker-plugin#222]
I'm setting up some docker slaves, and everything seems to work fine, except that the volumes I wan't aren't available.

I set up a logger for the docker java client and it seems it's not sending the volume values at all.

    18 > POST http://localhost:4243/containers/create
    18 > Accept: application/json
    18 > Content-Type: application/json
    {"name":null,"capAdd":null,"capDrop":null,"Hostname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"Cpuset":null,"AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":["22/tcp"],"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":["/usr/sbin/sshd","-D"],"Entrypoint":null,"Image":"jenkins-java8","Volumes":{},"WorkingDir":"","DisableNetwork":false,"ExposedPorts":{},"HostConfig":{"Binds":null,"Links":null,"LxcConf":null,"PortBindings":null,"PublishAllPorts":false,"Privileged":false,"Dns":null,"DnsSearch":null,"VolumesFrom":null,"ContainerIDFile":null,"CapAdd":null,"CapDrop":null,"RestartPolicy":null,"NetworkMode":null,"Devices":null,"ExtraHosts":null}}

The actual value of the volume field is e.g.:

    /opt/jenkins/data:/home/jenkins/data

I tested with more volumes too, makes no difference.

**Comment by KostyaSha** [comment]
Duplicates https://github.com/jenkinsci/docker-plugin/pull/183
