### ISSUE TITLE
Trailing space in image tag

### ISSUE THREAD

**Issue by Suirtimed** [jenkinsci/docker-plugin#236]
I had a docker template with an extra space at the end of it's name in the image tag inside the com.nirima.jenkins.plugins.docker.DockerTemplate tag.  It was causing the build to fail because there was no image matching that name (the one with the trailing space).  I'm not sure if this is something you can check for or correct, but it took quite a while to isolate.

**Comment by KostyaSha** [comment]
thanks, it is planned to rework configuration handling
