### ISSUE TITLE
share templates configuration between clouds

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#238]
Create some templates storage in Descriptor and allow for choosing in Clouds?
/cc @magnayn

**Comment by KostyaSha** [comment]
TemplateBase itself very generic, but Slave connection may differ?

**Comment by magnayn** [comment]
Yep, exactly.

Something like
- define a set of templates ouside of the individual clouds
- add references to each template you want to allow to be used (possibly
with 'add all' or regex-style (jenkins-*) options).

[​DockerSlave]​ (1)<----->(*) [DockerTemplateReference]
(*)------->(1)[DockerTemplate]

​Benefit is basically DRY​ when you use, basically, the same template in
multiple clouds.

**Comment by thomassuckow** [comment]
If an add all option is available, there should probably also be "add all with repository". I have a few images that were manually transferred to a build machine and don't exist in a repository.

Though realistically, you have

```.*``` and ```.*/.*``` in regex land

**Comment by KostyaSha** [comment]
@thomassuckow in my case such builds were wiped very soon by "clean local images" checkbox that can be set in any job property. I can suggest setup registry just to be safe :)

**Comment by KostyaSha** [comment]
@magnayn btw, i have idea to use container labels, instead of image name. One image in jenkins can have different configurations. If configuration will be moved to storage, then templates will need UUIDS (like for credentials) that can be used with container labels for calculations and other. Then it will be possible to create periodic work that will cleanup forgotten by jenkins images.

**Comment by ndeloof** [comment]
I don't really get the benefit for having more than one Docker Cloud, as swarm allows to group physical resources under a common API. So closing this issue. Feel free to reopen if you have a concrete use-case to expose
