### ISSUE TITLE
Not anymore volume mounted on slaves

### ISSUE THREAD

**Issue by jpthiery** [jenkinsci/docker-plugin#239]
Hi,

Since my upgrade to 0.9.0 with Jenkins 1.615, my Doucker template with mounted point (explicit of with volumes-from) won't work anymore.

On Docker host side, Docker inspect don't provide inforamtions about thos mounted volumes.

Thanks for your help.
Jean-Pascal

**Comment by KostyaSha** [comment]
please provide cloud section from config.xml

**Comment by jpthiery** [comment]
```xml
<com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.9.0">
      <name>joconde</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate>
          <image>myimages/mavenjenkinsslave</image>
          <dockerCommand></dockerCommand>
          <lxcConfString></lxcConfString>
          <hostname></hostname>
          <dnsHosts/>
          <volumes>
            <string>/docker/maven:/root/.m2/repository</string>
            <string>/docker/maven/settings.xml:/root/.m2/settings.xml</string>
          </volumes>
          <volumesFrom2/>
          <environment/>
          <bindPorts></bindPorts>
          <bindAllPorts>false</bindAllPorts>
          <privileged>false</privileged>
          <tty>false</tty>
          <labelString>maven</labelString>
          <credentialsId>32a6b717-5392-42a7-9c71-46053671d53a</credentialsId>
          <idleTerminationMinutes>5</idleTerminationMinutes>
          <sshLaunchTimeoutMinutes>1</sshLaunchTimeoutMinutes>
          <jvmOptions></jvmOptions>
          <javaPath></javaPath>
          <prefixStartSlaveCmd></prefixStartSlaveCmd>
          <suffixStartSlaveCmd></suffixStartSlaveCmd>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/root/</remoteFs>
          <instanceCap>2147483647</instanceCap>
          <mode>NORMAL</mode>
          <retentionStrategy class="hudson.slaves.RetentionStrategy$Always"/>
          <numExecutors>1</numExecutors>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>http://joconde:4243</serverUrl>
      <containerCap>2147483647</containerCap>
      <connectTimeout>5</connectTimeout>
      <readTimeout>15</readTimeout>
      <version></version>
      <credentialsId></credentialsId>
    </com.nirima.jenkins.plugins.docker.DockerCloud>

```

Thanks

**Comment by KostyaSha** [comment]
And configuration screenshot with volumesfrom section

**Comment by jpthiery** [comment]
![2015-05-29 12_46_09-configure system jenkins](https://cloud.githubusercontent.com/assets/1012203/7881216/c731c6da-0600-11e5-8aad-3f083834f971.png)

**Comment by jpthiery** [comment]
![2015-05-29 12_47_34-configure system jenkins](https://cloud.githubusercontent.com/assets/1012203/7881231/ef0b8628-0600-11e5-8e4f-c439b21e4d97.png)

**Comment by jpthiery** [comment]
I could reconfigure to get volumesFrom configuration.
I try to mount volumes with the host or other container with the volumes-from

**Comment by KostyaSha** [comment]
So what issue do you reporting if you are proving wrong info?

**Comment by jpthiery** [comment]
I will try to get some log about the Docker request create this afternoon.

**Comment by KostyaSha** [comment]
Please provide configuration, logs and other info of your issue.

**Comment by jpthiery** [comment]
It seems taht we can't mount volumes (via volumes parameters or volumefrom) since the update to version 0.9.0 of plugin docker and the upgrade from Jenkins 1.614 to 1.615.
I will try to downgrade Jenkins ans provide you more informations soon.

Regards.

**Comment by KostyaSha** [comment]
I found why it may fail, but i also found inconsistency in docker-java library. Need fix library upstream firstly.

**Comment by KostyaSha** [comment]
Please verify this hpi https://jenkins.ci.cloudbees.com/job/plugins/job/docker-plugin/309/com.nirima$docker-plugin/ from #240

**Comment by KostyaSha** [comment]
Please update to 0.9.1 Multiple volumes support will appear later, now only first entry will work

**Comment by KostyaSha** [comment]
And in 0.9.2 this fixed. Thanks for report.

**Comment by jpthiery** [comment]
Work fine, Thanks a lot for your help.
