### ISSUE TITLE
Builds not connecting to docker after upgrade

### ISSUE THREAD

**Issue by Suirtimed** [jenkinsci/docker-plugin#255]
I have several issues associated with upgrading prbuilder plugin and auth plugin recently.  I have disabled that function from all of those jobs.  Now my docker based builds aren't working.  The containers are being built, but they aren't functional slaves.  I noticed that in the Cloud / Docker config that the Credentials are selecting "none" and no other options are available.  If I add a credential, then the list of global credentials is presented and I can select one of them.  Once I apply those changes and go back in to validate, I am back where I started with "none" selected and no option to choose any other credentials.

  Here is the log:

https://gist.github.com/Suirtimed/0d0797392fdb3fd2ad43

My System Information is:

https://gist.github.com/Suirtimed/0785e237046ac14928bb

**Comment by Suirtimed** [comment]
This does not appear to have anything to do with the docker plugin.  It appears only associated with the authentication credentials being passed in to access the git repositories from within the docker container.

**Comment by KostyaSha** [comment]
Is it still actual? According to log jenkins master just can't connect to docker slave. Check ssh credentials and try reproduce using evarga/jenkins-slave/
