### ISSUE TITLE
"idle timeout" can be set to 0 in DockerOnceRetentionStrategy

### ISSUE THREAD

**Issue by abustany** [jenkinsci/docker-plugin#258]
We've been running the Docker plugin since quite early versions (0.5 I'd say), and are now running it 0.8 on Jenkins 1.617. It looks like the "idle timeout" field of the DockerOnceRetentionStrategy got added at some point, and if not defined gets a default value of 0. That in turns means that if you're unlucky enough to get the CloudRetentionStrategy.check run while your container is still not fully up, the container will get killed.

The plugin should probably set a reasonable default value for "idle timeout" in case it's set to 0.

Also, not completely related, but is there a reason for using `PortUtils.canConnect(host, port).withEveryRetryWaitFor` instead of `PortUtils.canConnect(host, port).bySshWithEveryRetryWaitFor` in `DockerComputerLauncher` ? I'd say it'd make more sense to wait until SSH is really up, rather than just the container being up and Docker accepting connections without sshd being ready yet in the container...

**Comment by lanwen** [comment]
Second question related to #234

**Comment by KostyaSha** [comment]
DockerOnceRetentionStrategy is designed to have idle = 0. This strategy appeared here only because of "workflow" "support". It probably makes to try other strategy. If error persist, then issue not in docker implementation. I'm closing this, because such things are known and discussed many times on other issues.

**Comment by KostyaSha** [comment]
Termination errors will be also hotfixed soon in 0.9.x

**Comment by KostyaSha** [comment]
Hope first part is fixed now in 0.9.4
