### ISSUE TITLE
Container name

### ISSUE THREAD

**Issue by ojacquemart** [jenkinsci/docker-plugin#261]
Is there a way to start a named container?

The goal would be to stop the container already started with a name, in pre step action.
WIth the command line, it's possible with the argument --name .

**Comment by KostyaSha** [comment]
i plan review and expose more container options. If it will be valid - i will add in next releases.

**Comment by KostyaSha** [comment]
Sorry, what exactly plugin functionality do you want to use? Cloud provisioning or some publishers? Please describe more detailed.
