### ISSUE TITLE
0.9.4 Stuck in suspended

### ISSUE THREAD

**Issue by thomassuckow** [jenkinsci/docker-plugin#262]
I upgraded to 0.9.4 and slaves are not being removed after use.

Log shows the following, but slave never goes away:
```
Jul 06, 2015 11:58:16 AM FINE com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy
Disconnecting 35b1656908aa@host
```

**Comment by thomassuckow** [comment]
The slaves are also sometimes never used.

**Comment by KostyaSha** [comment]
my bad, dockerOnce strategy object was not recreated for every slave so it badly cached terminating boolean. I merged #234 and will better release 0.10.0 that will also have ssh launching fix. Do you want test current master before release?

**Comment by thomassuckow** [comment]
Master seems to be working fine

**Comment by KostyaSha** [comment]
@thomassuckow i tested locally with ~6 jobs in queue, but provisioner starts only 2 containers. Node deletion works fine excluding some known traces https://wiki.jenkins-ci.org/display/JENKINS/Remoting+issue

@thomassuckow was all configuration successfully migrated?

**Comment by KostyaSha** [comment]
[INFO] Uploaded: http://maven.jenkins-ci.org:8081/content/repositories/releases/com/nirima/docker-plugin/0.10.0/docker-plugin-0.10.0.hpi (11589 KB at 41.1 KB/sec)
