### ISSUE TITLE
Containers' default "Docker Command"

### ISSUE THREAD

**Issue by wiese** [jenkinsci/docker-plugin#266]
The configuration option "Docker Command" behaves as documented, 
> The command to run for this image, defaults to "/usr/sbin/sshd -D"

but this is not always the desired option. 
The default command performed on the container should be that mentioned within the Dockerfile (CMD, which becomes effective when nothing is passed to the *run* command). The content of the "Docker Command" field should only be passed to docker's *run* command if it is not empty. Otherwise the Dockerfile's CMD information is effectively lost, and has to be redundantly confirgured within Jenkins' configuration.

In our usecase the command is indeed supervisord, not sshd - Dockerfile describing a server used for an integration test with more than one piece of software (sure, *docker compose* is the way to go).

**Comment by KostyaSha** [comment]
This functionality is on the way of changing. Atm launcher controls command run because it needs to have ability to run any not prepared container.

**Comment by wiese** [comment]
Hi,

sure - a reasonable default RUN command is very useful in case a Dockerfile does not provide one.
On the other hand, if a Dockerfile provides one, it should not be simply overwritten (e.g. "[checkbox] Use container's default RUN command").
Is there a milestone for the mentioned change to come?

Thanks

**Comment by wiese** [comment]
(@github damn this button placement)

**Comment by KostyaSha** [comment]
I'm trying do everything optional as much as possible, but my first goal atm add stability and fix real blockers. In case of launchers i did first attempt to unhardcode them. Dockerfile may provide wrong run command that will end with endless provisioning errors. I need time for more detailed investigation of run/control process either i may be spammed with bugs. So no ETA atm, but of course any valid use cases need to be implemented.

**Comment by looztra** [comment]
on the other hand, you cannot say for sure that the default command will provide the expected result in any image.

So you are stuck between 2 potential bad default values.

At list providing a checkbox to let the user inherit from the container default command is a good first move.

**Comment by maxfields2000** [comment]
This is interesting, we built a tool to test container images before configuring them against Jenkins, then if the tests pass it  uses groovy to auto-configure the jenkins configuration page.

We verify the image has the necessary things inside it (proper version of java, is running SSH -D as it's command, has proper permissions for the jenkins home folder and user you ssh in as etc etc).  We did this before you made this change to enforce SSH -D at start up.

We'll probably continue to ensure it.  Build slaves IMO probably shouldn't be running supervisord  (in general containers probably shouldn't be either).

**Comment by wiese** [comment]
@maxfields2000 Suppose I want to build an integration test between 2+ pieces of software. Even if they are - in a perfect world - both defined in individual docker images, and we use docker compose to tie them together... sshd will still not be the _only_ binary to run.

**Comment by maxfields2000** [comment]
@wiese If I understand correctly you'd want Jenkins to talk to both of those as agents, as well as run your tests? Here we'd have the single "environment" container that jenkins has the slave.jar in, use docker compose to spin up your two containers on a dockerhost somewhere (they can be whatever they want, Jenkins doesn't care about anything but the container where the slave.jar is).  Then the automation would continue to trigger/run the integration tests against those two spun up containers (note: total container count here would be 3).  

If necessary it could even docker exec into those running containers etc.  They would never need SSH -D unless the apps you were testing needed it running for some reason.

That's just one of many ways to do it though, I'm not sure there's a "wrong" way.

**Comment by KostyaSha** [comment]
Could you draw your use cases in https://www.gliffy.com/go/html5/launch and attach screenshots? Rectangle for every VM/container/server, arrows for connections. 

I have some ideas and plans how modularise possible actions under docker hosts, but i need collect possible use cases.

**Comment by wiese** [comment]
We found a reliable work-around in specifying ENTRYPOINT (supervisord) instead of CMD in the image.
supervisord then orchstrates all binaries, namely sshd, and all applications needed for the integration test (be it docker-compose or old fashioned).

The most basic work-around, of course, always was and is to specify supervisord as the "Docker command" in Jenkins' config for the slave.

Unless the maintainers really want to keep this as a todo, I consider this not solved but documented and manageable.
