### ISSUE TITLE
DockerBuilderPublisher is broken

### ISSUE THREAD

**Issue by magnayn** [jenkinsci/docker-plugin#267]

**Comment by KostyaSha** [comment]
link to commit will be welcome

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/docker-plugin/commit/14d864b2fb3de85cbd8cb5194ae244965376dc03

**Comment by magnayn** [comment]
Testing fix now.

**Comment by KostyaSha** [comment]
Do you have PR?

**Comment by KostyaSha** [comment]
@magnayn btw, could you PR javadoc description for all Publishers because some of them are really weird for me i don't know how test them?

**Comment by KostyaSha** [comment]
@magnayn i hope it will be not difficult next time to do a PR.

**Comment by KostyaSha** [comment]
@lanwen please review fixes because they were caused by your commit.

**Comment by lanwen** [comment]
@magnayn Could you provide test case to reproduce fixed problem? (To avoid such fails in future)
