### ISSUE TITLE
Poll SCM not working then using docker containers and advanced SCM steps

### ISSUE THREAD

**Issue by tomaxsas** [jenkinsci/docker-plugin#268]
Hi. Is this normal behavior, that polling SCM doesn't work when using docker slaves? It works if I'm using only one branch, but if i want to poll more branch or use sparse checkout it requires a workspace and therefore doesn't poll. I have setup of workspace browsing, but it doesn't work for polling. in Jenkins core code i saw something regarding polling with cloud slaves, but dint understood that. Can someone explain more on this issue.

**Comment by KostyaSha** [comment]
Don't use polling that requires workspace.

**Comment by danpfe** [comment]
It's a bit old but had the same problem. Polling (at least with Git) doesn't seem to require a workspace when you explicitly define a list of branches to poll (i.e. origin/develop,origin/master). This is how I managed to prevent a docker container firing up every 5 minutes to run a build.
