### ISSUE TITLE
DockerOnceRetentionStrategy terminates container before job can be placed on it

### ISSUE THREAD

**Issue by thomassuckow** [jenkinsci/docker-plugin#270]
In docker-plugin 0.10, DockerOnceRetentionStrategy defaults to having 0 for the idleTimeout. In many cases it terminates the slaves before jobs can be placed on them.

The more jobs you have queued, the worse it gets. I had 12 containers spinning up and shutting down for hours with only the random occasional one doing work.

Workaround: Set the idleTimeout to anything greater than 0.

**Comment by KostyaSha** [comment]
Seems CloudAPI calls retention strategy check every one minute and think that slave isIdle just after restart. Could you add logger and provide logging?

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/docker-plugin/pull/234#issuecomment-110693413

**Comment by thomassuckow** [comment]
About a 1 minute log showing slaves are killed about 10 seconds after creation of SSH Launcher.

https://gist.github.com/thomassuckow/437af7aeaf8d5b2c7168

**Comment by KostyaSha** [comment]
Seems actions are async and having 0 as default is a really bad :(
I will set to 10 minutes and do hotfix on weekend. WDYT?
Btw, does 0.10 works good for you in general in comparison to previous versions?

**Comment by thomassuckow** [comment]
10 minutes seems reasonable.

Besides this issue, things have been going pretty smoothly. Slaves seem to come online more reliably & quickly (Have not actually measured, it just seems that way).

**Comment by KostyaSha** [comment]
Should 0 be converted to 10 for existed installations?

**Comment by thomassuckow** [comment]
I would. May even be worth not allowing 0.

**Comment by KostyaSha** [comment]
Interesting how it used in other cloud providers...

**Comment by thomassuckow** [comment]
What do you mean?

**Comment by KostyaSha** [comment]
I mean review other cloud plugins that using this strategy

**Comment by KostyaSha** [comment]
Updated to 10 minutes.
