### ISSUE TITLE
Availability dropdown is empty when creating template

### ISSUE THREAD

**Issue by thomassuckow** [jenkinsci/docker-plugin#271]
When you create a template, if you expand the experimental options before saving, the Availability dropdown has no options. Appears to populate after saving and returning to the template.

**Comment by KostyaSha** [comment]
:disappointed:

**Comment by KostyaSha** [comment]
Can't reproduce, what jenkins core version do you have?

**Comment by KostyaSha** [comment]
Reproduced...

**Comment by KostyaSha** [comment]
found why, will fix
