### ISSUE TITLE
Plugin stops working with Docker 1.7.1

### ISSUE THREAD

**Issue by sisao** [jenkinsci/docker-plugin#272]
Hi, 
the plugin in version 10.0 and with Docker 1.7.1 as server Jenkins shows a error message like "client is too old, minimum supported API version is 1.12, please upgrade your client to a newer version"

Any hint what causes this?

I tried to use docker-java 1.4.0 in your plugin, but after fixing some api changes I ended with some ClassNotFound erros like 
"Can't find any implementation of 'com.github.dockerjava.api.command.DockerCmdExecFactory' in the current classpath." in Jenkins and gave up...

**Comment by magnayn** [comment]
No, but I have plenty of 1.7.0 hosts. It seems surprising that a minor
point release would break the API so comprehensively..

**Comment by sisao** [comment]
https://github.com/docker/docker/blob/master/CHANGELOG.md
...
Set limit for minimum client version supported
...
Maybe it can be configured in docker service now...

**Comment by magnayn** [comment]
Hm. That sounds a fairly dumb thing for them to have done in a +0.0.1
release, but i guess it is what it is.

Sounds like you're on the right lines. The exec factory should be set in
ClientBuilderForPlugin.java :

public DockerClient build() {
    return DockerClientBuilder.getInstance(config)
            .withDockerCmdExecFactory(new DockerCmdExecFactoryImpl())
            .build();

}

​It hasn't moved in docker-java, so I'm not sure why it would no longer
find it..​

**Comment by KostyaSha** [comment]
@sisao please provide cloud section from config.xml

**Comment by KostyaSha** [comment]
Current master works fine with 1.7.1 for me

**Comment by sisao** [comment]
thx, I'll try it in the next days...
Can't provide the config.xml... I reverted the changes and plugins on our jenkins...

**Comment by KostyaSha** [comment]
Please wait for 0.10.1, i plan release it soon.
