### ISSUE TITLE
Check NodeProvisioner delay

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#284]
i see delays and some requests related to not spinned or delayed container. I don't see any issue in provisioning implementation.

@thomassuckow i saw your comments in related jenkins issues. Should docker-plugin implement some custom NodeProvisioner?

**Comment by KostyaSha** [comment]
@stephenc is some implementation expected from plugin side in this field of hell?

**Comment by thomassuckow** [comment]
I don't know if anyone has ever extended the NodeProvisioner. If i remember correctly the extension point was added specifically for one off cloud slaves. The default NodeProvisioner is conservative in starting slaves because it believes slaves will process more than one job. Especially when a job has never completed (has no estimated completion time) it seems to be even more conservative.

I haven't noticed severe delays lately, but it could just be the provisioner has decided on my system to provision more. Or possibly someone has tweaked its algorithm.

**Comment by thomassuckow** [comment]
There is also https://issues.jenkins-ci.org/browse/JENKINS-27034 which may manifest as slaves never being started. I haven't seen it in a while, but I am pretty sure the label comparisons are still wrong in Core. I never did figure out how those equals but != labels got created in the first place.

**Comment by stephenc** [comment]
My recommendation, for now, is to have a `QueueDecisionHandler` that schedules a review of the NodeProvisioner for the task's label about 50-100ms after it returns *if* there are no executors available for that task.

The strategy extension point is designed so that it has enough so I can re-implement the cloud api in a less hellish (for implementers) manner... not really designed for general cloud implementations to be driving.

In 1.607+ as the node gets marked as suspended once the job completes, you should get better provisioning due to the stats no longer being poisoned

**Comment by stephenc** [comment]
IOW

```
public boolean shouldSchedule(...) {
  if (no available executors for this job AND we don't have one of these pending) {
    Computer.threadPoolForRemoting.submit(
      sleep(50);
      NodeProvisioner.suggestReviewNow();
    );
  }
  return true;
}
```

**Comment by KostyaSha** [comment]
If this code is not docker related then it should go into separate plugin to exclude duplicates.

**Comment by stephenc** [comment]
Yes I have considered addit it to a separate plugin. There is a side effect for docker cloud specific though. As you know each node from docker-cloud is used once and only once, you can count slightly differently for slaves provided by the docker cloud... may not make much difference when there are zero executors provisioned or pre-1.607 but should improve things for the post 1.607 world.

**Comment by KostyaSha** [comment]
@jglick FYI

**Comment by KostyaSha** [comment]
Damn, delay, time to code it...

**Comment by KostyaSha** [comment]
Weird design... every label has it's own NodeProvisioner, need investigate.... And NeedsMoreExecutor is private interface so i can't instanceof cause of blockage.

**Comment by thomassuckow** [comment]
The way Labels work period is bizarre.

**Comment by KostyaSha** [comment]
@thomassuckow i remember your equals efforts :)

**Comment by KostyaSha** [comment]
@stephenc something like this https://github.com/KostyaSha/nodeprovisioner-kicker-plugin/blob/master/src/main/java/org/jenkinsci/plugins/nodeprovisionerkicker/NodeProvisionerKicker.java ?

**Comment by KostyaSha** [comment]
on 1.565.3 spins 2 slaves if there 2 clouds...

**Comment by stephenc** [comment]
That is the right way... except that your test for no assigned label is not correct... it should not check if there are no nodes rather it should check do something like

```
boolean haveOne = false;
for (Node n: jenkins.getNodes()) {
  if (n.mode != tied && n.getIdleExecutors() > 0 {
    haveOne = true;
    break;
  }
}
kickNodeProvisioner = !haveOne;
```

**Comment by stephenc** [comment]
Also the issue you identify with multiple clouds... I'd forgotten that one (because oc-cloud and nectar-vmware are designed to only have one cloud per instance and instead have multiple configurations within that one cloud)... could you file a JIRA before we both forget it again!

**Comment by KostyaSha** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-30513
But i will better update to 1.609.3 and do my testing on it.

**Comment by KostyaSha** [comment]
https://github.com/KostyaSha/nodeprovisioner-kicker-plugin/blob/master/src/main/java/org/jenkinsci/plugins/nodeprovisionerkicker/NodeProvisionerKicker.java
but afair Computer may not exist so it requires null check.

**Comment by KostyaSha** [comment]
My initial idea was to stick to "NeedsMoreNodes" blockage from hudson.model.Queue.BuildableItem#getCauseOfBlockage but i see no right place (QTD doesn't guarantee order and called to frequently)

**Comment by stephenc** [comment]
Yes that's getting closer

**Comment by KostyaSha** [comment]
@stephenc where is the problem with two spinned nodes? Seems i kicked suggest for label based node, but jenkins decided to satisfy it with null+NORMAL. Should i switch to 1.609.3 line?

**Comment by KostyaSha** [comment]
no ideas...

**Comment by stephenc** [comment]
Let's see if 1.609.3 helps... but I suspect there is still potential for such a race even there

**Comment by KostyaSha** [comment]
@stephenc btw, i can't assign label to job if there is no other slaves excluding master. Should jenkins show this project property always? Either i can't configure job ahead before configuring cloud.

**Comment by KostyaSha** [comment]
@stephenc i found, NodeProvisionerInvoker calls first unlabeled and it wins. Want start plugin from clean initial implementation so force pushed https://github.com/KostyaSha/nodeprovisioner-kicker-plugin/blob/master/src/main/java/org/jenkinsci/plugins/nodeprovisionerkicker/NodeProvisionerKicker.java < this variant works very well on previous case!

Now unclear how i should hack tests and very all this cases... JenkinsRule can run jnlpSlaves, i need Cloud that will run such slaves, recurrence period can be set to huge value and verify then everything according to logs...

**Comment by KostyaSha** [comment]
Added global config to have ability disable it https://github.com/KostyaSha/nodeprovisioner-kicker-plugin/tree/master/src/main/java/org/jenkinsci/plugins/nodeprovisionerkicker probably better rename it to faster-provisionining-plugin to not confuse users?

**Comment by KostyaSha** [comment]
@thomassuckow do you want join testing? Deployed into prod and it works like a charm (though i have no load with many nodes).

**Comment by KostyaSha** [comment]
> @stephenc btw, i can't assign label to job if there is no other slaves except master. Should jenkins show this project property always? Either i can't configure job ahead before configuring cloud.

https://issues.jenkins-ci.org/browse/JENKINS-30553

**Comment by KostyaSha** [comment]
renamed plugin to https://github.com/KostyaSha/faster-node-provision-plugin

**Comment by KostyaSha** [comment]
Though, 1.609.3 delay is only 10 sec that is not very long....

**Comment by KostyaSha** [comment]
First of all minimised ssh retry delay, that caused 10 sec delay. Continue testing provisioner kicker and found that when unlabeled node exists and has NORMAL mode it not tooks slave, so kicking unlabeled when labeled requested isn't right. Probably it should also check that NORMAL node has no specified label as in this case it will win.

**Comment by thomassuckow** [comment]
It "kicks" but then still only allocates 1 slave 10 seconds later. If a second slave is needed it waits another minute and a half.

```
Sep 22, 2015 1:01:05 PM INFO org.jenkinsci.plugins.fasternodeprovision.FasterNodeProvisionRunnable run
Kicking suggest review for label a&&b
Sep 22, 2015 1:01:05 PM INFO org.jenkinsci.plugins.fasternodeprovision.FasterNodeProvisionRunnable run
Kicking suggest review for label a&&b
Sep 22, 2015 1:01:14 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: a&&b
[...]
Sep 22, 2015 1:02:44 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: a&&b
```

**Comment by KostyaSha** [comment]
maybe it's because of periodic stats load calculation?

**Comment by KostyaSha** [comment]
@thomassuckow could you try with single label? (just in case)

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/hudson/model/LoadStatistics.java#L369-L370
Seems kicking provisioning doesn't makes sense while load statistic updates only every minute.

**Comment by thomassuckow** [comment]
I changed it to a single label. I probably won't be able to check it till next week.

**Comment by KostyaSha** [comment]
I fear that something can be caused by Queue lock, i.e. provisioning of some node or retention strategy check. And i don't see any good logging for NodeProvisioners or queue debugging :(

**Comment by thomassuckow** [comment]
I would also beware that I think the null label statistics are wrong. They should only count jobs with no label but I believe that has never been fixed and they count all.

**Comment by KostyaSha** [comment]
Now i not sure that i understand this labels logic... Will try read code again after sleep.

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/docker-plugin/issues/235#issuecomment-147975445
