### ISSUE TITLE
Incorrect containers' credentials being displayed on the config page after an upgrade to 0.10.1

### ISSUE THREAD

**Issue by peterpakos** [jenkinsci/docker-plugin#285]
I have upgraded Docker Plugin 0.10.0 to 0.10.1 and now when I navigate to the config page I can see that the containers' credentials settings are being displayed incorrectly.

It seems that they are set correctly in the config file but for some reason they're set incorrectly on the config page.

If I hit save then the incorrect settings are being saved to the config file.

I've attached a screenshot of the container section of the config page before and after an upgrade.

Docker Plugin 0.10.0:

![screen shot 2015-07-22 at 11 33 39](https://cloud.githubusercontent.com/assets/8777471/8823527/88e09f0c-3065-11e5-9cb5-68ac2c4aeac3.png)

Docker Plugin 0.10.1:

![screen shot 2015-07-22 at 11 25 06](https://cloud.githubusercontent.com/assets/8777471/8823522/80db94c4-3065-11e5-87d7-fa91112e3003.png)

**Comment by KostyaSha** [comment]
Thanks for report, i will check asap.

**Comment by KostyaSha** [comment]
Credentials in docker ssh launcher, right?

**Comment by peterpakos** [comment]
That's right.

Let me know if you need any further info.

**Comment by KostyaSha** [comment]
Please try this hpi https://jenkins.ci.cloudbees.com/job/plugins/job/docker-plugin/433/com.nirima$docker-plugin/

**Comment by peterpakos** [comment]
Trying...

**Comment by peterpakos** [comment]
It works OK now, many thanks for the quick turnaround Kanstantsin!

**Comment by KostyaSha** [comment]
I will release hotfix.
