### ISSUE TITLE
Configure System / Cloud / Template / Credentials incorrect default

### ISSUE THREAD

**Issue by austinnichols101** [jenkinsci/docker-plugin#287]
Running jenkins 1.609.1 docker container and Docker plugin 0.10.1

To reproduce.
1.  I select the 3rd credential entry in the credentials drop-down list and SAVE
2.  Go back to configure system and the 1st credential entry is now highlighted
3.  SAVE

This results in the wrong credentials for the dynamic slave.  Workaround is that I select the desired credential entry each time that I edit something on the Configure System page.  Note that in my case, both the 1st and the 3rd entry are both 'jenkins', but each entry associated with it.

This *might* be related to #255

**Comment by KostyaSha** [comment]
fixed in 0.10.2
