### ISSUE TITLE
Credentials add button submits new credentials but does not show them in list

### ISSUE THREAD

**Issue by rdaviscc** [jenkinsci/docker-plugin#290]
I am having issues selecting credentials when adding a new docker host.  Once i click add I see them being added in my credentials but the drop down list gives me nothing to select.  Tried all types of authentication and they are all added successfully in my credentials area, but none ever show up in the list.  With other plugins, they are showing up.  My production environment has many other plugins to display the ssh credentials to where this plugin can not.  

At this time I do not see any errors in the logs other then the connection to the host won't work because its missing its authentication.

My Dev environment:
Docker plugin 0.10.2
ssh credentials plugin 1.11
Credentials Plug 1.22
Jenkins Version 1.622

Running on Mac Yosemite and Java 1.8

![screen shot 2015-07-28 at 3 09 36 pm](https://cloud.githubusercontent.com/assets/1088433/8940953/d270066a-353a-11e5-8a18-78ff6c2e2717.png)

**Comment by rdaviscc** [comment]
Also tried Safari, Firefox, and Chrome to verify that it is not a browser issue.

**Comment by KostyaSha** [comment]
will try reproduce

**Comment by KostyaSha** [comment]
Docker API works only with certificate connection, add certificate credentials type and it will appear.

**Comment by Fantomatic** [comment]
i tried with fake one, and still doesn't appear. Might need a valide certificate credential ?

**Comment by KostyaSha** [comment]
try enable logging and follow logs, i didn't test it

**Comment by belooussov** [comment]
Also see this unintended behavior. Docker plugin version 0.15.0, jenkins 1.620.
