### ISSUE TITLE
Connect between docker slave to created container as a build step

### ISSUE THREAD

**Issue by matankatz** [jenkinsci/docker-plugin#301]
Hi,

I have the following scenario:
I'm using docker-plugin to provision slave on demand and running my gradle project.
As a pre-build step, I'm using "Start/Stop docker containers" to start the server that the project should test against.
How can i extract from the started container it's IP and exposed port and set it as a system environment so the next build step (the gradle project) can use this information?

Thanks,
Matan

**Comment by KostyaSha** [comment]
nice question, i think atm no way. The second question will be how deal with multiple started/stopped containers. As one of solutions may be dump docker inspect result into ws file.

**Comment by KostyaSha** [comment]
Will docker inspect dump into ws file with specified path/name works for you?
You can then parse it with groovy build step, dump into property file and load property file with env inject.

**Comment by matankatz** [comment]
Hi,
You mean to use it as a workaround in the current plugin?
I would prefer to avoid such workarounds because i have many jobs that are
build in the same way and i don't want to complex them.

Thanks,
Matan

Thanks,
Matan
בתאריך 22 בספט' 2015 11:45,‏ "Kanstantsin Shautsou" <
notifications@github.com> כתב:

**Comment by ndeloof** [comment]
This use cas is better addressed by docker-slaves-plugin, until some container composition is introduce in docker-plugin
