### ISSUE TITLE
Enhanced docker once retention policy

### ISSUE THREAD

**Issue by philpep** [jenkinsci/docker-plugin#312]
Hi, I like the "docker once retention policy" that allow a build to be started on a clean environnent. However the slave provisioning (run docker, sshd, slave) is too slow, I think there is also a lot of sleep/wait in the code...

I would like to have a new retention policy that provision many (based on "Instance capacity") docker slaves just waiting for a job. When a job is started one of the pre-provisioned docker slave take it immediately and is destroyed at the end of the build.

In pseudo code the loop looks like:

````
while instance_count < instance_capacity {
  provision()
}
````

Do you think this could be possible ? Thanks !

**Comment by KostyaSha** [comment]
This doesn't make any sense, you can have many different containers and you can't guess what will be required while it will ate total capacity.
Main delays are in:
- jenkins calls Provisioning after delay - #284 
- pulling - check what pulling strategy do you use and not use latest or don't fetch it always
- container startup + ssh. It works as designed, requires start ssh and connect. - probably here may help JNLP launcher that i plan release soon or other progressive delay algorithm.

**Comment by philpep** [comment]
Ok setting pulling to "Never" helps.

Provisioning take 20 seconds here:

- 10 seconds lost in a sleep after first connect faillure in bySshWithEveryRetryWaitFor().
- 10 seconds for slave provisioning (I guess copying a jar and launch it)

````
Aug 31, 2015 5:56:28 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: jessie
Aug 31, 2015 5:56:28 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'philpep/jenkins-slave:jessie', for label: 'jessie', in cloud: 'localhost'
Aug 31, 2015 5:56:28 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'philpep/jenkins-slave:jessie' number '0' on 'localhost'; Total containers: '1'
Aug 31, 2015 5:56:28 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of philpep/jenkins-slave:jessie from localhost with 1 executors. Remaining excess workload: 0
Aug 31, 2015 5:56:28 PM com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
INFO: Trying to run container for philpep/jenkins-slave:jessie
Aug 31, 2015 5:56:29 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
SEVERE: Failed to connect to 127.0.0.1:32804 (try 1/10) - There was a problem while connecting to 127.0.0.1:32804
Aug 31, 2015 5:56:39 PM com.nirima.jenkins.plugins.docker.utils.PortUtils bySshWithEveryRetryWaitFor
INFO: SSH port is open on 127.0.0.1:32804
Aug 31, 2015 5:56:39 PM com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for 127.0.0.1:32804
Aug 31, 2015 5:56:48 PM hudson.slaves.NodeProvisioner$2 run
INFO: Image of philpep/jenkins-slave:jessie provisioning successfully completed. We have now 2 computer(s)
[08/31/15 17:56:50] SSH Launch of localhost-3dc18bcb2fa8 on 127.0.0.1 completed in 1,800 ms
````

Any idea how to improve this ? Thanks.

**Comment by KostyaSha** [comment]
For my purposes i'm doing cached images (built some zero job and commit it to container) for builds. Maybe it may help you exclude some fetches...
