### ISSUE TITLE
Feature request: Private repositories and force option for tag

### ISSUE THREAD

**Issue by jphelion** [jenkinsci/docker-plugin#314]
Ability to use private repositories for pushing the images created by the plugin. 

Ability to use force option with the additional tags as in using 
`docker tag --force`

**Comment by KostyaSha** [comment]
Adding more options for all existed commands is in TODO, but requires some redesign of code.

Could you clarify about private registry? I'm successfully pushing images to private registry.

**Comment by jphelion** [comment]
Oh sorry I meant registry. What we would want to do is to push images created by jobs to a private registry server that could be configured per job.

**Comment by KostyaSha** [comment]
docker is pushing to the registry according to image name.

**Comment by spoon99** [comment]
+1 for this feature.
I got com.github.dockerjava.api.ConflictException: Conflict: Tag latest is already set to image 07cd237e07a3b83ee195752827dd85eda258f0e2fe0b75e1bc51504e631d55aa, if you want to replace it, please use -f option. execption on build.

**Comment by ndeloof** [comment]
if your goal is to build and publish container you better should use https://wiki.jenkins.io/display/JENKINS/CloudBees+Docker+Build+and+Publish+plugin
