### ISSUE TITLE
Docker 1.7.1 support

### ISSUE THREAD

**Issue by Jotschi** [jenkinsci/docker-plugin#316]
It seems that docker-plugin 0.13.0 is not compatible with docker 1.7.1 hosts.

I get the following error when i try to test the connection to a docker 1.7.1 host:

**client is too old, minimum supported API version is 1.12, please upgrade your client to a newer version**

Docker Host:
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

**Comment by BcTpe4HbIu** [comment]
Try setting *Docker Version* parameter in settings to 1.18

**Comment by Jotschi** [comment]
Thanks, thats working.

**Comment by KostyaSha** [comment]
Do not set version at all if you don't know what it do

**Comment by Jotschi** [comment]
It's clear what it does. The helptext states that this setting will overwrite the used API version for all REST Url. I would rename "Docker Version" to "Docker API Version".

**Comment by nguyenhugh** [comment]
please do tell how do you set the Docker Version parameter to 1.18?
