### ISSUE TITLE
Launching container via Jenkins label does not work

### ISSUE THREAD

**Issue by IntelBob** [jenkinsci/docker-plugin#321]
Jenkins: V1.612
Docker plugin: V0.13.0

In the Jenkins configuration page, I added the label `docker-slaves-farm` to the docker configuration, in the job, I specified that as the value for `Restrict where this project can be run`. Jenkins system logs shows...

    Sep 16, 2015 3:28:37 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
    Asked to provision 1 slave(s) for: docker-slaves-farm
    Sep 16, 2015 3:28:37 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
    Will provision 'evarga/jenkins-slave', for label: 'docker-slaves-farm', in cloud: 'docker'
    Sep 16, 2015 3:28:37 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
    Not Provisioning 'evarga/jenkins-slave'; Server 'docker' full with '0' container(s)

Docker is configured for 12 containers and there are 0 running at the time of the test

    $ docker info
    Containers: 12
    Images: 22
    Storage Driver: aufs
    Root Dir: /var/lib/docker/aufs
    Backing Filesystem: extfs
    Dirs: 46
    Dirperm1 Supported: false
    Execution Driver: native-0.2
    Logging Driver: json-file
    Kernel Version: 3.13.0-52-generic
    Operating System: Ubuntu 14.04.2 LTS
     CPUs: 2
    Total Memory: 990.7 MiB
    Name: luvguptx-ivm
    ID: OM23:6472:A4WD:LIJW:CCL3:AD7G:44LF:FKGV:I2AN:4UKU:VUIA:EZVI
    Http Proxy: http://...
    Https Proxy: https://...
    WARNING: No swap limit support

    $ docker version
	Client:
	 Version:      1.8.2
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   0a8c2e3
	 Built:        Thu Sep 10 19:19:00 UTC 2015
	 OS/Arch:      linux/amd64

	Server:
	 Version:      1.8.2
	 API version:  1.20
	 Go version:   go1.4.2
	 Git commit:   0a8c2e3
	 Built:        Thu Sep 10 19:19:00 UTC 2015
	 OS/Arch:      linux/amd64

**Comment by KostyaSha** [comment]
> Not Provisioning 'evarga/jenkins-slave'; Server 'docker' full with '0' container(s)

Hi, 0 means no containers. Please set explicitly some reasonable limit of containers.

**Comment by KostyaSha** [comment]
Please provide cloud section from config.xml https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md

**Comment by IntelBob** [comment]
My bad, only saw the "instance capacity" field and somehow missed the "container cap" field. Thanks for your help.

**Comment by KostyaSha** [comment]
Maybe related to #318 sorry for not updating docs well

**Comment by IntelBob** [comment]
Yeah it's related but not your fault and I want to thank you for all your hard work. Just a thought, for the unsuspecting newbie user, it might be better to default cap container value to 1 so they don't mistakenly think something is broken when it isn't.

**Comment by KostyaSha** [comment]
Default should be 100, but i didn't check whether total and container capacity has the same behaviour.

**Comment by IntelBob** [comment]
100 is fine too, by total capacity do you mean instance capacity?

**Comment by KostyaSha** [comment]
Yes

**Comment by IntelBob** [comment]
Then yes, it would be good to check that container cap value is >= total instance capacity for all docker images if that's what you meant or perhaps auto adjust the container capacity based on the sum of total instance capacity, just a thought.
