### ISSUE TITLE
help file is missing for "environments" template field

### ISSUE THREAD

**Issue by prelegalwonder** [jenkinsci/docker-plugin#322]
What format should I use for Environment overrides?

Per the https://docs.docker.com/reference/builder/#env I tried:
```
http_proxy='myproxy' https_proxy='myproxy'
http_proxy 'myproxy' https_proxy 'myproxy'
```
Despite this, it never seems to set / override the base image ENV http_proxy var. Am I using the correct format?

**Comment by KostyaSha** [comment]
Sorry, can't get context, could you show some screenshot of place where you trying to use variables?

**Comment by prelegalwonder** [comment]
Sorry, I'm trying to overwrite environment variables specified in the image using the "Environment" field under Container Settings in the Docker Template in the Cloud section of the Main Configuration area of Jenkins. 

When I run the build an dump "env" I don't see it specified in the container at all.

![2015-09-17_0946](https://cloud.githubusercontent.com/assets/734328/9936397/6232cc52-5d21-11e5-9247-abdd5ad5b47d.png)

**Comment by KostyaSha** [comment]
What docker-plugin version do you use?

**Comment by prelegalwonder** [comment]
@KostyaSha currently at com.nirima:docker-plugin:0.13.0

**Comment by KostyaSha** [comment]
Should be new line separated, but i don't see expandable text box. I will check.

**Comment by KostyaSha** [comment]
Seems i broke logic, it accepts space separated value, but returns new line separated back to UI. 
Variant in your screenshot should work.

**Comment by KostyaSha** [comment]
Found, appeared after difficult launchers fixing work :)

**Comment by KostyaSha** [comment]
@prelegalwonder please try this hpi https://jenkins.ci.cloudbees.com/job/plugins/job/docker-plugin/516/com.nirima$docker-plugin/ and reply with results

**Comment by prelegalwonder** [comment]
@KostyaSha awesome, ty :) The UI is much more intuitive. 
However, I still don't see the ENV variables I define get exposed to the running container. If I do env as a build step in the container, I don't see http_proxy or https_proxy. Is how I've specified the variables below correct?

![docker-plugin-rev1](https://cloud.githubusercontent.com/assets/734328/9945650/21481386-5d54-11e5-895a-43f4dd019dfe.png)

**Comment by KostyaSha** [comment]
looks correct, i will try but later. Really want cover all this damn bugs with integration tests.

**Comment by prelegalwonder** [comment]
@KostyaSha sounds good, thank you for all your efforts! It's a great plugin :100:

**Comment by KostyaSha** [comment]
Verified, env vars attached to the container, but ssh is stripping them https://docs.docker.com/examples/running_ssh_service/#environment-variables

**Comment by KostyaSha** [comment]
I opened separate issue and will close this as first step was to fix UI and data binding.

**Comment by radinsky** [comment]
Does is work for you? I still see no vars I configured inside the docker container :\
