### ISSUE TITLE
preserve env vars for ssh launcher

### ISSUE THREAD

**Issue by KostyaSha** [jenkinsci/docker-plugin#327]
https://docs.docker.com/examples/running_ssh_service/#environment-variables

splitting from #322

**Comment by clausfod** [comment]
I've tried the way described here: https://docs.docker.com/examples/running_ssh_service/#environment-variables

But it still doesn't preserve env vars for the ssh launcher. Until this is fixed one have to stick with the CloudBees Docker Custom Build Environment Plugin.

Kind regards
Claus

**Comment by ndeloof** [comment]
AFAIK there's no way to fix this from sshd. Using NodeProperties/EnvironmentContributors could be a workaround.

**Comment by ndeloof** [comment]
Added support for EnvironmentNodeProperties in 6ab06da819b856fbfe8cbc5d3bd66154ff002d68
not sure we should try to fix this, this is how sshd is expected to run. Too much black magic could have some unexpected side effects
