### ISSUE TITLE
Option to limit container launch attempts upon failure

### ISSUE THREAD

**Issue by IntelBob** [jenkinsci/docker-plugin#334]
If Jenkins fails to launch a container say due to a SSH error, it'll keep retrying until it exhausts the container cap value. It'll only stop when the job is canceled. This is a problem if there are multiple jobs using the same Docker cloud and may not be able to launch containers. It'll be great if there is docker plugin option to limit number of attempts to launch a container if Jenkins fails to launch it on first try.

**Comment by KostyaSha** [comment]
Per template? How will it be possible unblock then?
Could you provide jenkins log? 
Failed containers will die after 2 minutes of TTL afair.

**Comment by IntelBob** [comment]
Yes, I would say have a config option per docker template. Not sure what you mean by unblock? If Jenkins fails to launch a container, Jenkins job should report it as failed build. Yes, I see that failed container will die after 2 minutes but then another one will be requested so all the docker containers are always maxed out. 

Here's a bit of the log, don't think it's useful because it just repeats
    Sep 29, 2015 1:42:36 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
    Will provision 'ubuntu12.04-ssh', for label: 'docker-bob-farm', in cloud: 'docker-bob'
    Sep 29, 2015 1:42:36 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
    Not Provisioning 'ubuntu12.04-ssh'; Server 'docker-bob' full with '5' container(s)
    Sep 29, 2015 1:42:46 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
    Asked to provision 1 slave(s) for: docker-bob-farm
    Sep 29, 2015 1:42:46 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
    Will provision 'ubuntu12.04-ssh', for label: 'docker-bob-farm', in cloud: 'docker-bob'
    Sep 29, 2015 1:42:46 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
    Not Provisioning 'ubuntu12.04-ssh'; Server 'docker-bob' full with '5' container(s)

**Comment by KostyaSha** [comment]
Bad infra and absent container shouldn't fail build. This is fundamentally wrong. 
About infinite spin-up i thought about ways to block new provisioning, i can collect and report provisioning failures in some place, but then it will be under question how "unblock" such provisioning. Because issues can be caused by some network issues i.e. 30 mins of outage.

This sounds like we need strategy for such action, but i don't see the full picture and behaviours of such strategies.

**Comment by KostyaSha** [comment]
I.e. Enter fail state: "disable template after N provisioning failures", 
and recovery "retry provisioning every 2 minutes" on success remove fail mode.

**Comment by KostyaSha** [comment]
@IntelBob what is the root issue of spin-up failure?

**Comment by IntelBob** [comment]
The cause is invalid creds, I mistyped the password, granted that it shouldn't happen once it's set correctly but in an corporate environment when passwords do get changed occasionally but not updated in a timely manner in Jenkins, this would cause the infinite launching of containers. Your suggestions sounds good to me.

**Comment by robtec** [comment]
+1

**Comment by eoghanino** [comment]
+1

**Comment by ndeloof** [comment]
Maybe docker-plugin could rely on [one-shot-executor](https://wiki.jenkins.io/display/JENKINS/One-Shot+Executor)

**Comment by pjdarton** [comment]
I added code (years ago now) that'll make the plugin stop using a template if there's a problem with that template.
It might not 100% detect a failure in all circumstances, but it works for me.
