### ISSUE TITLE
Error using local images and docker.io

### ISSUE THREAD

**Issue by FrEaKmAn** [jenkinsci/docker-plugin#335]
Hi

I have created a simple Dockerfile and built the image as 

    docker build -t billingapp .

when I run docker images, this image is present. When I run the Run container task, I get an error

    Pulling image billingapp
    null:Pulling repository docker.io/library/billingappERROR: Build step failed with exception
    com.github.dockerjava.api.DockerClientException: Could not pull image: Error: image library/billingapp: not found

Must I upload my newly created image to docker.io to be able to use it here? Or am I missing some configuration?

**Comment by KostyaSha** [comment]
I think it a generic docker question. I'm busy atm, please try read excellent docker docs about using custom images. Any image without host usually mapped on library -> that is remote hub registry.
Try name your image like localhost:5000/build or just enter hash of this container.

**Comment by FrEaKmAn** [comment]
Hi @KostyaSha 

Thank you for the quick reply. If I enter localhost:5000/build, then I get an error during pulling the image from localhost:5000 URL which of course ends in failure. Using only hash of the container causes same problem - tries to load it from docker.io.

**Comment by KostyaSha** [comment]
Try set NEVER_PULL in template pulling mode and ensure that plain
`docker run --rm -it imagename echo "hello"`

**Comment by magnayn** [comment]
Either docker.io or you need to run your own docker registry server.

You'd then tag it myrepo:5000/billingapp and push.

**Comment by KostyaSha** [comment]
@magnayn trick with specified hash will work, if image will have full name (even for not existed registry) docker will also it find. 

Problem is docker damn logic of invisible binding to `library`

**Comment by FrEaKmAn** [comment]
I tried with full name but no success. Can you please give an example?

**Comment by KostyaSha** [comment]
@FrEaKmAn 
> ensure that plain  docker run --rm -it imagename echo "hello" works on this docker host
