### ISSUE TITLE
Slave pool

### ISSUE THREAD

**Issue by MichaelBitard** [jenkinsci/docker-plugin#336]
One feature we really want is the capacity to have a pool of jenkins-docker slaves always ready.

And each time a job is run on a slave, the slave is destroyed and a new one is created.

With this feature, we could really speed up our job run time, because : 
- The creation of a new slave can take up to 20 seconds (which will not be on the critical path if there are always N slaves waiting for a job)
- We don't want to use a slave more than once, to ensure there is no side effects between our jobs

If you think this is a good idea, I can take a look into it and submit one or two pull request.

**Comment by lanwen** [comment]
Good point. Think it will be useful.
(Then it can be ported to openstack-plugin)

**Comment by KostyaSha** [comment]
Duplicates #312

**Comment by KostyaSha** [comment]
In general it should be possible, but it requires review design.

**Comment by CGavrila** [comment]
Is 20 seconds the expected wait time for a new Docker instance to be created? At the moment, I am seeing times of roughly 2 minutes at times. Is there anything that may contribute to this long wait?

**Comment by KostyaSha** [comment]
https://github.com/jenkinsci/docker-plugin/issues/284

**Comment by KostyaSha** [comment]
> Is 20 seconds the expected wait time for a new Docker instance to be created? At the moment, I am seeing times of roughly 2 minutes at times. Is there anything that may contribute to this long wait?

Thats jenkins design issue, atm i see no Extension for cutting out LoadStatistics checker that used as base for doing provisioning cycles. Feel free to contact @stephenc as he started ignoring my questions about Cloud improvements in jenkins. I also tried experiment with https://github.com/jenkinsci/docker-plugin/issues/284 but it doesn't work for all cases right (though it doesn't break production and probably makes provisioning faster for some cases).

**Comment by stephenc** [comment]
The load statistics have a set of parameters that control how soon it kicks in. [here](https://cloudbees.zendesk.com/hc/en-us/articles/204690520-Why-do-slaves-show-as-suspended-while-jobs-wait-in-the-queue-) is some documentation I have written on the subject.

Basically you probably want to change the decay to a faster value.

(@KostyaSha I am just currently rather busy with our November releases, not ignoring you)

**Comment by KostyaSha** [comment]
@stephenc can i expose decay into global config? I thought to change it in production, but didn't test yet.

**Comment by KostyaSha** [comment]
Probably https://github.com/KostyaSha/faster-node-provision-plugin + decay will work and then we will have bottleneck only in Queue locks.

**Comment by CGavrila** [comment]
Thank you for your suggestions, I'll take a look.

**Comment by ndeloof** [comment]
Implemented in 0.17 by reducing the "think time" when a job enter the queue and Docker Cloud has to provision a fresh new agent.
