### ISSUE TITLE
Binding slaves to a job

### ISSUE THREAD

**Issue by kummerer94** [jenkinsci/docker-plugin#338]
Hey everyone,

I like this plugin very much, it takes away so much work and the newest versions provision and tear down slaves very smoothly.

I want to add a use-case to this issue. However, I don't know whether this is actually possible using the Jenkins API:

If I want to make the workspace of a job in Jenkins available to the slaves, I have to mount the whole workspace of all jobs into the container.

We want to have a similar functionality like the CloudBees Docker Custom Build Environment provides. But, since the plugin poorly handles the startup of the job (not everything is run inside of the container), we can't and won't use it. (Also, you can't configure every option like --add-host, etc.) We need to start a slave for a specifiy job and after that job is finished the slave is torn down.

Thus, the slave's lifecycle is bound to the job's. The goal of this is to be able to use the Jenkins Job environment (at least the core variables, like JOB_NAME) during startup. This would allow us to only mount job specific directories and solve the issue of mounting the whole workspace.

Instead of adding a lot of slave configurations (which can only be done in the Jenkins global configuration) it would be easy to make some of this configuration generic using these build variables. For example, you could pull a specific tag of an image based on the job that's running. Of course, you wouldn't have to mount all job directories into the container.

As a first step, it would be great to know whether this is actually possible. Can you access the build environment (or at least the job name?) before the slave is actually provisioned?

Hope to hear your feedback,
Alex

Note: This issues originated in #325.

**Comment by KostyaSha** [comment]
I will read this long description later, but maybe the next solution will do what you want. In latest release i added variables into build job. If you have docker client in docker image where slave runs you can automatically use it and run side container with using --volumes-from=$DOCKER_CONTAINER_ID
See https://github.com/jenkinsci/docker-plugin/blob/master/CHANGELOG.md#0150

In shell script you can your custom flow
```
docker run \
 --rm \
 -i \
 --volumes-from="${DOCKER_CONTAINER_ID}" \
 -w "${WORKSPACE}" \
 additionalimage:test \
 bash -lc "command"
```

In the same way you can do builds.

**Comment by KostyaSha** [comment]
@kummerer94 i read your message, seems what i provided will work for you. 

I didn't get idea about `Can you access the build environment (or at least the job name?) before the slave is actually provisioned?`
Before slave provisioned there is no build at all, only special object Item in Queue that transforms into build and has workspace only after it get into slave executor.

**Comment by kummerer94** [comment]
It would be enough to know the Job Name of the Build who made us provision the slave.

So, in more detail:
When building a job, it gets queued and normally a slave gets provisioned for this build (in my case, there will always be one slave per build that gets deleted after the build is finished). I would like to know the job for which we are creating the new slave but before the slave is actually initialized with the job workspace.

**Comment by ndeloof** [comment]
What you're looking for is the initial reason I created [docker-slaves-plugin](https://wiki.jenkins.io/display/JENKINS/Docker+Slaves+Plugin)

I wish I will be able to backport some of the ideas demonstrated there into docker-plugin.

Could you describe in more details what you're trying to do here ? A job doesn't have a workspace, only a Build has one, on the agent it is running on. We could rely on docker volumes to offer _some_ persistence between builds if this is what you're looking for.

**Comment by pjdarton** [comment]
No response from author; closing.
