### ISSUE TITLE
Docker Swarm

### ISSUE THREAD

**Issue by kmadel** [jenkinsci/docker-plugin#346]
I have read through issue #299 but it is not clear if a Docker Swarm host is supported or not. 

I am using version 0.15 of this plugin on Jenkins 1.609.3.1. My Docker Swarm Master is using the 1.8.2 client.

I set up a Workflow job with a parallel step that kicks off 5 parallel branches against the same Docker cloud template using the specified label. All 5 nodes are kicked off on the swarm-master (even when the agent is not running), so it is as if it is being treated as a normal Docker host and not a Swarm manager. 

Just curious if anyone has successfully tested Docker Swarm with multiple agents?

On a side note, the parallel branches 2-5 don't get Docker cloud slaves provisioned until after the 1st branch is complete - once the first branch completes (all same label), the the other 4 branches get slaves provisioned in parallel as expected.

**Comment by prelegalwonder** [comment]
@kmadel  I've been successfully building against 3 swarm agents that report to a different master. The images never get kicked off on the master. 

What are you using for the discovery? The cloud hosted service or did you set one up based on redis / zookeeper / consul?

**Comment by Suirtimed** [comment]
I just confirmed with my environment that having two "cloud" (in this case Docker host) nodes with the same "Labels" will not both participate in building jobs.  The limit set by the first Docker Template that matches the label in the job will stop future jobs from being passed to the next cloud.  I was wondering if anyone had a "strong" opinion about a "best practice" in this area, or some comments in the plugin configuration help data to let other users know about this.  Tomorrow I'll likely look at setting up a docker swarm and seeing how Jenkins behaves in this case.

**Comment by ndeloof** [comment]
Don't use multiple clouds in jenkins to access a set of docker nodes, better run docker-swarm standalone to group them under a single API endpoint to configure in jenkins.
Support for docker 1.12+ swarm mode is planned for a future release.

**Comment by Roemer** [comment]
Any news on the swarm mode? Will it be integrated into this plugin or will it just be kept in the separate `Docker Swarm Plugin`?

**Comment by pjdarton** [comment]
Where I work, we use the docker-plugin with swarms.  The swarm endpoint acts like a load balancer and it "just works".  I'm not 100% sure of the exact configuration used (I don't admin those swarms) but my guess is that it's done as was [stated above](https://github.com/jenkinsci/docker-plugin/issues/346#issuecomment-335376077).

Also, in general, if there's functionality that's provided in one plugin then duplicating that in another plugin isn't a good idea, so if that `Docker Swarm Plugin` you mentioned does what's needed then this plugin definitely should _not_ duplicate that.

**Comment by Roemer** [comment]
This plugin (`Docker`) uses the obsolete swarm standalone. The other plugin (`Docker Swarm Plugin`) uses the newer swarm mode. But most things are or should be exactly the same. My issue I currently have is that this plugin supports jenkins credentials for a custom Docker registry, whereas the other plugin does not yet support that. In my opinion (as that much is shared), it would be better to unify those plugins into one.

**Comment by pjdarton** [comment]
Well, this isn't something I need myself, and I get the impression that Nick's less involved with this plugin than he used to be ... but if you did the work and created a PR (or found someone who would), I'd help review your changes and get them incorporated into the plugin.

**Comment by Roemer** [comment]
I created an issue in the other plugin (https://github.com/jenkinsci/docker-swarm-plugin/issues/30) to discuss this.
