### ISSUE TITLE
docker client connect timeout is too short

### ISSUE THREAD

**Issue by hindessm** [jenkinsci/docker-plugin#347]
While trying to track down a problem with a docker slave, I noticed that the connection timeout for the docker client seems to be using the connection timeout in seconds as a value in milliseconds without multiplying by 1000. I increased the timeout and the problem I was having went away.

After I mentioned this to a colleague, he pointed out that the DockerCmdExecConfig getConnectTimeoutMillis method actually returns the readTimeout so that should probably be fixed too or the timeout will still be incorrect.

Regards,
 Mark

**Comment by KostyaSha** [comment]
@hindessm one of the values wasn't used at all. I fixed it some time ago, but it may happen that something is still wrong.

**Comment by beanz** [comment]
Thanks!

**Comment by hindessm** [comment]
Thanks!
