### ISSUE TITLE
Trouble with volume permissions when container kicked off by plugin

### ISSUE THREAD

**Issue by prelegalwonder** [jenkinsci/docker-plugin#353]
Plugin: 0.15.0
Jenkins: 1.609.3
Docker: 1.8.3
Swarm: 0.4.0

Scenario: Image has a volume /Output that is off of root path. It's owned by a build user. When the docker-plugin deploys the image, that volume is owned by root. If I manually spin up the same container, I see it's owned by the user I had setup. 

I don't know that this is definitely an issue with the plugin but I've experienced it exclusively when using the plugin and never when not using the plugin. 

I've even setup an entrypoint script to chown that path and then startup sshd -D but it still gets written back to be owned by root somehow. 

I've checked Docker commands and various other settings and I can't find anything that would trigger this behavior so I wanted to see if anyone had any ideas or experienced the same?

**Comment by zuBux** [comment]
I am having the same issue here. 
When I add a Volume mount point through the docker-plugin options it is owned by root. This practically makes it useless because provisioning is performed by user 'jenkins' (or any other user you set up). When I run the container manually using the VOLUME command in Dockerfile, everything works as it should.

I use the exact same software versions.

**Comment by magnayn** [comment]
We don't do anything particular in the plugin, just call the docker API.

Best I can suggest is to use something like tcpdump and capture what the
difference between what URL&payloads the communication from the plugin
looks like compared to the command line.

When you say "owned by", is this not a confusion around the UID that the
volume container has written against? It'll need to be the same as whatever
your jenkins user is (if you're using ssh -D).

**Comment by zuBux** [comment]
OK I think I get what's happening now. You 're probably right.

I create a user 'jenkins' with UID 1000. I use the Volume option of the docker-plugin to create a mountpoint e.x

/var/lib/jenkins/jobs/testjob/output:/home/jenkins/output:rw

When I ssh to the machine the owner of this folder is : 
drwxr-xr-x 2     109     114 4096 Dec  4 16:49 output

which is the uid:gid of the jenkins user on the host machine. That means that the volume is not usable by container user 'jenkins'.

Do you have any suggestions for a portable way to solve this?

Thanks!

**Comment by KostyaSha** [comment]
Thats a generic docker issue. As hook allow sudo for jenkins user and chown

**Comment by zuBux** [comment]
Thanks!

**Comment by KostyaSha** [comment]
For example openvz attaches normal drives, while docker uses namespaces (that absent). Probably google around such topics https://github.com/docker/docker/issues/7198

**Comment by zuBux** [comment]
Yeah, I encountered this limitation for the first time. Until now I never used SSH & SSH users to access containers along with volume mounts. Thanks for the info.

**Comment by ndeloof** [comment]
What you do here is a **bind mount**. Volumes are managed by docker and follow permissions set from the image before the `VOLUME` command.
Don't use bind mounts. Never. They'll hurt you.
