### ISSUE TITLE
Setting DOCKER_HOST on the container breaks docker-in-docker script

### ISSUE THREAD

**Issue by fraz3alpha** [jenkinsci/docker-plugin#355]
This is potentially more of a gotcha/FYI, rather than an actual bug, but when a container is started through the plugin it now sets the DOCKER_HOST variable (see the Changelog for 0.15.0) - this then doesn't play nice with attempting to run the docker-in-docker script (https://github.com/jpetazzo/dind) as an error is thrown when trying to run docker:

Docker started
break
'[' 1 -eq 10 ']'
echo 'started, running containers:'
started, running containers:
docker ps
2015/11/18 13:58:11 Invalid bind address format: dockerslave01:4243/

This is now picking up the value of DOCKER_HOST that was set via this plugin, rather than connecting to the local docker as it would ordinarily.

The solution is as simple as unsetting the DOCKER_HOST variable at the start of my job, but I thought I'd bring it up in case others are hitting the same kind of issue

**Comment by KostyaSha** [comment]
Right behaviour that allows using and making out-of-the box shell flows with docker. 
Unsetting variable in any custom script is the right solution if your script can't work with provided system variable.

**Comment by cjthorne** [comment]
Thanks for this warning! I've just come across the same problem since upgrading the plugin. We use docker in docker alot.
