### ISSUE TITLE
Fails to install in docker jenkins:1.625.2

### ISSUE THREAD

**Issue by vermut** [jenkinsci/docker-plugin#358]
Docker image ID: ee572ce7ce25670e15bc052eca63195ed02fe6aea1f206121f8be0fe754632ea
Everything default to docker image:
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)

Steps:
1. Deploy new Jenkins in Docker
2. Install docker-custom-build-environment 1.6.4 via web gui (search, click, Download now and install after restart)
3. Receive error https://gist.github.com/vermut/ac561e2f610993da7b36

**Comment by KostyaSha** [comment]
`docker-custom-build-environment` is other plugin

**Comment by vermut** [comment]
Indeed.
