### ISSUE TITLE
Build stuck on pending-waiting for next available executor

### ISSUE THREAD

**Issue by markmaun** [jenkinsci/docker-plugin#361]
When attempting a build I'm seeing a "pending-waiting for next available executor" and the build won't run.   I've confirmed the build job uses the "test" label and the label is valid as a "cloud".

Here is the system log:

`Asked to provision 1 slave(s) for: test
Dec 15, 2015 3:57:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'evarga/jenkins-slave', for label: 'test', in cloud: 'docker'
Dec 15, 2015 3:57:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning 'evarga/jenkins-slave' number '1' on 'docker'; Total containers: '1'
Dec 15, 2015 3:57:57 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of evarga/jenkins-slave from docker with 1 executors. Remaining excess workload: 0
Dec 15, 2015 3:57:57 PM INFO com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
Trying to run container for evarga/jenkins-slave`

Jenkins version and plugins:

Jenkins 1.626
Plugins and Versions:

Ant Plugin1.2  
Authentication Tokens API Plugin1.2 
CloudBees Docker Build and Publish plugin1.1  
Config File Provider Plugin2.9.3  
Configuration Slicing plugin1.44  
Credentials Plugin1.24  
CVS Plug-in2.12  
Docker Commons Plugin1.2  
Docker plugin0.16.0  
Durable Task Plugin1.6  
External Monitor Job Type Plugin1.4  
GIT client plugin1.19.0  
GIT plugin2.4.0  
Gradle plugin1.24  
Javadoc Plugin1.3  
JUnit Plugin1.9 
LDAP Plugin1.11  
Mailer Plugin1.16  
MapDB API Plugin1.0.6.0  
Matrix Authorization Strategy Plugin1.2  
Matrix Project Plugin1.6  
Maven Integration plugin2.12.1  
Maven Release Plug-in Plug-in0.14.0  
OWASP Markup Formatter Plugin1.3  
PAM Authentication plugin1.2  
Publish Over SSH1.13  
SCM API Plugin1.0  
Script Security Plugin1.15  
SSH Credentials Plugin1.11  
SSH Slaves plugin1.10  
Subversion Plug-in2.5.4  
Token Macro Plugin1.11  
Translation Assistance plugin1.12  
Windows Slaves Plugin1.1  
Workspace Cleanup Plugin0.28

My config.xml

``` xml
 <clouds>
    <com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.16.0">
      <name>docker</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate>
          <configVersion>2</configVersion>
          <labelString>test</labelString>
          <launcher class="com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.10">
              <port>22</port>
              <credentialsId>************************************</credentialsId>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <maxNumRetries>0</maxNumRetries>
              <retryWaitTime>0</retryWaitTime>
            </sshConnector>
          </launcher>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/home/jenkins</remoteFs>
          <instanceCap>100</instanceCap>
          <mode>EXCLUSIVE</mode>
          <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>10</idleMinutes>
            <idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerTemplateBase>
            <image>evarga/jenkins-slave</image>
            <dockerCommand></dockerCommand>
            <lxcConfString></lxcConfString>
            <hostname></hostname>
            <dnsHosts/>
            <volumes/>
            <volumesFrom2/>
            <environment/>
            <bindPorts></bindPorts>
            <bindAllPorts>false</bindAllPorts>
            <privileged>false</privileged>
            <tty>false</tty>
            <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
              <c class="list"/>
              <list reference="../c"/>
            </extraHosts>
          </dockerTemplateBase>
          <removeVolumes>false</removeVolumes>
          <pullStrategy>PULL_LATEST</pullStrategy>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>http://**.**.***.*:4243</serverUrl>
      <connectTimeout>5</connectTimeout>
      <readTimeout>15</readTimeout>
      <credentialsId></credentialsId>
      <containerCap>100</containerCap>
    </com.nirima.jenkins.plugins.docker.DockerCloud>
  </clouds>
```

When I goto configure a build label it recognizes the "test" cloud as a valid option.   When I test a connection to the docker slave host it succeeds.

I'm able to start/stop/destroy docker containers using jenkins on the slave host, I just can't run a build within those containers.

Docker version on slave:  Docker version 1.9.1, build a34a1d5

**Comment by Thomas-Clark** [comment]
Check your jenkins.log file. I had this problem as well and found I was getting a NullPointerException from com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getAddressForSSHD. Jenkins just kept spinning up new slaves endlessly.

**Comment by nashdiesel** [comment]
Thanks for the reply.   I'm not seeing that message in the jenkins logs, I'm just seeing that it's "trying to run container" for the image I'm using and it's just hanging there.

From previous attempts I can indeed create containers with jenkins but in a simple build tied to that cloud label it doesn't see the "slave".  I  have this issue whether or not a docker container is running on the slave itself

`Creating slave SSH launcher for /**.**.***.*:32770
Dec 15, 2015 12:28:37 AM INFO hudson.slaves.NodeProvisioner$2 run
Image of evarga/jenkins-slave provisioning successfully completed. We have now 2 computer(s)
Dec 15, 2015 12:39:12 AM INFO com.nirima.jenkins.plugins.docker.DockerSlave _terminate
Disconnected computer
Dec 15, 2015 12:39:12 AM INFO com.nirima.jenkins.plugins.docker.DockerSlave _terminate
Stopped container 2853f3aae0067063f26f70c3521d4e595047ceb1c1144a4522e0f3c99a80aa12
Dec 15, 2015 12:39:12 AM INFO com.nirima.jenkins.plugins.docker.DockerSlave _terminate
Removed container 2853f3aae0067063f26f70c3521d4e595047ceb1c1144a4522e0f3c99a80aa12
Dec 15, 2015 1:24:27 AM INFO com.nirima.jenkins.plugins.docker.builder.DockerBuilderControlOptionProvisionAndStart execute`

**Comment by nashdiesel** [comment]
I did another test on a fresh jenkins instance (to rule out environment issues) on version 1.626 with only the docker plugin installed (aside from the defaults) and ran into the same issue with pending-waiting for executor.  I did check the slave connection and it worked on "test connection". I also noticed that when I ran my job against the label a container was indeed started on the slave, but the build did not run.

**Comment by Thomas-Clark** [comment]
If you go to your docker host and run the 'docker ps' command, do you see ports open for SSH for your slaves there?

**Comment by nashdiesel** [comment]
You mean the slave host I'm using to spawn the containers? This is my output:

`CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                   NAMES
fdca8eb50609        evarga/jenkins-slave   "bash -c '/usr/sbin/s"   51 minutes ago      Up 51 minutes       0.0.0.0:32773->22/tcp   suspicious_lumiere`

**Comment by Thomas-Clark** [comment]
I don't use the evarga/jenkins-slave but what credentials are you using in the cloud config? Username with password? Private certificate? Can you test logging in to the slave with SSH manually to see if you can even connect to the slave the way Jenkins would?

**Comment by nashdiesel** [comment]
I am using the user/pass for the evarga/jenkins-slave default under the image section.   I believe they are working since I can indeed start and stop containers using the plugin from the jenkins master.  I just can't execute a build within that container by running the build against the cloud slave.   I'm connecting over TCP to invoke docker commands (I think).   I went ahead and installed ssh key pairs on the master/slave and was able to then ssh directly.  I also was able to connect to the slave host from the master via SSH as a conventional slave, but I don't believe that is necessary.  Even with those changes I'm still getting the same pending message.   I also tried switching out the credentials under the image section with the key pair for the actual host (not the docker image) and that results in the same pending-waiting for next exectuor message.

**Comment by KostyaSha** [comment]
DockerSShLauncher uses SSHLauncher - the same as standard Dumb slaves. You can specify user/pass or ssh keys.

**Comment by DanielHouston** [comment]
I'm seeing the same problem after upgrading to Docker 1.9.1. Previously it was fine on Docker 1.7.1.
Tested on version 0.16.0 and 0.14.0 of the plugin.

**Comment by nashdiesel** [comment]
Interesting.  My jenkins instance is running 1.7.1 but the slave was on 1.9.1.   I downgraded the slave to 1.7.1 but I'm still unfortunately having the same problem.

**Comment by nashdiesel** [comment]
I tried reinstalling the jenkins host again this time using tomcat for more granular logging but it's not really showing me anything additional on the error side.  Notable I can go to the Docker link in manage jenkins and stop the running containers there with ease, it doesn't appear to be related to anything with connectivity to the slave.    If anyone has any other troubleshooting suggestions I'm all ears.

**Comment by tianlai** [comment]
I have the exact same issue with docker 1.9.1 and docker-plugin 0.16.0. I'll try downgrade it to 1.7.1 tmr

**Comment by tianlai** [comment]
I was doing some debug, looks like it hangs at `DockerCloud.java` line: 393
`dockerTemplate.getLauncher().waitUp(getDisplayName(), dockerTemplate, ir);`

**Comment by tianlai** [comment]
I resolved the issue with opening the mapped ssh port of the docker container on the docker machine. Do `docker ps` to check the port mapping and make sure the port is open to the jenkins instance. My combination is Docker 1.9.1 with docker api 1.21 and Jenkins docker-plugin 0.16.1 snapshot (I built my own due to https://issues.jenkins-ci.org/browse/JENKINS-30200). 

Current code works fine but there might be some room to improve in that the "hanging" is basically retrying the connection, it should catch some network exceptions so that we don't waste time here to discuss the issues.

**Comment by KostyaSha** [comment]
Obviously if you are using ssh connection jenkins must have access to connect to container. Also if you are using custom container and didn't prepare it well you will have issues. Docs not very huge, but they define success way.

**Comment by tallandtree** [comment]
I run into the same issue. But in my case, the cause seems that I run my jenkins master container in a bridge network with --net mynetwork. The slave is started in the default 'bridge' network. My jenkins master simply cannot find the slave (ssh jenkins@172.17.0.2 (ip address of slave) hangs). If I connect the running slave manually to the network, it gets a new IP address with which I can connect from my Jenkins master.
 Anyone knows if it is possible to start the slave with a "--net mynetwork" option (like the Cloudbees Docker Custom Build Environment plugin?

**Comment by bbansalWolfPack** [comment]
I am having the same issue. My jobs are stuck in build queue and wont move until I reboot the system. Does anybody has a solution or idea what is the issue?

**Comment by ndeloof** [comment]
Hard to diagnose this generic issue without more details on the actual failure.
Please give 01.7 a try and re-open if this issue occurs again.
