### ISSUE TITLE
Improve Availability Documentation 

### ISSUE THREAD

**Issue by haysclark** [jenkinsci/docker-plugin#364]
It would be great to see some added docs on the experimental 'Availability' options.  This documentation could either be in the official plug-in page, or in Jenkins (?) button hints.

<img width="747" alt="screen shot 2016-01-05 at 9 49 39 pm" src="https://cloud.githubusercontent.com/assets/138324/12135899/ff89869a-b3f6-11e5-94b7-7e6f9cf46c93.png">

**Comment by KostyaSha** [comment]
It was my efforts to make strategies choosable, but i'm not working on this plugin anymore. Can even suggest disable it if nobody continue working on it.

**Comment by ndeloof** [comment]
That's indeed confusing. As the primary goal for this plugin is to provision a fresh new container per build, then destroy, I guess we should just hide this option and implement container cleanup internally.

**Comment by KostyaSha** [comment]
> That's indeed confusing. As the primary goal for this plugin is to provision a fresh new container per build, then destroy, I guess we should just hide this option and implement container cleanup internally.

You are totally mistaken, the goal was to provide features, and other strategies worked (with some nuances, but they easily solveable). Just curious, is it your personal contribution or as CloudBees employee?

**Comment by ndeloof** [comment]
deprecated to only support "Once"
