### ISSUE TITLE
JNLP mode with user jenkins breaks the init command

### ISSUE THREAD

**Issue by bamthomas** [jenkinsci/docker-plugin#366]
When running container with JNLP and user jenkins, the init scrit has a quote that breaks the script :

    $> docker logs jenkins-slave
    (...)
    HOSTNAME=32244a92e296
    TERM=xterm
    CONFIG=/tmp/config.sh
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    PWD=/
    HOME=/root
    SHLVL=1
    _=/usr/bin/env
    + RUN_OPTS='-jnlpUrl http://10.242.167.79//computer/docker-cloud-32244a92e296//slave-agent.jnlp '
    + '[' '!' -z 91b4e4d733f79595292a98ed32c6fe9eef2a4f1fc62188ff9dafe37378ed6ce2 ']'
    + RUN_OPTS+=' -secret 91b4e4d733f79595292a98ed32c6fe9eef2a4f1fc62188ff9dafe37378ed6ce2 '
    + RUN_CMD='java -jar /home/jenkins/slave.jar -jnlpUrl http://10.242.167.79//computer/docker-cloud-32244a92e296//slave-agent.jnlp  -secret 91b4e4d733f79595292a98ed32c6fe9eef2a4f1fc62188ff9dafe37378ed6ce2 '
    + '[' '!' -z jenkins ']'
    + '[' xjenkins '!=' xroot ']'
    + '[' jenkins '!=' null ']'
    + RUN_CMD='su - jenkins -c '\''java -jar /home/jenkins/slave.jar -jnlpUrl http://10.242.167.79//computer/docker-cloud-32244a92e296//slave-agent.jnlp  -secret 91b4e4d733f79595292a98ed32c6fe9eef2a4f1fc62188ff9dafe37378ed6ce2 '\'''
    + su - jenkins -c ''\''java' -jar /home/jenkins/slave.jar -jnlpUrl http://10.242.167.79//computer/docker-cloud-32244a92e296//slave-agent.jnlp -secret 91b4e4d733f79595292a98ed32c6fe9eef2a4f1fc62188ff9dafe37378ed6ce2 \'
    su: invalid option -- 'j'
    Usage: su [options] [LOGIN]

**Comment by KostyaSha** [comment]
Of course ;) It was my WIP that magnayn released.

**Comment by bamthomas** [comment]
I have a pull request that solved the issue for us if you like

**Comment by KostyaSha** [comment]
Feel free plugin "author" will merge it of course (i personally already fixed everything in my rewritten plugin that i continue developing outside this).

**Comment by bamthomas** [comment]
cf #367
