### ISSUE TITLE
https support to use with docker UCP

### ISSUE THREAD

**Issue by ediri** [jenkinsci/docker-plugin#368]
Hi there,

i wanted to ask if there was a special reason why there is no https support for the Docker URL? 

I use the Docker UCP (beta6) and stopped my own docker swarm cluster. And Docker UCP uses https, Thats means i cant use the docker-plugin. 

I would do the changes in the code if someone from the contibuters point me to the  right code place!
Cheers,

**Comment by ediri** [comment]
can sombody help me here? I am even willing to do any code changes on my own...

**Comment by ndeloof** [comment]
You for sure can use https, actually the URL to use has to rely on `tcp://...` scheme but will for sure be secured as you configure your client keys as credentials.
