### ISSUE TITLE
Docker containers are created for pending jobs even though shutdown mode is activated

### ISSUE THREAD

**Issue by padyx** [jenkinsci/docker-plugin#369]
When Jenkins is put into shutdown mode with some jobs are still pending in the queue, the docker plugin will still create docker slaves for them, even though it does not start to execute them.
(see attached screenshot)

I'd expect that no new docker containers would be created while Jenkins is in shutdown mode.
The reason for this: If you need to reboot your Docker or Jenkins instance, those hanging instances will need to be cleaned up later manually.

Jenkins-Version: 1.625.3  (LTS)
Docker Plugin version: 0.16.0

Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:12:04 UTC 2015
 OS/Arch:      linux/amd64

Old Data (Manage Jenkins): "No old data was found."
Our infrastructure: Dedicated Ubuntu Machine running Jenkins inside a Tomcat 8. A dedicated Ubuntu machine running docker.

Reproduce:
* Configure a simple image to run as docker slave
* Queue 2 jobs.
* After first job has started executing, put jenkins to shutdown mode
* Wait until first job has finished

![image](https://cloud.githubusercontent.com/assets/649179/12418393/58aa2014-beaf-11e5-98b2-e607318bf45b.png)

**Comment by KostyaSha** [comment]
That's not plugin issue. How much Provisioner asked, so plugin provisioned. Also containers are really light, shouldn't be a problem.

**Comment by padyx** [comment]
Ok, thanks for the feedback - If the plugin is not responsible for requesting the provisioning, you can close this issue of course.

**Comment by magnayn** [comment]
My guess would be that by the time you're requesting the shutdown, the (asynchronous) demand for additional slaves is likely already in-progress (probably as soon as those jobs hit the build queue).
