### ISSUE TITLE
Dynamic container provisioning does not respect build queue priority.

### ISSUE THREAD

**Issue by matthiaso** [jenkinsci/docker-plugin#370]
As far as I understand, the build queue (w/o any additional plug-ins) should use a first in, first out order. At least w/o the docker-plugin it did.

The dynamic provisioning however breaks this rule, assuming I have a constant build queue of 4 jobs (two limited to dockerimage-a and two limited to dockerimage-b). As soon as the build for one of the jobs starts, a job of the same type is added to the build queue again (this is not the real setup of course, but should be a good assumption for this case).

I also set a maximum container cap of 2. Now with the dynamic container provisioning as soon as a job ends, it always starts to provision dockerimage-a, figures one slot is available and starts the build job for dockerimage-a. Next it also starts to provision dockerimage-b however it figures the limit has been reached and tries to provision later again. Because there are always jobs for dockerimage-a and dockerimage-b waiting in the build queue, only jobs for dockerimage-a get built, the jobs for dockerimage-b would only be built if there are no more jobs waiting for dockerimage-a.

**Comment by KostyaSha** [comment]
Please firstly check how core do provisioning.

**Comment by matthiaso** [comment]
Thanks for the quick reply and sorry for my mistake, probably not an issue with the plug-in.
