### ISSUE TITLE
bug PrivateKeyInfo cannot be cast to PEMKeyPair

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/docker-plugin#372]
Discovered in #371 and reported in upstream library docker-java/docker-java#441.

docker-java/docker-java#441 closed the issue as `invalid` citing:

> Not a docker-java issue. That's caused by multiple docker-java libraries from different plugins in your jenkins installation. I can suggest to use my plugin https://github.com/KostyaSha/yet-another-docker-plugin where i fixed this issue.

Therefore, I open this bug report since the responsibility apparently falls on the `docker-plugin` to fix.

**Comment by KostyaSha** [comment]
As i said in upstream issue, i mistaken. Even if was right that you installed to many plugins in your jenkins that caused class errors, that doesn't mean that it's docker-plugin issue.
