### ISSUE TITLE
Reference Leak: DockerComputer ClassLoader

### ISSUE THREAD

**Issue by maxfields2000** [jenkinsci/docker-plugin#374]
Hello!

We've found a potential reference leak with the Docker Plugin. Running Jenkins 1.617 and Docker Plugin 0.15.  I can try and compress and send you the memory dump. Taking a look at the dumpfile:

13,134 instances of "com.nirima.jenkins.plugins.docker.DockerComputer", loaded by "hudson.ClassicPluginStrategy$AntClassLoader2 @ 0x853e5200" occupy 419,645,232 (48.20%) bytes. These instances are referenced from one instance of "java.util.HashMap$Node[]", loaded by "<system class loader>"

It's a class loader leak. We had to run Java 1.8 to catch this though we had the problem in 1.7 but the classloader objects were in permgen and much harder to get a clear report.

To give you an idea of scale, we currently use the Docker Plugin on a Jenkins instance with 800 or so jobs defined and around 20 different slave images.  We probably spin up about 5-6k containers a week, this took about 18 days to manifest at this count.  

I suspect that the Docker Computer class objects are not getting removed after the nodes are released by Jenkins. I do not know if this is a plugin issue or a Jenkins issue (i.e. this is just something Jenkins does with all Computer class objects whether they are DockerComputer or default ones).  I can confirm this because I also had to deploy the Metrics plugin which also reports that these nodes exist even after they have been destroyed.

**Comment by ndeloof** [comment]
classloader issue is about new classes being created again and again, what you seem to report here is a memory leak where some object keep being referenced in memory and should be garbage collected. Hard to diagnose without more details on the references.
Can you please first give 0.17 a try to confirm this hasn't been fixed yet, then reopen ?
