### ISSUE TITLE
Maintain preseeded containers running.

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/docker-plugin#379]
It would be awesome if you could have a minimum number of containers running at any given time (each with a run once strategy).
1. Let's say you set the minimum number of active "run once" containers to 5.  Then even though there are no builds queued up the docker plugin ensures that there's at least 5 "run once" containers actively running.
2. Then a build comes in and takes up one of the "run once" executors.  When the build finishes it deletes the docker container.  The result is no there are only 4 "run once" containers actively running.
3. The docker-plugin notices there's only 4 "run once" instances but it should have 5.  It then proceeds to provision 1 additional container so that there are 5 ready to go containers.

In my use case, I have one container image ready to build all types of projects.  So any pull requests that come in or main builds that are executed make use of the same container image.  It takes time to spin up a new container for each build in the queue.  Therefore, it would be nice to have a minimum set of active containers but elastically expand that number as more are needed.

This setting should be available in the `Images` section and configurable per image that's referenced.  Default should be `0` which is what it currently is today.

**Comment by sskjames** [comment]
This will be an awesome feature to support. Yes, it really takes time to spin up a new slave and will be great to have a pool of slaves readily available.

**Comment by magnayn** [comment]
Are you sure the slow bit is the time taken to spin up the container, and
not the time taken to SSH into it?

IME, it's the latter (and the time Jenkins spends 'asleep', not even asking
for a host) that causes the delays.

**Comment by samrocketman** [comment]
> IME, it's the latter (and the time Jenkins spends 'asleep', not even asking for a host) that causes the delays.

Depends on the location (i.e. datacenter of slaves/master), how many plugins a Jenkins instance is using, and how the client container has been built.

Regarding:
* datacenter of slaves/master - Sometimes slaves can be located in drastically different locations so initializing them can be delayed due to geography.
* how many plugins a Jenkins instance is using - the more plugins the master has then potentially the more Jars are loaded (scp'd) from the master to the slave during startup.  `slave.jar` is only 500KB but my Jenkins loads ~ 30MB of jar files due to Jenkins plugins from master to slave.
* how the client container has been built - containers can be preloaded with `slave.jar` and all dependent Jars.  This helps speed up the amount of time a container is provisioned and agent software started drastically.  This helps mitigate bullet point 2.  Additionally, a shared volume can be used to cache the jars instead.

> and the time Jenkins spends 'asleep', not even asking for a host

What causes this delay?  Our Jenkins instance "sleeps" up to 30 minutes at times.  Preseeding containers helps address all of the aforementioned issues by simply loading agents before they're needed.  I don't care about idle resources but I definitely care when builds or deploys are delayed for 15-30 minutes because there's no container runtime available despite capacity.

**Comment by ndeloof** [comment]
What you describe is how the Jenkins Cloud API should work. But in a docker world, where creating a new container is just about milliseconds, this API doesn't work as expected. We also want containerized agents to only be used once, then destroyed. 
0.17 do use a faster provisioning strategy, you should not get any noticeable delay when a job enter the queue for an agent to be provisionned.

**Comment by samrocketman** [comment]
Incorrect, creating containers is not instant as you describe.  There is a startup time and while these numbers do not matter to you, they matter to me.  Please reopen this issue.

**Comment by ndeloof** [comment]
container creation is under a second (but for initial image pull). 
anticipated Pre-loaded agents is not the direction I want to give to the docker-plugin, I'd like it to offer build specific agents provisioned on-demand, which by nature require some just-in-time provisioning.

**Comment by samrocketman** [comment]
Not everyone's needs are the same.  There's a startup cost to a Jenkins agent more than creating a container. Not sure where you got your metric but my experience has been different.  If you don't plan to implement this then fine.  Please reopen so someone in the community can get to it (maybe even me).

**Comment by ndeloof** [comment]
Jenkins agent startup cost indeed exists, but this is a question of a second (running a JVM then setting up the remoting channel with some bytecode transfert). I use to have a build agent up and starting the build in ~ 3s at most.

For sure, "Not everyone's needs are the same", so the large number of plugins in jenkins ecosystem with comparable goals but distinct implementation details.
I plan to adopt an opinionated approach here and focus on this "per build build container" vision, even some side case might not be covered. I think this will offer some extra features that a "general purpose plugin" wouldn't offer. For those looking for a more classic approach, YADP is a good alternative, as well as other docker-related plugins.

**Comment by samrocketman** [comment]
I guess I'll take a wait and see approach then.  I may request this be reopened in the future if there's not a significant improvement in time an agent is available to service work for Jenkins.  I don't really care about container startup time but more the time it takes for an agent to be ready and registered in Jenkins which can take anywhere from 30 seconds minimum to several minutes in my experience.  It's the primary reason I opened this issue because a large user base doesn't really care that their container was provisioned in seconds if it's not available for actual work.

**Comment by ndeloof** [comment]
What you describe is mostly the Cloud Provisioner decision delay, which is a pain. Nobody want's this, this only made sense with the pay-by-the-hour EC2 billing model, which is obsolete as well !

[FastNodeProvisionerStrategy](https://github.com/jenkinsci/docker-plugin/blob/master/docker-plugin/src/main/java/io/jenkins/docker/FastNodeProvisionerStrategy.java) should reduce this significantly, and as a longer terms plan I wish I could adopt some provisioning bypass experimented on [one-shot-executor-plugin](https://github.com/jenkinsci/one-shot-executor-plugin).

Such strategy should be included in core, I'll look into setting up a PR for this so other plugins don't have to copy/paste this again and again.

**Comment by samrocketman** [comment]
That sounds great @ndeloof.
