### ISSUE TITLE
TLS is still not work  

### ISSUE THREAD

**Issue by ringtail** [jenkinsci/docker-plugin#381]
I set Docker URL to https://master1.cs-cn-hangzhou.aliyun.com:14805   and set the correct certs. But I got the code below   with jenkins 1.649 and docker-plugin 0.16.0 

```
shaded.org.apache.http.conn.UnsupportedSchemeException: https protocol is not supported 
```

**Comment by ringtail** [comment]
I have searched the issues before. It seems that lots of people have the same problem.But I can't use the docker deamon without tls.

**Comment by KostyaSha** [comment]
@ringtail hi, as i was unable to continue development in terms of this plugin, i tested TLS support in https://wiki.jenkins-ci.org/display/JENKINS/Yet+Another+Docker+Plugin

**Comment by ringtail** [comment]
@KostyaSha Hmm.I'll check it. thank you~

**Comment by ringtail** [comment]
@KostyaSha It works.thank you very much.

**Comment by stormbeta** [comment]
I'm running into this as well - TLS support appears to be non-functional, which is a pretty big problem considering that's the only way to securely access a remote docker daemon.

**Comment by ndeloof** [comment]
TLS is fully supported in latest release. Please note the correct URL scheme is `tcp://...`, not `https://...`

**Comment by ringtail** [comment]
please try yet-another-docker,it works.
