### ISSUE TITLE
DockerCloud.java:198 // provisionedImages never sync

### ISSUE THREAD

**Issue by kepeket** [jenkinsci/docker-plugin#382]
Hi

I'm just posting an issue here to warn you about a crash proof behavior.

In DockerCloud.java, starting line 198, the decrementAmiSlaveProvision is defined to decrease the number of number of provisioned AMI.

Unfortunately this code is only called in the `finally` in `DockerCloud.java:248` and never synced anymore, even when `estimatedAmiSlaves` returns 0 in `DockerCloud.java:504`.

I think that's too bad, because if you remove, for any reason, a container that belongs to the cloud, this container will never be replaced, because it's still counted as on in `provisionedImages`.

In the end, I don't really understand what's the purpose of that variable. Is it there for race condition?

Thanks for taking a look at it.

Kev.

**Comment by KostyaSha** [comment]
Asking the number of provisioned imaged is bit expensive, that's why it store own variable. Manual is always bad and indicates that you do something wrong.

**Comment by kepeket** [comment]
Hi thanks for your answer.

> Manual is always bad and indicates that you do something wrong.

That's true unless docker decide to crash (or your host server, or whatever). Then, with your implementation, your only choice is to restart Jenkins to wipe `provisionedImages` from memory.


I don't think there is a real reason to keep that variable, but I understand that you could not want to change that. I'll build a fork of the plugin and use my fix in it instead.

Thanks for your time.

**Comment by KostyaSha** [comment]
There is the code that removes bad containers after some delay plus after master restart it automatically wipes bad containers. @kepeket i'm not maintaining this plugin anymore ( i continue at https://github.com/KostyaSha/yet-another-docker-plugin ). So you free for contributions.

**Comment by ndeloof** [comment]
I plan to remove provisionedImages at some time, this is inherited from ec2 cloud plugin (so the `ami` variable name) to limit resource cost, doesn't make sense on a docker infrastructure.
