### ISSUE TITLE
Multiple Docker "Clouds"

### ISSUE THREAD

**Issue by farahfa** [jenkinsci/docker-plugin#386]
Hello,

I have two Slave VMs setup with docker and I've added them both to Jenkins; is there a way to tell Jenkins to use the second vm when the first one is out of memory?

Like, if lets say I have 32GB of memory on each VM and each job takes 2GB of memory and I run 17 jobs at the same time, I expect the 17th job to run on the second slave VM rather than wait in queue or run on the first slave but runs a lot slower (or actually in many cases some of the containers gets killed and the job fails).

Fadi

**Comment by magnayn** [comment]
Not easily. You probably want to check out docker-swarm or joyent triton, which will present individual hosts as a homogenous 'cloud'
