### ISSUE TITLE
Add network (net) parameter to docker template settings

### ISSUE THREAD

**Issue by michelvocks** [jenkinsci/docker-plugin#387]
Hello all,

I would really like to see the "--net" parameter in the docker template settings.
That allows me to start my jenkins slave in a predefined network.
Or is there any work around that I could use to set this parameter?

Greetings

**Comment by gclayburg** [comment]
This would be a great feature to have.  It would simplify my [BuildFarm](https://github.com/gclayburg/buildfarm) for sure
