### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by kyhavlov** [jenkinsci/docker-plugin#388]
there's a few fixes that have gone in since the last release that required me to build from master to use; are there any plans to publish 0.17.0 at some point?

**Comment by pznamensky** [comment]
I have the same question.

**Comment by KostyaSha** [comment]
You can try https://github.com/KostyaSha/yet-another-docker-plugin where i continue my work that i started here. Or wait this plugin for releases.

**Comment by fboudra** [comment]
@KostyaSha as long as your docker plugin is in experimental state, I personally  don't feel to switch to something else when I have a system running in production. I'll certainly try your plugin when you feel more comfortable to get it out of experimental and make 0.1.0 release :) Nonetheless, your work is really appreciated.

**Comment by KostyaSha** [comment]
my experimental state is more stable than this, and if something works for you then you can just use without looking at numbers.

**Comment by dasJ** [comment]
Bumping this again. What is so hard with just hitting the release button on GitHub?

The master contains a fix for an issue that I have and I don't really like building from master myself and then deploy the plugin file (which is what I'm currently doing).

**Comment by KostyaSha** [comment]
> What is so hard with just hitting the release button on GitHub?

It pretty clear that it not maintained https://github.com/jenkinsci/docker-plugin/graphs/contributors :)
