### ISSUE TITLE
Cannot build docker images: "Could not get client"

### ISSUE THREAD

**Issue by sirhopcount** [jenkinsci/docker-plugin#389]
Hi,

I am having some trouble building images. Every time I run the job I get the following error:

```
Docker Build
Docker Build: building image at path /var/lib/jenkins/jobs/docker_image_build/workspace/dockerfiles/Apache/base-jessie
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Could not get client because we could not find the cloud that the project was built on. What this build run on Docker?
    at org.apache.commons.lang.Validate.notNull(Validate.java:192)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.getClient(DockerBuilderPublisher.java:173)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.access$200(DockerBuilderPublisher.java:116)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:246)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run$1.invoke(DockerBuilderPublisher.java:232)
    at hudson.FilePath.act(FilePath.java:990)
    at hudson.FilePath.act(FilePath.java:968)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:232)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:189)
    at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:306)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Build step 'Build / Publish Docker Containers' marked build as failure
Finished: FAILURE
```

To elaborate some more, docker is running locally and a "cloud" is configured. I have no problem starting an already existing image via a job but building one for some reason fails.

There is also no option to specify a cloud in the "Build / Publish Docker Containers" build step.

The Cloud section from config.xml

```
<clouds>
    <com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@0.16.0">
      <name>docker</name>
      <templates>
        <com.nirima.jenkins.plugins.docker.DockerTemplate>
          <configVersion>2</configVersion>
          <labelString>jenkinsslave</labelString>
          <launcher class="com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher">
            <sshConnector plugin="ssh-slaves@1.10">
              <port>22</port>
              <credentialsId>64b21707-c8e9-4a8e-a0fc-345488070b2c</credentialsId>
              <jvmOptions></jvmOptions>
              <javaPath></javaPath>
              <maxNumRetries>0</maxNumRetries>
              <retryWaitTime>0</retryWaitTime>
            </sshConnector>
          </launcher>
          <remoteFsMapping></remoteFsMapping>
          <remoteFs>/home/jenkins</remoteFs>
          <instanceCap>1</instanceCap>
          <mode>NORMAL</mode>
          <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
            <idleMinutes>10</idleMinutes>
            <idleMinutes defined-in="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">10</idleMinutes>
          </retentionStrategy>
          <numExecutors>1</numExecutors>
          <dockerTemplateBase>
            <image>jenkinsslave</image>
            <dockerCommand></dockerCommand>
            <lxcConfString></lxcConfString>
            <hostname></hostname>
            <dnsHosts/>
            <volumes/>
            <volumesFrom2/>
            <environment/>
            <bindPorts></bindPorts>
            <bindAllPorts>false</bindAllPorts>
            <privileged>false</privileged>
            <tty>false</tty>
            <extraHosts class="java.util.Collections$UnmodifiableRandomAccessList" resolves-to="java.util.Collections$UnmodifiableList">
              <c class="list"/>
              <list reference="../c"/>
            </extraHosts>
          </dockerTemplateBase>
          <removeVolumes>false</removeVolumes>
          <pullStrategy>PULL_NEVER</pullStrategy>
        </com.nirima.jenkins.plugins.docker.DockerTemplate>
      </templates>
      <serverUrl>unix:///var/run/docker.sock</serverUrl>
      <connectTimeout>0</connectTimeout>
      <readTimeout>0</readTimeout>
      <credentialsId></credentialsId>
      <containerCap>100</containerCap>
    </com.nirima.jenkins.plugins.docker.DockerCloud>
  </clouds>
```

I am using the following versions:

```
Jenkins: 1.656
Docker plugin: 0.16.0   
```

**Comment by KostyaSha** [comment]
Because build must happen on slave, set label in job.

**Comment by sirhopcount** [comment]
I am probably missing something but there is no option called label (in the job options):

![dockerplugin_build](https://cloud.githubusercontent.com/assets/1218282/14530886/3efa4208-025b-11e6-950c-1987be6b04bb.png)

**Comment by thomassuckow** [comment]
I have not used this feature, but I believe @KostyaSha means you should use the "Restrict where this project can be run" option for the Job to be a container on the machine you wish to build on.

https://wiki.jenkins-ci.org/download/attachments/72417700/myst-restrictwherejobcanberun.png?version=2&modificationDate=1400680144000

It would appear that it will build the container on the same machine as the slave is running on.

**Comment by thomassuckow** [comment]
I have not used this feature, but I believe @KostyaSha means you should use the "Restrict where this project can be run" option for the Job to be a container on the machine you wish to build on.

https://wiki.jenkins-ci.org/download/attachments/72417700/myst-restrictwherejobcanberun.png?version=2&modificationDate=1400680144000

It would appear that it will build the container on the same machine as the slave is running on.

**Comment by sirhopcount** [comment]
Just to be sure, am I correct to understand that you cannot build docker images on the "master"? Because we do not have any slaves, docker runs on the same machine as Jenkins.

Even if I restrict the job to master it still gives the same error:

![dockerplugin_label](https://cloud.githubusercontent.com/assets/1218282/14555910/a54e0504-02f5-11e6-9879-a96fedb15b5b.png)

```
Could not get client because we could not find the cloud that the project was built on. What this build run on Docker?
```

**Comment by timstoop** [comment]
Having a full working example would be very helpful here, I think.

**Comment by KostyaSha** [comment]
Of course it would work on master. You MUST run job on docker-plugin provisioned slave and only then use this step. Error message is clear, it tries to get docker from this slave.

**Comment by MrEnzyme** [comment]
@timstoop +1 to that. it's unclear from the wiki page how this part of the plugin is supposed to be used. 

@KostyaSha what does the slave need in order for this build step to work? does it need the docker cli and access to a daemon?

**Comment by oppianmatt** [comment]
Sorry @KostyaSha error message isn't very clear. I've got a Dockerfile in my repo and I'm just trying to configure a simple job to build it on change. You add the build step "Build / Publish Docker Containers" expecting it to a docker build but you get this error. I, like many others, have a simple jenkins setup with just a master and no slaves.

Basically I just wanted to use the docker plugin to build the container rather than shell commands. Note using a execute shell script and doing a docker build works.

**Comment by KostyaSha** [comment]
@oppianmatt imho using native CLI atm is better variant and reproducible variant.

**Comment by kpostrup** [comment]
@oppianmatt I agree that the error message is unclear from a user perspective. I think there is also a typo in the message, probably causing the misunderstanding in the first place:

> What this build run on Docker?

**Comment by geekvikas** [comment]
My scenario is bit different but exact same error

I have this setup

Master Docker Server (docker.myserver.com)
|______ Jenkins Container 
|______Git Container

both my Git and Jenkins are running in separate containers. Here is what I am trying to do 

1) Commit my code in GIT
2) Git Hook calls Jenkins to initiate the build
3) Build is basically a Node Repo which is copied from Git server onto shared volume (/var/jenkins_home/myrepo). This repo contains a Dockerfile to build the dependencies and node application
4) At this step, I should be able to initiate a Docker (remote) command to build & start my another docker container using the Dockerfile.

My Docker Cloud is configured and I can see all running nodes, even use "Docker Start/Stop" plugin to start or stop an existing container(s).

any suggestions?

**Comment by KostyaSha** [comment]
You are all has different configuration and cases, but mixing everything in one thread.

**Comment by KostyaSha** [comment]
> Even if I restrict the job to master it still gives the same error:
> 
> 
> 
> Could not get client because we could not find the cloud that the project was built on. What this build run on Docker?

You must not run JOB on MASTER.

`java.lang.IllegalArgumentException: Could not get client because we could not find the cloud that the project was built on. What this build run on Docker?`
means that CMD tries extract docker client connection from running slave where build happens and it MUST be docker provisioned slave.

**Comment by mailtosmyk** [comment]
You must not run JOB on MASTER.
Why not? Restricted by religion? Or you are AWS agent and trying to sold us additional node for $$$$?

KISS pattern forever. Useless plugin. Uninstall.

**Comment by vickybansal** [comment]
Hi, I am also getting the similar error message. There is no option to change from "cloud this project was built on" to salve or specific location. Currently, I have configured everything on Master. it works from command line. But this plug is not able to reflect the other option. I am getting the below error message. 

ERROR: Build step failed with exception
java.lang.RuntimeException: Could not find the cloud this project was built on
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.getCloud(DockerBuilderPublisher.java:217)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:427)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1819)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Build / Publish Docker Image' marked build as failure
Recording test results

**Comment by jovianinc** [comment]
@vickybansal did you find solution to this? I am trying to setup Jenkins with ECR on K8S cluster and facing same error as above.

**Comment by damentz** [comment]
In-case anyone else came here and found the posts here unhelpful, you want to be using this plugin:

https://plugins.jenkins.io/docker-build-publish

It performs the docker build and push steps on the running instance regardless of whether your agent is already containerized or running on on a raw node.
