### ISSUE TITLE
Allow configuration of Idle Timeout for Docker Slaves

### ISSUE THREAD

**Issue by johnrengelman** [jenkinsci/docker-plugin#39]
https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/DockerRetentionStrategy.java#L50-L51
configures the idle timeout to be 0 seconds. It would be nice if this was configurable so that the docker containers could stick around for a bit to handle more jobs (or potentially troubleshooting the container).

**Comment by KostyaSha** [comment]
Timeout is in minutes AFAIR, and it possible now with experimental changes #209 , #81 and many other duplicated issues...
