### ISSUE TITLE
Variable images names

### ISSUE THREAD

**Issue by EslamElHusseiny** [jenkinsci/docker-plugin#393]
Can I construct the image name to include some variables either to be a jenkins job parameters or an exported parameters in previous execute shell step ? 

my image name will be something like : 
`docker-registry-url/${image_name}:${version}`

I've tried but I got this error message : 
`Couldn't macro expand tag`

**Comment by ndeloof** [comment]
@EslamElHusseiny where would you like to use such variables ? For build agent template in jenkins cloud configuration ?

**Comment by EslamElHusseiny** [comment]
I don't remember the use case, it has been more than a year ago.

**Comment by yermulnik** [comment]
The use case for me personally was an ability to use **one** build job for **different** types of containers. E.g. (pretty general example as it's been awhile for me too) there's a repo with sub-dirs named after container type (`repo/centos`, `repo/ubuntu`, etc). So I'd want to have a single job with a selector `centos, ubuntu, etc` and resulting images named `centos`, `ubuntu`, `etc`.

**Comment by Jacq** [comment]
Same scenario here, I am using a parametrized variable ($VERSION) build with a "choice" parameter for selecting the trunk/branch/tag version that I will build.
It works if you use directly the choice variable name, but I need to transform it from "tags/v1.0" to just "v1.0" (to comply with docker tags requirements):
`IMAGE_TAG=$(echo "$VERSION" |cut -d'/' -f 2)`
The $VERSION is recognized as an Image name, but using the environment variable $IMAGE_TAG leads to the above error "Couldn't macro expand tag", finally using ${env.IMAGE_TAG}
