### ISSUE TITLE
Considerations for Large Scale Deployments

### ISSUE THREAD

**Issue by boonware** [jenkinsci/docker-plugin#395]
According to Jenkins documentation here [Considerations for Large Scale Deployments](https://wiki.jenkins-ci.org/display/JENKINS/Consideration+for+Large+Scale+Jenkins+Deployment) each Jenkins slave maintains a connection to the master, and this incurs a thread cost on the master.
A large scale deployment could see a huge number of builds in parallel, and consequently a huge number of co-existing ephemeral slaves for each and every build. This would create a huge load on the master node. A fixed number of slaves capable of running builds in containers as opposed to ephemeral slave containers would not have this disadvantage, it seems. How does the Jenkins Docker plugin take this into account?

**Comment by KostyaSha** [comment]
Ephemeral slave doesn't difference with real slave. They are using the same APIs and for any slave you would need thread and connection. THe only difference on how/when they are killed (Strategy).
PS JFYI: i left this plugin development and available at https://github.com/KostyaSha/yet-another-docker-plugin.
