### ISSUE TITLE
DockerCloud equals method is broken

### ISSUE THREAD

**Issue by samrocketman** [jenkinsci/docker-plugin#398]
Currently, the [`DockerCloud.equals` method](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-parent-0.16.0/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L559-L576) is broken.  Specifically, what is broken is:

``` java
if (templates != null ? !templates.equals(that.templates) : that.templates != null) return false;
```

`templates` is of type `ArrayList<DockerTemplate>`. Because [`DockerTemplate` does not implement an `equals` method](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-parent-0.16.0/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplate.java), it will always evaluate to `false`.  Unless it's evaluating the same list.
### Scenario

I instantiate a new `DockerCloud` with all of the same configuration values as an existing one and compare them.  `templates.equals` will always evaluate to `false`.  Which means `DockerCloud.equals` will always evaluate to `false`.

May this be fixed?

**Comment by magnayn** [comment]
I'm not even sure compare-by-value makes any sense for DockerCloud anyway.

Would simply removing the equals() method (and returning to equality-by-reference) work?

**Comment by samrocketman** [comment]
No, it makes sense because I bootstrap configuration via script console.  E.g. I instantiate a new configuration and would use equals method to compare if it is the same by values.  It should be considered a bug.  For now, without the equals method I simply delete all docker clouds and reinstantiate them as new configurations because I have no way of determining if the configs are the same.  For reference, see [my comment in JENKINS-31094](https://issues.jenkins-ci.org/browse/JENKINS-31094?focusedCommentId=266134&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-266134).

**Comment by magnayn** [comment]
Ok, I think I understand the UC (I could not find any other cloud
implementations that even implement equals(), and Jenkins doesn't require
it, hence my confusion).

That said, I don't think making equals() mean "equality of all fields" is
correct, either. The normal idiom is equality of identifier - for which I
suspect serverUrl is probably the best candidate.

**Comment by samrocketman** [comment]
I see.  If you don't want to implement it that way it's fine.  Deleting all of the docket configs and creating new instances isn't too terrible.  I may eventually contribute a patch myself if you feel it would be useful.

**Comment by KostyaSha** [comment]
@samrocketman JFYI the real problem that it doesn't contain all fields is that not all underlying classes has well defined `equals()`.
Good luck.

**Comment by ndeloof** [comment]
Would need to understand why DockerCloud had to implement `equals` in legacy codebase, sounds to me this is useless and not accurate.

**Comment by samrocketman** [comment]
@ndeloof it is valuable for configuration automation via the Jenkins Script Console.  This codebase is published to the update center.

**Comment by ndeloof** [comment]
@samrocketman I'm not just focussing on my own needs without consideration for published stuff as you suggest, I'm trying to make this plugin healthy and evolve to adopt more advanced docker features. Codebase is a mess, features are unclear and lack of maintenance for one year created a huge issue queue that I'm trying to cleanup.

I wonder how you manage docker cloud configuration using groovy console, and why you need to do so. I wouldn't expect this to be a highly moving configuration

**Comment by samrocketman** [comment]
If you don't want to be perceived that way then perhaps you shouldn't claim my request is useless without comprehending it.

I manage over 20 docker clouds in an on premises openstack environment; managing the docker cloud agents with terraform.  Managing manually as you suggest is a very bad idea.  Automation is better to manage this.

Here's an example: https://github.com/samrocketman/jenkins-bootstrap-shared/blob/master/scripts/configure-docker-cloud.groovy

**Comment by ndeloof** [comment]
two questions then :
- what do you mean by "manage" ? Do you need to change templates on a regular basis ?
- why do you manage 20 clouds, and not just a single one relying on swarm ?

**Comment by samrocketman** [comment]
By manage I mean adjust settings that are available in the configuration I linked you.

We're not using swarm and I don't consider switching to it as a desired resolution for this issue.

**Comment by ndeloof** [comment]
ok. I just was wondering you were aware of swarm standalone that would reduce your configuration needs.
So IIUC you rely on groovy init scripts to force configuration on jenkins startup. What I don't get is how this relates to `equals`. AFAICT you remove all clouds to setup fresh new ones (just like the web UI does)

**Comment by samrocketman** [comment]
It is configured while Jenkins is up and not using `init.groovy.d`.  I'm removing all clouds **because** there's no equals methods or hash methods to determine equality of the configuration.  It's not really feasible for me to compare the 20 different settings per cloud and would just be easier if equality was computed based on the cloud settings.  That's where this issue comes in because of that need.

**Comment by samrocketman** [comment]
In reality, I don't really consider this issue _that_ big of a need because when builds are occurring and clouds get deleted the build continues to run on containers until after the build is finished.  So in practice that was a nice surprise.  As long as that behavior continues to exist it works well enough for me.

**Comment by ndeloof** [comment]
actually this "remove all and replace" is how jenkins behaves when one submit the web UI global configuration.
see https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/GlobalCloudConfiguration.java#L24

**Comment by ndeloof** [comment]
this makes me think reconfiguring clouds would break running builds for those who use a docker-plugin build step with a docker cloud name reference to use dockerhost API. That's a "feature" that surprised me a lot, I expected a plain docker hostname configuration here. I think it mostly make sense when you need container operations to take place on the same dockerhost running your build. Will need to investigate possible impacts.

**Comment by ndeloof** [comment]
I've introduced `equals()` in DockerCloud and referenced classes for testing purpose (https://github.com/jenkinsci/docker-plugin/commit/92d366e580878b07b334e717d2b9b4b481d959b0), I guess this fixes this issue as same time.

**Comment by samrocketman** [comment]
Awesome!  Great work.
