### ISSUE TITLE
Feature request: add Node Properties

### ISSUE THREAD

**Issue by oscarpicasso-intact** [jenkinsci/docker-plugin#402]
Add Node Properties like it is currently possible with standard Nodes such as:
- Environment variables,
- Tool Locations... 

In our case we have a Windows master and we need to override the scm tool location so it can use the linux path of the scm tool inside the container for source code checkout, instead of the one used for polling by the Master.

**Comment by KostyaSha** [comment]
Hi, imho this plugin is not maintained, so i can suggest to look at 
- branch https://github.com/kmbulebu/docker-plugin/tree/nodeprops and make your custom build
- https://github.com/KostyaSha/yet-another-docker-plugin where it work for a long time
Good luck!

**Comment by ndeloof** [comment]
implemented by 6ab06da819b856fbfe8cbc5d3bd66154ff002d68

**Comment by fxnn** [comment]
@ndeloof Thanks for closing this! Does your commit also include tool locations, as requested in this issue?

**Comment by ndeloof** [comment]
yes, all NodeProperties
