### ISSUE TITLE
Set names to running containers as slaves

### ISSUE THREAD

**Issue by Voolkanus** [jenkinsci/docker-plugin#404]
When using the Plugin today, when a slave(container) connects to the Jenkins instance the name of the slave will be "CloudServerName-ContainerID". Is it possible to add an option to change the name of the slave before it connects to the master? I know I can change the name after in the node settings, however when running a dynamic environment, this is not an option.
Thanks!

**Comment by ndeloof** [comment]
Can you please describe in more details your actual goal doing this ?
As agent containers are ephemeral, I would expect nobody cares about their names.
