### ISSUE TITLE
"Environment" field in container settings

### ISSUE THREAD

**Issue by lkzcgfvf** [jenkinsci/docker-plugin#405]
Hi All,

  "Environment" field in container settings - what does it do? There is no doc or popup hint about it.
  I thought that I could use it to pass env. variable to container - but it didn't work for me.
  I entered "FOO=BAR" and there was no such variable in container.

  btw. Is there any way to pass env varaible? like docker run ... -e "FOO=BAR"

**Comment by KostyaSha** [comment]
Yes, should be env. Follow help button.

**Comment by lkzcgfvf** [comment]
there is no help button, see attached screenshot

![image](https://cloud.githubusercontent.com/assets/18581101/16426864/d169f21a-3d38-11e6-96c1-85b1703c6e9e.png)

**Comment by KostyaSha** [comment]
should be the same https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-plugin/src/main/resources/com/github/kostyasha/yad/commons/DockerCreateContainer/help-environment.html

**Comment by lkzcgfvf** [comment]
yes, I tried it. I entered  "FOO=BAR" and there was not "FOO" variable in container during build session.
Installed:
Docker Commons Plugin: 1.4.0
Docker plugin:0.16.0

**Comment by KostyaSha** [comment]
Then bug somewhere or conflict with vars from image.

**Comment by lkzcgfvf** [comment]
is there any way to debug it? I tried to enable logging for "com.nirima.jenkins.plugins." and didn't find in logs any information about what parameters were passed to docker daemon?

**Comment by BrunoLavitForgerock** [comment]
Hi,

I also have the same issue with the same Docker plugins (0.16.0 and 1.4.0).
I'm setting some environment variables in this field, and when I'm using the "env" command to check what are the current environment variables, I'm not able to see them.

**Comment by cagriy** [comment]
This is still not working in 0.16.2.

**Comment by Israphel** [comment]
any news on this?

**Comment by ndeloof** [comment]
"environment" is passed to the docker container create command to set process ENV. If you use a ssh launcher, by nature this one won't propagate environment. Same applies to any ssh slave.
Support for environment node properties has just been added by 6ab06da819b856fbfe8cbc5d3bd66154ff002d68, should help
