### ISSUE TITLE
security issue with binding all started containers with 0.0.0.0::port

### ISSUE THREAD

**Issue by pault28** [jenkinsci/docker-plugin#407]
There is a major security issue with the way containers are provision using the plugin.
All started containers with Docker ssh launcher results in the provisioned container accessible from the outside world - as long one knows the computer name from which they are running.

At the moment the code I can attribute to this is https://github.com/jenkinsci/docker-plugin/blob/1b4b2546567bdb0e1ffcb2a64075a5ed7a1c457e/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/launcher/DockerComputerSSHLauncher.java#L71

Can we make this configurable please?

`Jenkins ver. 1.646`
`docker plugin 0.16.0`

To see what I mean after starting a container with the plugin run `docker ps`:

```
sudo docker ps
CONTAINER ID   IMAGE            COMMAND     CREATED        STATUS        PORTS                   NAMES
211a95fb6373  IMAGE_NAME  "bash -c '"   2 seconds ago   Up 1 seconds  0.0.0.0:32777->22/tcp   sick_meitner
```

**Comment by Loki-Afro** [comment]
duplicate of #20?

**Comment by ndeloof** [comment]
closing as a duplicate of https://github.com/jenkinsci/docker-plugin/issues/20
