### ISSUE TITLE
Start/Stop Docker containers build step 'Run Container' multiple environment properties

### ISSUE THREAD

**Issue by gupbeheer** [jenkinsci/docker-plugin#413]
There is no possiblity to add multiple environment properties to the "Run Container" build step. The split is done based on "\n" but there is only the option to put in one line. 
In the Template settings there is an option to "expand" the "environment" input field to a textarea. This should also be possible within the 'Start/Stop Docker container' build step 'Run Container'.

**Comment by KostyaSha** [comment]
@gupbeheer why do you need this UI based start/stop commands? Could you describe your use case?

**Comment by gupbeheer** [comment]
@KostyaSha we use the start/stop commands (run in our case) to run multiple containers before our integration (black box testing) tests run. This guarantees that we have a clean environment (database, server) that is exactly the same for each test run and we use the plugin to stop and remove the started containers after the tests.
We use the UI because that way we do not need an SSH server configured on Jenkins to run the commands on the Docker machine and for the "automatic" cleaning at the end of the build.

**Comment by KostyaSha** [comment]
But you can use docker CLI and DOCKER_HOST is already injected into build process.

**Comment by gupbeheer** [comment]
@KostyaSha To use Docker CLI the Docker CLI must be available. This is not the case on our build server. We need to SSH to the Docker machine (or another one with the Docker CLI) to execute the command, we then need to store the id's of the running containers so that we can stop and remove them later. The UI is far more simple and is offered in the plugin, so why not use it?
