### ISSUE TITLE
NullPointerException in DockerCloud.pullImage() (Line 328)

### ISSUE THREAD

**Issue by fraz3alpha** [jenkinsci/docker-plugin#415]
When adding a new Template to the Docker Cloud any attempt to try and instantiate a copy of it would fail and a NullPointerException was produced in the log:

```
java.lang.NullPointerException
        at java.util.Arrays$ArrayList.<init>(Arrays.java:2853)
        at java.util.Arrays.asList(Arrays.java:2839)
        at com.nirima.jenkins.plugins.docker.DockerCloud$2.apply(DockerCloud.java:331)
        at com.nirima.jenkins.plugins.docker.DockerCloud$2.apply(DockerCloud.java:328)
        at shaded.com.google.common.collect.Iterators.indexOf(Iterators.java:778)
        at shaded.com.google.common.collect.Iterators.any(Iterators.java:684)
        at shaded.com.google.common.collect.Iterables.any(Iterables.java:623)
        at com.nirima.jenkins.plugins.docker.DockerCloud.pullImage(DockerCloud.java:328)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:363)
        ...
```

Docker plugin version: 0.16.1 (also 0.16.0)

Docker slave version:
```
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 294
 Dirperm1 Supported: true
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 62.73 GiB
```

The symptom was identical to Issue #315 , but in that report the raiser managed to work around his problem by changing the API version and using a different Jenkins. In this case the problem persisted if a different cloud template or Jenkins was used - as long as the image was being targeted at the same Docker host.

Looking at the area around the problem here is the snippet:

```
    private void pullImage(DockerTemplate dockerTemplate)  throws IOException {
        final String imageName = dockerTemplate.getDockerTemplateBase().getImage();

        List<Image> images = getClient().listImagesCmd().exec();

        NameParser.ReposTag repostag = NameParser.parseRepositoryTag(imageName);
        // if image was specified without tag, then treat as latest
        final String fullImageName = repostag.repos + ":" + (repostag.tag.isEmpty() ? "latest" : repostag.tag);

        boolean imageExists = Iterables.any(images, new Predicate<Image>() {
            @Override
            public boolean apply(Image image) {
                return Arrays.asList(image.getRepoTags()).contains(fullImageName);
            }
        });

        boolean pull = imageExists ?
                dockerTemplate.getPullStrategy().pullIfExists(imageName) :
dockerTemplate.getPullStrategy().pullIfNotExists(imageName);
```

What is happening here is that the Docker plugin gets the list of images already on the target host, and then, after parsing the JSON under the covers, works out if it is available, and if it should update it with a pull. 
This breaks if the JSON is badly formed for some reason. 
It so happens that although the majority of the JSON was fine for me host, for one of the images, the RepoTags attribute was the string "null", which led to image.getRepoTags() returning null, and `Arrays.asList( null )` throwing an NPE.

Technically, this was my Docker slave machine being in an odd state, but the plugin was not able to cope nicely with the issue in this case.

I already have a few lines of code to guard against a null, I will open a PR

**Comment by magnayn** [comment]
merged
