### ISSUE TITLE
WARNING: falling back to default instantiation

### ISSUE THREAD

**Issue by jommgoncalves** [jenkinsci/docker-plugin#430]
I already found many issues with this problem but I have not find a solution yet.

> WARNING: falling back to default instantiation com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy {"stapler-class":"com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy","idleMinutes":"10"}
> java.lang.NullPointerException

I know that is just a WARN, but I want to remove it from the logs, because every time that I go to the Manage Jenkins > Configure System, the logs are unreadable :\

**Comment by ndeloof** [comment]
I'm not sure about the exact cause for this, maybe fixed by 127d2cd76f99acd53a493a993e228d5fd615eac2

**Comment by ndeloof** [comment]
please reopen if this issue persist
