### ISSUE TITLE
error: starting container with HostConfig was deprecated since v1.10 and removed in v1.12

### ISSUE THREAD

**Issue by farahfa** [jenkinsci/docker-plugin#433]
I upgraded docker engine to 1.12.1 and I can no longer start slaves due to the following:

```
error: starting container with HostConfig was deprecated since v1.10 and removed in v1.12
```

**Comment by nikname** [comment]
Temporary workaround: install (Docker engine) version 1.11.2

**Comment by eaglerainbow** [comment]
looks to me being a duplicate of #403

**Comment by farahfa** [comment]
@eaglerainbow Yeah, looks like the same problem.. Sorry for opening a new issue about it..

And lol @KostyaSha

**Comment by andrey-moor** [comment]
It seems that the issue had been fixed. When the next release is planned?

**Comment by lamdbui** [comment]
It looks like 0.16.2 has been released here:
https://wiki.jenkins-ci.org/display/JENKINS/Docker+Plugin

I just tried it and it's now working for me. Thanks for fixing this!

**Comment by magnayn** [comment]
Yep, just rolled it last night (The release repo no longer needs port 8081
access, so I can do these things from the office now instead of having to
do it from home)

**Comment by andrey-moor** [comment]
:+1:

**Comment by farahfa** [comment]
Thanks!
