### ISSUE TITLE
Environment variables equivalent

### ISSUE THREAD

**Issue by Reonaydo** [jenkinsci/docker-plugin#435]
Hello!
Setting "Enviroment" for template is not equivalent "Environment variables" in node properties.
They do not visible in jenkins steps only in shell script.
It is possible create same option as node environment?

**Comment by Reonaydo** [comment]
Ooops. In shell script these variables also do not visible.
So it is impossible create node based variables in docker slaves

**Comment by Israphel** [comment]
Is this working? I'd like to use env variables inside the docker agent

**Comment by ndeloof** [comment]
I guess you're using ssh-launcher, which by nature don't preserve docker root process environment.

0.17+ introduced support for NodeProperties (see https://github.com/jenkinsci/docker-plugin/pull/373)

**Comment by ndeloof** [comment]
I just noticed for some weird reason `EnvironmentVariablesNodeProperty` isn't included in
