### ISSUE TITLE
Probably malplaced @Extension

### ISSUE THREAD

**Issue by Loki-Afro** [jenkinsci/docker-plugin#437]
I',m gettin the following error with the current release:

```
Sep 15, 2016 12:57:37 PM hudson.model.Descriptor verifyNewInstance
WARNING: Father of com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@186aa533 and its getDescriptor() points to two different instances. Probably malplaced @Extension. See http://hudson.361315.n4.nabble.com/Help-Hint$
needed-Post-build-action-doesn-t-stay-activated-td2308833.html
Sep 15, 2016 12:57:37 PM hudson.model.Descriptor verifyNewInstance
WARNING: Father of com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@263b1ebc and its getDescriptor() points to two different instances. Probably malplaced @Extension. See http://hudson.361315.n4.nabble.com/Help-Hint-n$
eded-Post-build-action-doesn-t-stay-activated-td2308833.html
```

As far as I rember those warnings mean that settings done to this job will not get applied correctly.

**Comment by KostyaSha** [comment]
Broken by https://github.com/jenkinsci/docker-plugin/commit/64055d3b1f4d35fa2e30e1304cfed84bc959b196

**Comment by Loki-Afro** [comment]
however it did not introduce any noticeable bugs... as far as I can tell.

**Comment by uditjh** [comment]
I'm also seeing the same error and I believe it's causing things to not work. I was using docker version 1.10 first which was starting the container but the job would never actually execute on it. I then upgraded my docker to version 1.11.2 and now I'm seeing the same error as above plus my containers aren't even starting.

Father of com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@333bcbe6 and its getDescriptor() points to two different instances. Probably malplaced @Extension. See http://hudson.361315.n4.nabble.com/Help-Hint-needed-Post-build-action-doesn-t-stay-activated-td2308833.html

**Comment by Loki-Afro** [comment]
@uditjh Check the docker API Version and Try a Test connect, also check that your dockerd is exposing the api, I had the same issue :D

**Comment by uditjh** [comment]
Thank you. I was able to resolve it just now. This is what I have learned.
1. Use docker version 1.11.2 or lower.
2. You will need to open all the ports between Jenkins master and Docker Host. The plugin doesnt print if the port its using is not open. I only had the docker host API port open which would get me the Test Connection to pass but wasnt able to run the job on the container.

**Comment by echho34** [comment]
@uditjh thanks that seemed to have worked. Finally able to get the build to run in the container. Do you know what the port range that the docker plugin uses. I see it goes from 32760 and onwards. I ask because the docker host was not accepting connections on these ports and so I had to temporarily open the ports for the build to get pushed to the slave container

**Comment by KostyaSha** [comment]
Hint: https://github.com/docker/docker/issues/13322

**Comment by zackliu** [comment]
`@Extension` should be placed before ` DESCRIPTOR ` rather than `DescriptorImpl`

**Comment by ndeloof** [comment]
fixed by https://github.com/jenkinsci/docker-plugin/commit/75089b2e705a1463f9aa9920ea95d238ee42ccca
