### ISSUE TITLE
v0.16.2 unix protocol not supported

### ISSUE THREAD

**Issue by pporada-gl** [jenkinsci/docker-plugin#439]
I updated from v0.16.1 and now receive this error when trying to start slave containers. In my testing setup, I mount the docker socket from the host machine into the master so it can push/pull containers. Jenkins itself should then be able to use this socket.

```
Linux 5407332c5784 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
Sep 21, 2016 5:00:48 PM WARNING com.nirima.jenkins.plugins.docker.DockerCloud provision

Bad template 'myorg/build-slave:latest' in cloud 'Docker Slave': 'org.apache.http.conn.UnsupportedSchemeException: unix protocol is not supported'. Trying next template...
javax.ws.rs.ProcessingException: org.apache.http.conn.UnsupportedSchemeException: unix protocol is not supported
```

My solution was to downgrade back to v0.16.1 and restart Jenkins.

**Comment by dj-wasabi** [comment]
I'm not able to downgrade to v0.16.1 due to the hostConfig issue.
Is there a other possible fix available?

**Comment by pporada-gl** [comment]
@dj-wasabi No idea. We need a maintainer for this. I'm not a Java guy.

**Comment by dj-wasabi** [comment]
@pporada-gl 
I know. I was just mentioning this in general letting the maintainer know that a downgrade in my case not possible is. ;-)

**Comment by pragnesh-infostretch** [comment]
getting this error when jenkins is running as docker container
It is working fine when jenkins is running outside of docker host

**Comment by knaperek** [comment]
Also happens to me with Docker version 17.03.1-ce, build c6d412e.
I'm running the master in a Docker container also.

**Comment by ndeloof** [comment]
can't reproduce. 
As 0.17 now uses docker-java-api plugin with netty mode, please check this new release and reopen if this issue persists
