### ISSUE TITLE
Docker cloud doesn't recognice Docker Host Certificate Authentication

### ISSUE THREAD

**Issue by SalahAdDin** [jenkinsci/docker-plugin#442]
Hi guys

I'm testing docker salves configuration and i do all needed steps but it doesn't works:

I created a Docker Host Certificate Authentication:
![seleccion_273](https://cloud.githubusercontent.com/assets/5034215/18826694/5d87d144-8394-11e6-81f6-1cdd89618434.png)
As you can see, there is one credential.

Then, i add a new Docker cloud, but when i try to add a credentials, i can select anyone because there aren't:
![seleccion_272](https://cloud.githubusercontent.com/assets/5034215/18826733/92609414-8394-11e6-891f-7954612d308b.png)
Select box doesn' show me the credentials.

I tried adding new, create it but doesn't show in selection list. Then, i tried with Docker Certification Directory and selection list shows me. 

Which is the problem here? 

I'm using `Jenkins 2.7.4` and Docker `1.12.1`.

Thanks!

**Comment by magnayn** [comment]
I think it's probably that docker-plugin doesn't recognise "Docker Host
Certificate Authentication" - I.E: that's a credential type created by a
different plugin.

The two types I know work are "Docker Certificates Directory" and
"Certificate" (modulo I think that's PKCS#12 which I seem to remember might
not be always easy to generate).

If we can figure out where the credential type comes from we can possibly
support it sice it must boil down to a certificate.

On Mon, Sep 26, 2016 at 8:56 AM, Yusuf (Josè) Luis <notifications@github.com

**Comment by SalahAdDin** [comment]
But, i a tutorial that i following, author shows that for he docker cloud recognize Host Certificate, he has a previous jenkins versionn, so, i don't know which error i have.

**Comment by SalahAdDin** [comment]
I test the `Yet Another Docker Plugin` for this function and it works fine:
![seleccion_274](https://cloud.githubusercontent.com/assets/5034215/18848642/f62b4dee-83f4-11e6-8369-1360bc425e47.png)

So, what's problem with this official plugin?

**Comment by nkcfan** [comment]
Thanks @SalahAdDin, " Yet Another Docker Plugin" works like a charm.

**Comment by ndeloof** [comment]
obsolete. 
docker-plugin 017+ now uses docker-commons for credentials support

**Comment by SalahAdDin** [comment]
@ndeloof which plugin? the oficial docker plugin?

**Comment by ndeloof** [comment]
the docker-plugin from this repository (just released 1.0.0).

**Comment by SalahAdDin** [comment]
@ndeloof how can we install from here?

**Comment by ndeloof** [comment]
![capture d ecran 2017-10-24 a 08 07 51](https://user-images.githubusercontent.com/132757/31927023-7659086c-b892-11e7-9cf2-d58e8b2755e8.png)
plugin is released in Jenkins update center (as 1.0.2), you just can install/update it like any other plugin
