### ISSUE TITLE
Specifying additional arguments to 'docker run'

### ISSUE THREAD

**Issue by rev112** [jenkinsci/docker-plugin#447]
It would be convenient to be able to specify additional (custom) arguments which will be passed to `docker run`. It will allow to use Docker features not yet supported by the plugin itself (for example, passing the `--tmpfs` option, or specifying quotas).

If there are already ways to accomplish this, please let me know.

**Comment by ndeloof** [comment]
As docker-plugin use a java client library, not `docker` CLI, we can't let you define arbitrary parameters. Those have to be supported by the client library then added to plugin UI.
