### ISSUE TITLE
SSH Launch failed on containerised Jenkins master with DockerAPI proxy

### ISSUE THREAD

**Issue by szarlatan** [jenkinsci/docker-plugin#451]
Hey,

That might be simple problem but I'm doing rounds without getting a solution.

Environment is:
- Docker v.1.12.2, installed on host machine
- Docker API proxy container, from shipyard/docker-proxy image. _/var/run/docker.sock_ path mapped to host environment, port _2375_ forwarded to host
- Jenkins v.2.19.1, run as a container from official Jenkins image. Connection test to _tcp://docker-api-proxy-ip:2375_ passes and returns the Docker API version

But during the container provisioning for build I got following problem:

`INFO:
Started provisioning Image of jenkins-slave:latest from siili with 1 executors. Remaining excess workload: 0
Oct 17, 2016 11:24:44 AM com.nirima.jenkins.plugins.docker.DockerCloud pullImage
INFO: Pulling image 'jenkins-slave:latest' again. This may take awhile...
Oct 17, 2016 11:24:46 AM com.nirima.jenkins.plugins.docker.DockerCloud pullImage
INFO: Finished pulling image 'jenkins-slave:latest', took 2887 ms
Oct 17, 2016 11:24:46 AM com.nirima.jenkins.plugins.docker.DockerCloud provisionWithWait
INFO: Trying to run container for jenkins-slave:latest
Oct 17, 2016 11:26:47 AM com.nirima.jenkins.plugins.docker.utils.PortUtils$ConnectionCheck execute
WARNING: Could not connect to 172.17.0.2 port 32782. Are you sure this location is contactable from Jenkins?
Oct 17, 2016 11:26:47 AM com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher getSSHLauncher
INFO: Creating slave SSH launcher for /172.17.0.2:32782
Oct 17, 2016 11:26:54 AM hudson.slaves.NodeProvisioner$2 run
INFO: Image of jenkins-slave:latest provisioning successfully completed. We have now 5 computer(s)
[10/17/16 11:26:54] SSH Launch of siili-b715b7495970 on 172.17.0.2 failed in 8 ms`

The most interesting thing is that IP address from the log is the address of the docker api proxy container, not the one that has been just run, so that is why connection cannot be established.

The question is: why is it that way?

Kind Regards,
Kris
#432

**Comment by uditjh** [comment]
Kris - It looks like you dont have all the ports open from Jenkins to the docker host.  I see its complaining about port 32782 in the log above. Hope this helps.

**Comment by ndeloof** [comment]
ssh launcher trying to guess the target IP is a pain. You should at least set docker hostname in your cloud configuration to point to the host IP. Plan is to make such configuration more explicit so one does not get such cryptic errors.
