### ISSUE TITLE
How to configure Windows container(slave) 

### ISSUE THREAD

**Issue by rajeeshdf** [jenkinsci/docker-plugin#460]
I was trying to get windows container configured as a slave, when build is starting container is getting created but not starting. I tried **Docker JNLP Launcher** and **Docker SSH Computer Launcher**, none of them worked. 

Jenkins is confgired to use **docker-plugin v0.16.2**

Looking through the code, as I understand both these launchers were created for Linux based docker containers, not for windows containers.

This was the error I got when trying to run the build with *Docker SSH Computer Lanuncher* option

`Error in provisioning; template='DockerTemplate{configVersion=2, labelString='xxxxxx', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerJNLPLauncher@7a5414d4, remoteFsMapping='C:\', remoteFs='C:\', instanceCap=1, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@6082d940, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=xxxxxxxxxx}, removeVolumes=true, pullStrategy=PULL_LATEST}' for cloud='Docker-Windows'
com.github.dockerjava.api.exception.InternalServerErrorException
	at com.github.dockerjava.jaxrs.filter.ResponseStatusExceptionFilter.filter(ResponseStatusExceptionFilter.java:53)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:140)
	at org.glassfish.jersey.client.ClientFilteringStages$ResponseFilterStage.apply(ClientFilteringStages.java:128)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:171)`

Thanks

**Comment by Thitho007** [comment]
[This pull request](https://github.com/jenkinsci/docker-plugin/pull/465) should resolve this issue.

**Comment by rajeeshdf** [comment]
@Thitho007 Thanks, that's great. Will update the plugin once this is released. Currently I'm using a tweaked version of this plugin, so that it work with JNLP launcher.

**Comment by ndeloof** [comment]
Proposed [refactoring](https://github.com/jenkinsci/docker-plugin/blob/refactoring/src/main/java/io/jenkins/docker/JNLPDockerSlaveProvisioner.java) would introduce support for windows container without any specific code as it just relies on installed java in container.
