### ISSUE TITLE
Custom docker command for nvidia-docker

### ISSUE THREAD

**Issue by slefrancois** [jenkinsci/docker-plugin#468]
For using docker with GPUs, [nvidia provides a wrapper](https://github.com/NVIDIA/nvidia-docker) that finds the device options for graphics cards and passes them to docker as arguments. This can be done by calling "nvidia-docker" instead of "docker" when launching the container.

I cannot find an option in the plugin to change the docker call, could this be added?

Alternatively, the device parameters --volume-driver={} --volume={} --device={}, could be passed manually, but I can't find where to do so in the plugin.

**Comment by nelson-liu** [comment]
Any updates on this? It'd be a great feature to have in particular for testing machine learning code with jenkins.

**Comment by slefrancois** [comment]
The docker plugin doesn't seem to have been updated, but I have found a way to do it manually using a regular node.

Make sure user `jenkins` is in the `docker` group.

Launch method: "Launch agent via execution of command on master"
Launch command:
`nvidia-docker run --user jenkins --rm -i <docker image>`

To isolate a specific GPU, you can manually provide the `docker` arguments. If you haven't done so, build the driver volume for your machine:
`docker volume create --name=nvidia_driver_375.74 -d nvidia-docker`
Here `nvidia_driver_375.74` should be updated to the correct driver version.

Get the `docker` arguments through the nvidia-docker API:
`curl -s http://localhost:3476/docker/cli`

An example launch command:
`docker run --volume=nvidia_driver_375.74:/usr/local/nvidia:ro --device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia-uvm-tools --device=/dev/nvidiaX --user jenkins --rm -i <docker image>`
Change `--device=/dev/nvidia0` to the desired GPU number.

There is a `NV_GPU` environment variable that can be used directly with nvidia-docker, but I haven't found a way to pass it to the Jenkins launcher.

To start dockers on a remote machine, add `ssh <hostname> ...` to the launch command.

**Comment by ndeloof** [comment]
docker-plugin use a java client implementation to connect to docker API endpoint, not the CLI, so can't be replaced by such a wrapper.

**Comment by slefrancois** [comment]
Indeed, this is a low-level replacement for docker-plugin, until the nvidia-docker arguments can be passed to the plugin.

**Comment by oxynux** [comment]
With the new https://github.com/NVIDIA/nvidia-docker (nvidia-docker2) you could use `docker run --runtime=nvidia ...`

It works fine.

**Comment by jomach** [comment]
would be great to have similar think for the mesos or jenkins x

**Comment by zhongmingHuang** [comment]
> With the new https://github.com/NVIDIA/nvidia-docker (nvidia-docker2) you could use `docker run --runtime=nvidia ...`
> 
> It works fine.

Thank you for your answer, and i would like to raise a question how to enable '--runtime=mvida' in docker plugin configuration. actually I didn't find a place where I could set 'docker run' parameters freely
