### ISSUE TITLE
Hang or crash on one of the Docker host will make the entire Jenkins server to get stuck

### ISSUE THREAD

**Issue by subeeshes** [jenkinsci/docker-plugin#469]
Suppose in case an issue or connectivity problem to one of the docker host and instances on it was used for build, then the entire Jenkins server is getting hanged.
Jenkins UI will appear as usual . However, new builds in the queue will not processed

Similar issue is reported here: https://issues.jenkins-ci.org/browse/JENKINS-38369

**Comment by ndeloof** [comment]
should be fixed in 0.17
