### ISSUE TITLE
Allow more Docker hosts per one Cloud

### ISSUE THREAD

**Issue by zstyblik** [jenkinsci/docker-plugin#470]
Hello,

would it be possible to allow to specify more Docker hosts, eg. delimited by comma, per one Cloud? It would remove the need to manage dozens of duplicate Docker templates.

Thank you.

**Comment by fboudra** [comment]
similar to https://github.com/KostyaSha/yet-another-docker-plugin/issues/47
and https://github.com/KostyaSha/yet-another-docker-plugin/issues/54

the way forward seems to be docker swarm mode but none of the plugins is implementing it yet.

**Comment by dj-wasabi** [comment]
👍

**Comment by ndeloof** [comment]
Simpler solution is to run [docker-swarm standalone](https://github.com/docker/swarm).
I plan to investigate swarm mode but this also means many restrictions on the available API to fine tune containers.
