### ISSUE TITLE
Is there a way to keep a idle container in queen to speed up container launching

### ISSUE THREAD

**Issue by StanleyShen** [jenkinsci/docker-plugin#477]
Hello, all

I am using docker plugin in my jenkins server, and it's perfect for many tasks.
I notice one things, as the image is about 1.4G and it seems some slow if there are multiple jobs to be launched in the same time.

For example, I triggered two jobs in the same time, and I see they are waiting in queue waiting for containers in both slave1 VM.

It will be perfect to spare them in different VMs.
Another way we can keep one running container for backup, if a job is triggered, this running container will be taken firstly, and then another idle running container is launched in queue.

Any idea on it?

**Comment by asgerjensen** [comment]
This would be great

**Comment by ndeloof** [comment]
recycling containers would just kill the benefit from using container as a predictible, isolated environment.
the size of your docker image should not have any impact on the time required to start a container (until you're sotrage driver is misconfigured).

**Comment by StanleyShen** [comment]
I don't mean to recycle container, I mean we can a strategy that we always have X containers in queue(new one, not used one), and when launching jobs, we will use containers in queue first, and launch new container to fill the queue.

In my environment, I see the time to launch docker container is variable, from several seconds to several minutes.

**Comment by ndeloof** [comment]
Oh ok. Then the issue is actually caused by cloud provisioner delay, which could be reduced (I have pending fix for this)

**Comment by StanleyShen** [comment]
Yes, sometimes the time using by launching in my environment is quite significant. I have many jobs configured to use docker container.

For example, I have a flow job which have 3 sub jobs,  sometimes the launching time is 5-6 minutes, comparing the whole job just uses 25 minutes.
In this case, it's quite not acceptable.

Is there a issue for it, or some link so that we can keep track on it as we closed this issue here?

**Comment by ndeloof** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-33512
