### ISSUE TITLE
Windows doesn't support host IP in port bindings

### ISSUE THREAD

**Issue by erik-am** [jenkinsci/docker-plugin#480]
Hi,

I tried to use the Docker plugin with a Docker Host for Windows containers.

I got quite far. Important thing is to override the Docker Command from "/usr/sbin/sshd -D" to a Windows command.

However, the containers are created but cannot be started. When I try to start the created containers by doing `docker start` myself, I get the following error:

>  Windows does not support host IP addresses in NAT settings

Apparently this feature is not yet implemented in Docker for Windows, see https://github.com/docker/docker/issues/26980 ([click here for the line that triggers the error](https://github.com/docker/docker/blob/d3139fc84af390142341a29d3512462d1a449045/vendor/src/github.com/docker/libnetwork/drivers/windows/windows.go#L351))

I guess (but I'm not sure) that the Docker plugin will launch a container with something like `<ip-address>:22:22`.

Is it possible to (optionally) omit the IP address to make it work on Windows?

**Comment by erik-am** [comment]
I see this has actually been fixed already by [this commit](https://github.com/jenkinsci/docker-plugin/commit/3bb3552f71b12058f21983c8a43b7f42735db761) in November.
When is the new version going to be released?

**Comment by ndeloof** [comment]
I plan to push a release in incoming weeks. 
most people I know do rely on JNLP for windows agents.
