### ISSUE TITLE
How do I use --cap-add with this plugin?

### ISSUE THREAD

**Issue by tmcarr** [jenkinsci/docker-plugin#481]
I need finer control over my containers than is allowed with the plugin currently. I don't want to enable full privileged mode. 

Is there a way to specify container capabilities, as one would use --cap-add for on the command line, in the configuration right now?

**Comment by ndeloof** [comment]
docker-plugin do rely on a java client library to access docker API, so you can't pass arbitrary command line parameters and we have to introduce support for every specific option.

**Comment by ndeloof** [comment]
pull requests are welcome if you miss this feature :P
