### ISSUE TITLE
Docker Plugin doesn't pull image from ECR 

### ISSUE THREAD

**Issue by deviscalio** [jenkinsci/docker-plugin#484]
I'm trying to launch docker slave on my Jenkins. I have docker slave images on AWS ECR. Unfortunately the plugin seems is not able to pull image from ECR. I set docker registry in the Jenkins configuration using AWS credential, but it seeme not enough. I also installed amazon ecr plugin, but it seems not works with docker plugin.

Error is:

> Pulling image '_account-id_.dkr.ecr.eu-west-1.amazonaws.com/executor-smild-4.x:4.3.6' again. This may take a while...
> 
> Mar 20, 2017 4:32:04 PM SEVERE com.github.dockerjava.core.async.ResultCallbackTemplate onError
> 
> Error during callback
> com.github.dockerjava.api.exception.InternalServerErrorException: Get https://'_account-id_.dkr.ecr.eu-west-1.amazonaws.com/v2/executor-smild-4.x/manifests/4.3.6: no basic auth credentials

**Comment by xdexter** [comment]
Hello @deviscalio,

Do you configured a profile default and execute login (aws ecr get-login --region us-east-1) in ECR before pull imagem from ECR?

Best;

**Comment by deviscalio** [comment]
Hello @xdexter,

I'm able to pull and push images from jenkins machine if I use a shell in a job.
The problem is related to plugin. I configure a docker registry in Jenkins option, but it doesn't work.

![immagine](https://cloud.githubusercontent.com/assets/13203526/24352416/d2b41236-12e9-11e7-8e52-ead7a3cdba1b.png)

**Comment by xdexter** [comment]
Hello @deviscalio 
Hmm, i understand, i don't tried this options, sorry.

**Comment by ndeloof** [comment]
0.17 now uses docker-commons-plugin, and as such do support credentials set from https://wiki.jenkins.io/display/JENKINS/Amazon+ECR. Please reopen if this issue persists

**Comment by ben-gineer** [comment]
Hi @ndeloof 

I've just updated to version 1.0 but experiencing an error when trying to build a project:

```
Oct 16, 2017 9:48:47 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Asked to provision 1 slave(s) for: docker-tmp
Oct 16, 2017 9:48:47 PM com.nirima.jenkins.plugins.docker.DockerCloud provision
INFO: Will provision 'xxx.dkr.ecr.eu-west-1.amazonaws.com/jenkins-slave', for label: 'docker-tmp', in cloud: 'docker'
Oct 16, 2017 9:48:47 PM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
INFO: Provisioning 'xxx.dkr.ecr.eu-west-1.amazonaws.com/jenkins-slave' number '0' on 'docker'; Total containers: '0'
Oct 16, 2017 9:48:47 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning Image of xxx.dkr.ecr.eu-west-1.amazonaws.com/jenkins-slave from docker with 1 executors. Remaining excess workload: 0
Oct 16, 2017 9:48:47 PM io.jenkins.docker.DockerSlaveProvisioner pullImage
INFO: Pulling image 'xxx.dkr.ecr.eu-west-1.amazonaws.com/jenkins-slave:latest'. This may take awhile...
Oct 16, 2017 9:48:47 PM com.nirima.jenkins.plugins.docker.DockerCloud$1 call
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='docker-tmp', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@7c342ac9, remoteFsMapping='/opt/jenkins-data', remoteFs='/home/jenkins', instanceCap=4, mode=NORMAL, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@5f385a0a, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=xxx.dkr.ecr.eu-west-1.amazonaws.com/jenkins-slave}, removeVolumes=false, pullStrategy=PULL_ALWAYS, nodeProperties=[]}' for cloud='docker'
java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.DockerCloud.getAuthConfig(DockerCloud.java:778)
        at com.nirima.jenkins.plugins.docker.DockerCloud.setRegistryAuthentication(DockerCloud.java:749)
        at io.jenkins.docker.DockerSlaveProvisioner.pullImage(DockerSlaveProvisioner.java:91)
        at io.jenkins.docker.DockerSlaveProvisioner.runContainer(DockerSlaveProvisioner.java:55)
        at io.jenkins.docker.SSHDockerSlaveProvisioner.provision(SSHDockerSlaveProvisioner.java:63)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:397)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:80)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:298)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:295)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I am running:
Jenkins 2.85
Amazon ECR Plugin 1.6
Credentials Plugin 2.1.16
Docker API Plugin 3.0.13
Docker Commons Plugin 1.9
JClouds Plugin 2.14
Docker Version = 17.09.0-ce, API Version = 1.32

I'm using a valid set of AWS credentials for pushing/pulling to ECR. Any ideas what to check next?

Also, I note that the wiki page for the Docker Plugin has been significantly reduced recently. Is there a reason for this? Are the old instructions still valid?

Thanks
