### ISSUE TITLE
org.apache.http.conn.UnsupportedSchemeException: unix protocol is not supported

### ISSUE THREAD

**Issue by udit04** [jenkinsci/docker-plugin#486]
Why, uptil now, unix protocol is not supported even when it is recommended in the help icon in jenkins !

This works in older version but older version gets a lot more problems !

So please try to resolve this issue in the latest version i.e 0.16.2 !

**Comment by ndeloof** [comment]
I'm using unix socket without any issue, please (reopen and) give more details on your setup and the actual error.
