### ISSUE TITLE
Workspace specific volume

### ISSUE THREAD

**Issue by deyceg** [jenkinsci/docker-plugin#487]
Im running docker in docker (the recommended way) and I have a need for my build slave to run docker-compose, mounting my src directory into a container to install dependencies and run tests. This works fine locally.

However when running in jenkins the new container created by my build target is actually a sibling of the build slave so any volumes mounted are from the host.

My dumb solution was to have a named volume for the "workspace" that could be shared by all build slaves since its unlikely a job_id collision would occur. However this means I cannot remove volumes once the build has finished and would have to manually tidy up.

I figured a better solution would be to mount a named volume containing the job id such that the volume only exists for the duration of the build and would be torn down afterwards.

Is there a way to do this? Or is there a better approach I havent considered?

**Comment by ndeloof** [comment]
I'm not sure to understand your setup :-\
When you say you run docker-in-docker, does this mean every build agent is a DinD instance with dedicated docker daemon for the duration of a build ? In such case bind mounts from "host" should be ok and access the actual build agent workspace.

**Comment by ndeloof** [comment]
please reopen if you have some extra infos
