### ISSUE TITLE
install jdk every build

### ISSUE THREAD

**Issue by JM00oo** [jenkinsci/docker-plugin#489]
Hi, I have a question about installing jdk. In my case, I use Docker container as slave node, and I have run installing jdk in my dokcerfile, but in each build it will still install jdk again, i.e. ```Installing /home/jenkins/tools/hudson.model.JDK/JDK_8u121/jdk.sh```, can I skip this step? should I skip it? Thanks.

**Comment by ndeloof** [comment]
please join jenkins-users mailing list for such questions.

sounds like your jenkins master is configured with a JDK tool installer selected for your job, so as a result ... jenkins do install as requested.
