### ISSUE TITLE
Docker URL: Unix protocol is not supported

### ISSUE THREAD

**Issue by mikevan** [jenkinsci/docker-plugin#496]
When entering the suggested value for Docker URL (for localhost), "unix:///var/run/docker.sock", I get an error stating "unix protocol is not supported".  I've googled for a workaround, but there doesn't appear to be one. 

Could this kindly be fixed or perhaps a work-around stated?

**Comment by mister2d** [comment]
You have to open the TCP port to use instead of a unix socket.

https://docs.docker.com/engine/reference/commandline/dockerd/#bind-docker-to-another-hostport-or-a-unix-socket

**Comment by kumy** [comment]
There is an issue also in Jira since February :'(

https://issues.jenkins-ci.org/browse/JENKINS-42157

**Comment by kumy** [comment]
Isn't it the same as #495 and the related PR #494?

**Comment by ndeloof** [comment]
Should be fixed in 0.17
Please also double check for comparable issue before opening a new one
