### ISSUE TITLE
Tunnel connection throught in Docker JNLP launcher can not save

### ISSUE THREAD

**Issue by tiendungitd** [jenkinsci/docker-plugin#498]
I tried to use jnlp instead of ssh, and my Jenkins behind reverse proxy, so I have to config Tunnel connection like:
![image](https://user-images.githubusercontent.com/21011388/28264191-0d350bfe-6b14-11e7-8e02-edafd8efd8e9.png)
The issue is Jenkins can not save this config, this field got blank after I clicked "Save" button. Look in in system log I saw some warning

`WARNING: Father of com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@4be0343b and its getDescriptor() points to two different instances. Probably malplaced @Extension. See http://hudson.361315.n4.nabble.com/Help-Hint-needed-Post-build-action-doesn-t-stay-activated-td2308833.html
Jul 17, 2017 12:13:26 PM hudson.model.Descriptor verifyNewInstance
WARNING: Father of com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@7e957b15 and its getDescriptor() points to two different instances. Probably malplaced @Extension. See http://hudson.361315.n4.nabble.com/Help-Hint-needed-Post-build-action-doesn-t-stay-activated-td2308833.html
Jul 17, 2017 12:13:26 PM hudson.model.Descriptor verifyNewInstance
WARNING: Father of com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@2f62d3b4 and its getDescriptor() points to two different instances. Probably malplaced @Extension. See http://hudson.361315.n4.nabble.com/Help-Hint-needed-Post-build-action-doesn-t-stay-activated-td2308833.html
Jul 17, 2017 12:13:26 PM hudson.model.Descriptor verifyNewInstance
WARNING: Father of com.nirima.jenkins.plugins.docker.launcher.DockerComputerJNLPLauncher@1848ae88 and its getDescriptor() points to two different instances. Probably malplaced @Extension. See http://hudson.361315.n4.nabble.com/Help-Hint-needed-Post-build-action-doesn-t-stay-activated-td2308833.html`

**Comment by ndeloof** [comment]
fixed by https://github.com/jenkinsci/docker-plugin/commit/e61dee013009f903ea9131ecad321fa8cd173a4f#diff-7199370089b8fd86e9cbb4501279fae7L8
