### ISSUE TITLE
Failed to run a build in docker if the jenkins is running inside a docker container

### ISSUE THREAD

**Issue by zhaoyi0113** [jenkinsci/docker-plugin#499]
I have setup Jenkins inside a Docker container. And my host is CoreOS.  I created a job to use docker plugin to run the build inside a docker container but it failed to launch the build. 

The Jenkins image is from `jenkins:latest` and I added below configuration in order to map the host socket: `/var/run/docker.sock:/var/run/docker.sock:rw`.

I got below error from system log when I try to launch the project build.

> Failure to create Docker Slave
> java.io.IOException: Failed to connect to docker API
> 	at it.dockins.dockerslaves.drivers.CliDockerDriver.serverVersion(CliDockerDriver.java:453)
> 	at it.dockins.dockerslaves.drivers.CliDockerDriver.<init>(CliDockerDriver.java:78)
> 	at it.dockins.dockerslaves.drivers.PlainDockerAPIDockerDriverFactory.forJob(PlainDockerAPIDockerDriverFactory.java:43)
> 	at it.dockins.dockerslaves.DefaultDockerProvisionerFactory.createProvisionerForClassicJob(DefaultDockerProvisionerFactory.java:95)
> 	at it.dockins.dockerslaves.DockerSlaves.createStandardJobProvisionerFactory(DockerSlaves.java:101)
> 	at it.dockins.dockerslaves.ProvisionQueueListener.prepareExecutorFor(ProvisionQueueListener.java:93)
> 	at it.dockins.dockerslaves.ProvisionQueueListener.onEnterBuildable(ProvisionQueueListener.java:62)
> 	at hudson.model.Queue$BuildableItem.enter(Queue.java:2582)
> 	at hudson.model.Queue$BuildableRunnable.run(Queue.java:2886)
> 	at hudson.model.Queue.maintain(Queue.java:1515)
> 	at hudson.model.Queue$1.call(Queue.java:321)
> 	at hudson.model.Queue$1.call(Queue.java:318)
> 	at jenkins.util.AtmostOneTaskExecutor$1.call(AtmostOneTaskExecutor.java:108)
> 	at jenkins.util.AtmostOneTaskExecutor$1.call(AtmostOneTaskExecutor.java:98)
> 	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
> 	at java.lang.Thread.run(Thread.java:748)
> 

How can I make the Jenkins work with docker plugin if Jenkins is running inside a docker?

**Comment by wenerme** [comment]
Try `docker -H unix:///var/run/docker.sock info`, this may fail, because jenkins run as jenkins user, docker mount as root.

1. Try add user to group
```
USER root
# Works for -v /var/run/docker.sock:/var/run/docker.sock
RUN adduser jenkins users
USER jenkins
```

2. Use a docker in docker with compose, link dind to jenkins, set DOCKER_HOST env

**Comment by zhaoyi0113** [comment]
Add a jenkins user doesn't seem to work. I have to change the directory permission like this:

`RUN chmod 777 /home/jenkins`

**Comment by satyamkapoor** [comment]
Hi @zhaoyi0113, I was trying to achieve the same. Manage to run docker inside jenkins but somehow the DNS of docker inside jenkins isn't set and I've tried alot but unable to make it work :( From what I've been reading, docker should be using Google's open dns servers but not the case with me :/ Did you face such an issue?
