### ISSUE TITLE
Kill a process in the docker container will make the container exit with 137 code.

### ISSUE THREAD

**Issue by zhaoyi0113** [jenkinsci/docker-plugin#501]
I use this plugin to launch a build job. In the job, I create a few test cases and each of them will launch a internal process for testing. After each test case finished, it will kill that process. The internal process is launched by this command `mongod --dbpath /home/jenkins/.jenkins/data/db --logpath /home/jenkins/.jenkins/data/mongod.log --port 27017 --logappend --fork`. 

I found that if this process is killed the container will exit with 137 code. However, it works fine if I launch the container manually and follow the same process to do the build. So I think this is caused by the launcher command used to run the container. I wonder which command this plugin use to run a job container. Whether I can change the launch command in order to fix this issue?

**Comment by ndeloof** [comment]
it sounds like your kill command to also kill the remoting agent. Please give more details on your kill mechanism

**Comment by ndeloof** [comment]
please reopen as you provide more infos on this issue
