### ISSUE TITLE
Docker-Plugin takes a long time to figure out and start containers with matching labels

### ISSUE THREAD

**Issue by MichaelGreco** [jenkinsci/docker-plugin#503]
I have 5 nodes with the same label. Jenkins always tries to use the 1st node ... and then while that 1st job is running more jobs come in but they all sit there saying "node_0  is offline" for minutes. 

At some point the plugin figures out there's another free node that can service the same label but something isn't right cause the plugin is taking a lot time to realize there are other nodes that aren't doing anything that can service the same label.  

Is there something to tune this behavior ?

**Comment by ndeloof** [comment]
should be fixed if we use https://github.com/jenkinsci/one-shot-executor-plugin/blob/master/src/main/java/org/jenkinsci/plugins/oneshot/OneShotProvisionerStrategy.java

**Comment by VQuery** [comment]
@MichaelGreco  did you face this issue? 
 https://github.com/jenkinsci/docker-plugin/issues/511

**Comment by ndeloof** [comment]
released with 0.17
