### ISSUE TITLE
variable not replaced in Docker push step

### ISSUE THREAD

**Issue by mrmunch** [jenkinsci/docker-plugin#504]
I'm having two variables in my Jenkins job: `THE_IMAGE` as the image name and `THE_TAG` as the tag-name for the image:
![image](https://user-images.githubusercontent.com/12833236/29362948-421625ce-828e-11e7-8457-b3b88162c3ec.png)
When I use both within the `push image` step, **$THE_IMAGE** is successfully replaced, but **$THE_TAG** is not.
For example, setting **THE_IMAGE=myimage** and **THE_TAG=v1.2.3** , I can see in the log output that docker tries to push an image called `myimage:$THE_TAG`

**Comment by easylite376** [comment]
correct me if i'm wrong, but don't you write ${THE_IMAGE} and ${THE_TAG} to get the environment variables interpreted?

**Comment by mrmunch** [comment]
@easylite376 I tried both.

**Comment by ndeloof** [comment]
duplicates https://github.com/jenkinsci/docker-plugin/issues/466
