### ISSUE TITLE
multi docker cloud with same label doesn't work as expected

### ISSUE THREAD

**Issue by visibilityspots** [jenkinsci/docker-plugin#516]
Hi,

we have configured 2 physical docker nodes in jenkins as docker clouds both with a container cap of 10 and having the same label.

I however discovered that when the first physical node reaches this max capacity of 10 containers the job doesn't automatically gets executed on the 2nd docker cloud..

```
Oct 06, 2017 9:56:42 AM com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
testdocker_jenkins | INFO: Not Provisioning 'internal.nexus.docker.repo/organisation/jenkins-build-slave:latest'; Server 'testdocker' full with '10' container(s)
testdocker_jenkins | [10/06/17 09:56:46] SSH Launch of testdocker-f8efdf24a5e8 on X.X.X.X completed in 3,507 ms
testdocker_jenkins | Oct 06, 2017 9:56:48 AM com.nirima.jenkins.plugins.docker.DockerSlave _terminate
testdocker_jenkins | INFO: Disconnected computer
```

Is that normal behaviour and did I expected too much or did I overlooked some setting which currently blocks this behaviour?

**Comment by ndeloof** [comment]
You should not rely on distinct clouds for such a setup, but run docker-swarm  "standalone" (https://github.com/docker/swarm) in front of them.

**Comment by visibilityspots** [comment]
The swarm standalone setup does indeed exactly what I was looking for! Thanks for the pointer already on the wiki https://wiki.jenkins.io/display/JENKINS/Docker+Plugin!
