### ISSUE TITLE
Cannot enter server credentials in Configure System area

### ISSUE THREAD

**Issue by mtdeguzis** [jenkinsci/docker-plugin#522]
Please don't use the issue tracker to ask questions, join jenkins-users mailing list.

If you get some troubles with docker-plugin, please report
 - [x] docker-plugin version you use
    0.18
 - [x] jenkins version you use
   2.73

When I got to the "Cloud" section and add a new entry, I see server credentials, but none of my plain text user/password entries appear. When I chose to add to the Jenkins domain store, no added entry appears

![image](https://user-images.githubusercontent.com/27829577/31522408-a85b8c06-af7b-11e7-9cab-0589d38f470f.png)

Credentials setup:

![image](https://user-images.githubusercontent.com/27829577/31522419-b7933084-af7b-11e7-8070-c30f0016480c.png)

Do I need a specific kind here?

![image](https://user-images.githubusercontent.com/27829577/31522438-cb8dcc2a-af7b-11e7-95ad-0dca3c715b13.png)

**Comment by ndeloof** [comment]
Docker API authentication is based on TLS "Host Certificate" credentials. 
What's your docker infrastructure so you rely on username/password ?

**Comment by mtdeguzis** [comment]
We currently have a docker host that requires use of sudo, and as I am learning this here, is only exposed to the unix socket. I realize I must get the TCP socket exposed, but I was confused what credentials would be acceptable based on this behavior. Is there better documentation on any of this beyond the plugin page? The wiki is bare.

I am going to work on getting the TLSVERIFY setup on the host.

**Comment by ndeloof** [comment]
there's no relation with `sudo` here. docker-plugin does not use a system command but API call. I assume your dockerhost is the node running jenkins master, and system user running Jenkins isn't member of the `docker` group so can't access `/var/run/docker.sock`, isn't it ?

Then, jenkins won't indeed be able to run docker commands. Credentials here are the TLS keys required to access a (potentially remote) DockerHost tcp API. From your description it sounds you'll need to enable this.
