### ISSUE TITLE
Obvious NPE case in DockerSlaveProvisioner

### ISSUE THREAD

**Issue by cal101** [jenkinsci/docker-plugin#523]
As of now:

docker-plugin/docker-plugin/src/main/java/io/jenkins/docker/DockerSlaveProvisioner.java

In method pullImage the code reads:
```
            if (registry == null) {
                DockerRegistryToken token = registry.getToken(null);
```

**Comment by ndeloof** [comment]
thanks for reporting this, has been fixed in the meantime
