### ISSUE TITLE
Exception thrown with docker based agent msg: getAddressForSSHD

### ISSUE THREAD

**Issue by pteichner** [jenkinsci/docker-plugin#525]
If you get some troubles with docker-plugin, please report
 - [ ] docker-plugin: 0.18
 - [ ] jenkins version you use: 2.73.2
 - [ ] docker engine version you use: 1.12.6
 - [ ] stack trace / logs / any technical details that could help diagnose this issue

The image that was build (on the docker server) it not able to provision properly following the upgrade.

```
SEVERE: Error in provisioning; template='DockerTemplate{configVersion=2, labelString='rhel5-docker-python', launcher=com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher@19f15822, remoteFsMapping='/var/lib/jenkins', remoteFs='/home/jenkins', instanceCap=4, mode=EXCLUSIVE, retentionStrategy=com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy@34c8cdf, numExecutors=1, dockerTemplateBase=DockerTemplateBase{image=testdocker.uex-repo-test.hq.k.grp/cd/nagra/centos-5-python-jenkinsagent:latest}, removeVolumes=true, pullStrategy=PULL_NEVER, nodeProperties=[]}' for cloud='build-docker-02'
java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getAddressForSSHD(DockerComputerSSHLauncher.java:60)
        at io.jenkins.docker.SSHDockerSlaveProvisioner.provision(SSHDockerSlaveProvisioner.java:75)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:397)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:72)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:290)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:287)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ndeloof** [comment]
Line number suggests `networkSettings.getPorts()` returned null, which is weird.

**Comment by pteichner** [comment]
I guess #528 explains why pullStrategy=PULL_NEVER is set to this way.

**Comment by ndeloof** [comment]
Can you please capture `docker inspect` for such a container ?

**Comment by pteichner** [comment]
```json
[
    {
        "Id": "0e4a4c4f8db4787679086c6658cfe03b669c2ea6634ac954c3f211a57e64ad6a",
        "Created": "2017-10-17T16:16:07.710945593Z",
        "Path": "/usr/sbin/sshd",
        "Args": [
            "-D",
            "-p",
            "22",
            "-o",
            "AuthorizedKeysCommand /root/authorized_key",
            "-o",
            "AuthorizedKeysCommandUser root"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 22526,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-10-17T16:16:08.357451583Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:7431c74e58884b1a3edbb0fb6e5e4d365810fc8f59730505defeb248fd6660dd",
        "ResolvConfPath": "/var/lib/docker/containers/0e4a4c4f8db4787679086c6658cfe03b669c2ea6634ac954c3f211a57e64ad6a/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/0e4a4c4f8db4787679086c6658cfe03b669c2ea6634ac954c3f211a57e64ad6a/hostname",
        "HostsPath": "/var/lib/docker/containers/0e4a4c4f8db4787679086c6658cfe03b669c2ea6634ac954c3f211a57e64ad6a/hosts",
        "LogPath": "/var/lib/docker/containers/0e4a4c4f8db4787679086c6658cfe03b669c2ea6634ac954c3f211a57e64ad6a/0e4a4c4f8db4787679086c6658cfe03b669c2ea6634ac954c3f211a57e64ad6a-json.log",
        "Name": "/nauseous_wescoff",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "system_u:object_r:svirt_lxc_file_t:s0:c77,c302",
        "ProcessLabel": "system_u:system_r:svirt_lxc_net_t:s0:c77,c302",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "22/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": ""
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/lib/docker/overlay/a41ea8d43d7e198a87fe3aca145078e5c4f2183a03e91e20a714aed6af46aa7d/root",
                "MergedDir": "/var/lib/docker/overlay/75ada5169c9670284384fc84b65cae601cc81a19fef28aa8ce51f44fb2bbe46a/merged",
                "UpperDir": "/var/lib/docker/overlay/75ada5169c9670284384fc84b65cae601cc81a19fef28aa8ce51f44fb2bbe46a/upper",
                "WorkDir": "/var/lib/docker/overlay/75ada5169c9670284384fc84b65cae601cc81a19fef28aa8ce51f44fb2bbe46a/work"
            }
        },
        "Mounts": [],
        "Config": {
            "Hostname": "0e4a4c4f8db4",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "22/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TZ=GMT",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/usr/sbin/sshd",
                "-D",
                "-p",
                "22",
                "-o",
                "AuthorizedKeysCommand /root/authorized_key",
                "-o",
                "AuthorizedKeysCommandUser root"
            ],
            "Image": "testdocker.uex-repo-test.hq.k.grp/cd/nagra/centos-5-python-jenkinsagent:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "JenkinsId": "877d5d81a023546701390c7c2457e384"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "f8f96128e699915039a1a972d5f9ce4c02e8b55520c0db9dbaaca3117648acfe",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "22/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "33385"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/f8f96128e699",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "89f76045b04f96e4ec8701828707939a647cb796fc6c84a48bcbb551565be64b",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "e3c6b72f8863870d5a98af93bba58b2fed9473303879fca89da02ebd2bfbc66b",
                    "EndpointID": "89f76045b04f96e4ec8701828707939a647cb796fc6c84a48bcbb551565be64b",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]

```

**Comment by ndeloof** [comment]
so NetworkSettings. Ports is well set (at least in json), that's very strange.
I'll add some protective null check here, but wonder what could be the root cause. This would only avoid an ugly NPE but would prevent the plugin to detect assigned port and connect to agent.

**Comment by pteichner** [comment]
I've checked and I can definitely connect when I manually provision the container from the jenkins master

**Comment by ndeloof** [comment]
issue here is not to connect but to detect the port being used for ssh. For some unknown reason docker-java don't report network settings for your container. Do you always get this exact same stacktrace trying to connect ?

**Comment by pteichner** [comment]
I think so, I was on 0.15.1 release I think prior and upgraded to 0.18 that's when the problem started. Not sure if it's the docker library plugin or this one that's responsible for decoding the ja on object but somehow it's not working. I could try and change the cloud to be ip based rather than host name

**Comment by ndeloof** [comment]
ip or hostname won't change anything here, you don't get the payload parsed correctly it seems. 
would you agree to install a custom diagnostic version of docker-plugin to help me fix this ?

**Comment by pteichner** [comment]
update
 - [ ] docker-plugin: 1.0.1
 - [ ] jenkins version you use: 3.0.14
 - [ ] docker engine version you use: 1.12.6
 - [ ] stack trace / logs / any technical details that could help diagnose this issue
```
[INFO] Working directory: /var/lib/jenkins/scm-sync-configuration/checkoutConfiguration
Oct 18, 2017 1:34:13 PM hudson.slaves.NodeProvisioner$2 run
WARNING: Unexpected exception encountered while provisioning agent Image of testdocker.uex-repo-test.hq.k.grp/cd/nagra/centos-5-python-jenkinsagent:latest
java.lang.NullPointerException
        at com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher.getAddressForSSHD(DockerComputerSSHLauncher.java:67)
        at io.jenkins.docker.SSHDockerSlaveProvisioner.provision(SSHDockerSlaveProvisioner.java:76)
        at com.nirima.jenkins.plugins.docker.DockerCloud.provisionWithWait(DockerCloud.java:392)
        at com.nirima.jenkins.plugins.docker.DockerCloud.access$000(DockerCloud.java:75)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:293)
        at com.nirima.jenkins.plugins.docker.DockerCloud$1.call(DockerCloud.java:290)
        at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by ndeloof** [comment]
right, same cause: https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-parent-1.0.1/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/launcher/DockerComputerSSHLauncher.java#L67
 networkSettings.getPorts from container inspect is null, should be empty at worst.

I've added some diagnostic code upstream, logging the whole inspect response in DEBUG

**Comment by pteichner** [comment]
do you want me to take a build?

**Comment by ndeloof** [comment]
sure, you can use [last artifact build from CI](https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/lastSuccessfulBuild/artifact/)
you'll need to create a log recorder for com.nirima.jenkins.plugins.docker.launcher.DockerComputerSSHLauncher (see https://wiki.jenkins.io/display/JENKINS/Logging) to include DEBUG logs,
you'll then get the InspectResponse object logged and we can get more details on what ge reported by docker-java client

**Comment by pteichner** [comment]
So I've installed the plugin - tried both 
- build #41 https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/41/ 
- build #46 https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/46/

and I end up with no Cloud instances (see image) plus the button is not working either ![image](https://user-images.githubusercontent.com/28305157/31822748-af1cae4a-b5a1-11e7-9490-1ee3d238c070.png)

**Comment by pteichner** [comment]
Well in fact I returned to 1.0.1 and now I can't add any Cloud Docker config at all :(

**Comment by ndeloof** [comment]
please check the jenkins start log for failure loading any component

**Comment by pteichner** [comment]
It did load the component but screwed up the config file - I've restored the config file now. At this stage I'm a bit lost as to how to help next but it would be very good to have this functionality back as some of our builds rely on docker containers

**Comment by ndeloof** [comment]
data migration between snapshot builds might be unstable, it's only guaranteed (at least, tested) from released versions.
https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/50/ is the build for 1.0.2 that I've tested to load configuration from previous releases.
still, DockerComputerSSHLauncher logs will be required to understand what's wrong in your installation.

**Comment by pteichner** [comment]
I've used https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/50/ and all reference to cloud disappeared from the config.xml file. 
- There was a file com.nirima.jenkins.plugins.docker.DockerPluginConfiguration.xml which had a reference to a Docker registry I removed and restarted Jenkins.
- I'm seeing nothing in the created logger instance 
- I'm Still I'm unable to create new "Cloud" Docker instance in the config and the existing ones have vanished. 

Is there anything else I can do please?

**Comment by ndeloof** [comment]
@pteichner can we follow up on private ? I'll need some more details on your installation that you might not want to publish here
mailto :  nicolas.deloof_at_gmail.com

**Comment by pteichner** [comment]
email sent, thanks

**Comment by pteichner** [comment]
After the installation of the latest 1.0.x build recommended in #542 I can no longer reproduce the problem. The container is created and the build is successfully running inside.

**Comment by pteichner** [comment]
However this appears in the log file now

```bash
Oct 25, 2017 3:15:46 PM hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager getTrileadSupport
WARNING: Could not create Trilead support class. Using legacy Trilead features
java.lang.ClassNotFoundException: hudson.plugins.sshslaves.verifiers.JenkinsTrilead9VersionSupport
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:560)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager.createVersion9Instance(TrileadVersionSupportManager.java:51)
        at hudson.plugins.sshslaves.verifiers.TrileadVersionSupportManager.getTrileadSupport(TrileadVersionSupportManager.java:32)
        at hudson.plugins.sshslaves.verifiers.SshHostKeyVerificationStrategy.getPreferredKeyAlgorithms(SshHostKeyVerificationStrategy.java:68)
        at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:797)
        at hudson.plugins.sshslaves.SSHLauncher$2.call(SSHLauncher.java:793)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by axgrap** [comment]
I am seeing the same issue as above "I'm Still I'm unable to create new "Cloud" Docker instance in the config and the existing ones have vanished.".  I get a js error from an anonymous function (error on " `var table = master.parentNode;` `Uncaught TypeError: Cannot read property 'parentNode' of null`): 
`
      (function() {
        
        var master = document.getElementById('id2760');
        var table = master.parentNode;
        table.removeChild(master);
      
        makeButton($('id2760button'), function (e) {
          
          var name = $('id2760text').value;
          if(name=="") {
            alert("Please enter a user name or a group name");
            return;
          }
          if(findElementsBySelector(table,"TR").find(function(n){return n.getAttribute("name")=='['+name+']';})!=null) {
            alert("Entry for '"+name+"' already exists");
            return;
          }

          if(document.importNode!=null)
            copy = document.importNode(master,true);
          else
            copy = master.cloneNode(true); 
          copy.removeAttribute("id");
          copy.removeAttribute("style");
          copy.firstChild.innerHTML = name;
          copy.setAttribute("name",'['+name+']');
          findElementsBySelector(copy, ".stop img").each(function(item) {
            item.setAttribute("title", item.getAttribute("title").replace("__SID__", name));
          });
          findElementsBySelector(copy, "input[type=checkbox]").each(function(item) {
            item.setAttribute("title", item.getAttribute("title").replace("__SID__", name));
          });
          table.appendChild(copy);
          Behaviour.applySubtree(findAncestor(table,"TABLE"),true);
        });
      })();

      Behaviour.specify("#org-jenkinsci-plugins-matrixauth-AuthorizationMatrixNodeProperty TD.stop A.remove", 'GlobalMatrixAuthorizationStrategy', 0, function(e) {
          e.onclick = function() {
            var tr = findAncestor(this,"TR");
            tr.parentNode.removeChild(tr);
            return false;
          }
          e = null; 
        });
      Behaviour.specify("#org-jenkinsci-plugins-matrixauth-AuthorizationMatrixNodeProperty TD.stop A.selectall", 'GlobalMatrixAuthorizationStrategy', 0, function(e) {
          e.onclick = function() {
            var tr = findAncestor(this,"TR");
            var inputs = tr.getElementsByTagName("INPUT");
            for(var i=0; i<inputs.length; i++){
                if(inputs[i].type == "checkbox") inputs[i].checked = true;
            }
            return false;
          };
          e = null; 
        });
        Behaviour.specify("#org-jenkinsci-plugins-matrixauth-AuthorizationMatrixNodeProperty TD.stop A.unselectall", 'GlobalMatrixAuthorizationStrategy', 0, function(e) {
          e.onclick = function() {
            var tr = findAncestor(this,"TR");
            var inputs = tr.getElementsByTagName("INPUT");
            for(var i=0; i<inputs.length; i++){
                if(inputs[i].type == "checkbox") inputs[i].checked = false;
            }
            return false;
          };
          e = null; 
        });
        
        
        Behaviour.specify("#org-jenkinsci-plugins-matrixauth-AuthorizationMatrixNodeProperty TR.permission-row", 'GlobalMatrixAuthorizationStrategy', 0, function(e) {
          FormChecker.delayedCheck("/jenkins/descriptorByName/org.jenkinsci.plugins.matrixauth.AuthorizationMatrixNodeProperty/checkName?value="+encodeURIComponent(e.getAttribute("name")),"GET",e.firstChild);
        });
    `

**Comment by ndeloof** [comment]
please open a separate issue for this
