### ISSUE TITLE
Can't connect JNLP salve on jenkins with authentication

### ISSUE THREAD

**Issue by gustafg** [jenkinsci/docker-plugin#526]
I'm attempting to launch my containers using jnlp but I am unable to do so because the plugin do not provide any -secret to slave.jar. I notice there are 2 commits lately removing references to getJnlpMac() and COMPUTER_SECRET stating that this is obsolete but the commit comments leave to me no clue as to what replaced it.

**Comment by ndeloof** [comment]
You don't need to, [JNLPDockerSlaveProvisioner](https://github.com/jenkinsci/docker-plugin/blob/master/docker-plugin/src/main/java/io/jenkins/docker/JNLPDockerSlaveProvisioner.java#L85) takes care of setting up the container to run JNLP launcher with adequate command line

**Comment by gustafg** [comment]
Yes, and that code in my environment becomes something like:
```jenkins-slave java -jar /home/jenkins/remoting-3.12.jar -jnlpUrl https://jenkins//computer/c-5f6e6b94d6bcd3//slave-agent.jnlp```

Which if I run it manually return a 403 because the client is not authenticated. I've noticed Docker mount /home/jenkins/.jenkins and /home/jenkins/agent, not sure how that is supposed to work are the credentials supposed to come via those directories somehow?

**Comment by gustafg** [comment]
Thanks for quick response. I only wished I asked earlier. I will make some kind of work around in my environment for now.

**Comment by ndeloof** [comment]
I could have a fix quickly. This is a major regression.

**Comment by gustafg** [comment]
For me it is not a regression. I'm trying to set it up now. I just wanted to do it with JNLP + authentication but I could not figure out how. Now I know it is not possible (with the release I am running) so I changed our setup to Matrix Based Security and let agent's connect anonomously. It worked well. I am not able to upgrade Jenkins so often anyways so for me this would be no help.

Again, much thanks for quick response!
