### ISSUE TITLE
Allow to publish to multiple registries

### ISSUE THREAD

**Issue by ThStock** [jenkinsci/docker-plugin#527]
In 0.16.2 it was possible to push images to multiple registries.

Do you have plans to enable this feature again?

![image](https://user-images.githubusercontent.com/4543919/31655246-97e0db5a-b328-11e7-8e66-0f1576145cd3.png)

**Comment by ndeloof** [comment]
Doing this makes it harder to configure push credentials
Simpler to just duplicate this build step, or will need a more complex UI

**Comment by ThStock** [comment]
Okay this helps, but I think it could be helpfull to move (docker registry, registry credentials) to jenkins configuration page.

All my docker builds that pushes to e.g. "public.company" uses the same credentials.

**Comment by ndeloof** [comment]
Doing this you loose the scoping capabilities for credentials. Credentials typically can be configured on a per folder or per user basis. Jenkins is not always a "single user" deployment.
Same applies to docker host selection by the way, so far I've left the "by cloud name" selection but this creates a credential scope bypass. As a team using a large jenkins instance you might have distinct credentials to access the same docker infrastructure to run your docker builds (with some restrictions)

**Comment by ThStock** [comment]
ok, it is a design decision ... feel free to close this issue 😃
