### ISSUE TITLE
No Containers being spawned

### ISSUE THREAD

**Issue by djl197** [jenkinsci/docker-plugin#53]
All,

Just started to play with this.
I have a Jenkins Master with the plugin installed.
I set it up to point at another machine as a docker host.
I run Test Connection and it reports version 1.0.1.

I setup a cloud with the ID set to:
localhost:5000/jenkins_slave

On the remote machine - This can be seen (docker images)
I setup the access, home dir etc and limit it to 8 instances.

I have a single slave setup, and I was expecting that any subsequent jobs would trigger the creation of a docker container.
However this is not happening.

Under the 'System Configuration->Docker' it shows the image is available with no running containers.

I have enabled debug (System Logs) 
com.nirima.jenkins.plugins.docker Set to ALL

But this just confirms connections are made:
Jul 04, 2014 11:32:45 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud connect
Building connection to docker host Grass URL http://grass.DOMAIN:4243
Jul 04, 2014 11:32:46 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud connect
Building connection to docker host Grass URL http://grass.DOMAIN:4243
Jul 04, 2014 11:32:46 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud connect
Building connection to docker host Grass URL http://grass.DOMAIN:4243

Any ideas on why nothing much seems to be happening - and why the debug is not very verbose?

**Comment by KostyaSha** [comment]
Is it still actual?

**Comment by KostyaSha** [comment]
Closed by mistake :smiley:  but feel free to reopen if issue is still valid
