### ISSUE TITLE
disable SSH key management option is not saved

### ISSUE THREAD

**Issue by vrockai** [jenkinsci/docker-plugin#530]
The "disable SSH key management" remains unchecked after these steps

1. Checking the "disable SSH key management" option
2. Save (or apply)
3. Refresh the page

If you get some troubles with docker-plugin, please report
 - [x] docker-plugin 1.0.1
 - [x] jenkins version 2.73.2
 - [x] docker version 17.05.0-ce 
 - [x] no logs

**Comment by ndeloof** [comment]
stapler databinding 😱 ...

thanks for reporting this issue

**Comment by vrockai** [comment]
I believe there is still something wrong when a custom command is provided (agent launch will fail but the sshd is running and I can login manually). For some reason, after recent updates, the agent launch works only if the "default"  _Docker Command_ is used.

In short, letting the _Docker Command_ empty works, using `/usr/sbin/sshd -D` as the value doesn't.

**Comment by ndeloof** [comment]
@vrockai see help tip for the "inject SSH" option. 
If you override sshd command line then this option will just not work.

**Comment by vrockai** [comment]
oh right, i see now, thanks! my only problem with going the preferred "key" way is that i'm getting always logged in as a root, not jenkins, to the slave machine. is there any tutorial "for dummies" how to set it up somewhere, I'm having troubles finding all the relevant information.

btw, since you already fixed the issue, this PR can be closed.

**Comment by alonbl** [comment]
I am trying to use this feature which should be very nice. However, it does not work. I believe for some reason it hardcode to use "root" user? 

```
        return new BasicSSHUserPrivateKey(CredentialsScope.SYSTEM, "InstanceIdentity", "root",
                new BasicSSHUserPrivateKey.DirectEntryPrivateKeySource(pem), null,
                "private key for docker ssh agent");
```

I expect the user to be configurable... or if ssh credentials are provided to use the credentials.

Thanks!

**Comment by ndeloof** [comment]
@alonbl implemented by 12b8f54b269a6ae1989176f6d887787cdbaae51f

**Comment by alonbl** [comment]
Thanks!

May I suggest a different approach?

If credentials are provided use credentials otherwise use the instance identify.
This removes the need to explicitly specify a user and enable to choose the credentials using standard jenkins process.

The toggle of key management should be used only for enable/disable the authorized keys command mechanism.

The authorized keys command should only allow the user provided in credentials, you can do this by providing %u (which is default) parameter to the script and generate the script with the user of credentials replacing @USER@ with the actual user. The script will return the ssh public key only if [ "$1" = "@USER@" ], this will avoid hacking the system using root.

What do you think?

**Comment by ndeloof** [comment]
@alonbl we indeed could add this as some special "empty" credential entry for SSH credentials selection, would anyway still need some way to set user for injected key ssh authentication.
My plan is to fully revisit the UI for this section.

We can indeed make ssh auth stronger by forcing injected key to only match configured user, anyway being root inside a container doesn't have the same impact as being root on host (especially if you enabled user namespace)

**Comment by alonbl** [comment]
@ndeloof : why do you need to add a special "empty" credentials? you already have the credentials in the user interface, the user can select ssh private key to use... what is missing?

See the following code:

```java
        if (!launcher.isUseSSHkey()) {
            return launcher.getSshConnector().getCredentials();
        }

        InstanceIdentity id = InstanceIdentity.get();
        String pem = PEMEncodable.create(id.getPrivate()).encode();

        // TODO find how to inject authorized_key owned by a (configurable) user "jenkins"
        return new BasicSSHUserPrivateKey(CredentialsScope.SYSTEM, "InstanceIdentity", launcher.getUser(),
                new BasicSSHUserPrivateKey.DirectEntryPrivateKeySource(pem), null,
"private key for docker ssh agent");
```

replace with to something with:

```java
        creds = launcher.getSshConnector().getCredentials();

        if (creds == null && launcher.isUseSSHkey()) {
            InstanceIdentity id = InstanceIdentity.get();
            String pem = PEMEncodable.create(id.getPrivate()).encode();

            // TODO find how to inject authorized_key owned by a (configurable) user "jenkins"
            creds = new BasicSSHUserPrivateKey(CredentialsScope.SYSTEM, "InstanceIdentity", launcher.getUser(),
                new BasicSSHUserPrivateKey.DirectEntryPrivateKeySource(pem), null,
"private key for docker ssh agent");
        }
        return creds;
```

I disagree about the root access, I believe it should be avoided when possible... I can workout a patch to generate nicer command if I get this working... however, I think the above is something beyond me and important :)

**Comment by ndeloof** [comment]
credentials selection will always have a value, so I can't detect that user is asking for ssh key injection based on credentials being selected or not - "no selection" is only possible if no credentials exists on the master.

I agree about root as not being a nice option, this is just the sole user we can ensure exists on any docker image. Ability to override this default user anyway avoids this bad practice.

**Comment by alonbl** [comment]
> credentials selection will always have a value

hmmm... so maybe add a checkbox if to use the credentials or  not? this will enable to choose explicit trusted credentials including a user.

**Comment by vrockai** [comment]
from the UX perspective it's very confusing to have credentials selected and ignored.

**Comment by ndeloof** [comment]
@vrockai totally agree, so my plan to revisit the UI and have an explicit selection for the ssh key strategy to use. Initial design was based on re-using SSHConnector, so not so much flexibility

**Comment by alonbl** [comment]
the current phrase of:

```
| disable SSH key management |  
```

to actually enable a feature is even more confusing :)
I only understood that this actually enables this feature while reading the code.

I think you should always use the credentials and not the identifier... and have a simple configuration.
the mechanism should control only the use of authorized keys feature at the container... this will keep feature nice, simple and integrated within the jenkins concepts without confusion...

```
[X] Use OpenSSH Authorized Keys Command
```

**Comment by alonbl** [comment]
Maybe even:

```
[X] Use OpenSSH Authorized Keys Command
( ) Use Jenkins Identified key
     Public key: ____________________________________________________
(o) Use SSH credentials
  _______________V
```

**Comment by ndeloof** [comment]
the title indeed is wrong and confusing (sorry for that)
UI refactoring in progress ... ⌨️

**Comment by ndeloof** [comment]
see 08110044284c01f97907b4f5a274afc0ede5dd00

**Comment by alonbl** [comment]
thanks! I still think that explicit credentials are better than the identify but ok, working after minor fix #537.

**Comment by alonbl** [comment]
One last question... I see the following warning:

```
SSH Host Key Verifiers are not configured for all SSH slaves on this Jenkins instance. This could leave these slaves open to man-in-the-middle attacks. Update your slave configuration to resolve this.
```

The strategy of known hosts is gone, can connection be secured?

**Comment by alonbl** [comment]
and... finally #538 to make it secure.
