### ISSUE TITLE
Port Bindings are discarded, but Bind All works

### ISSUE THREAD

**Issue by gamma** [jenkinsci/docker-plugin#532]
Please don't use the issue tracker to ask questions, join jenkins-users mailing list.

If you get some troubles with docker-plugin, please report
 - docker-plugin version you use: 1.0.0
 - jenkins version you use: 2.85
 - docker engine version you use:
  - Version = swarm/1.2.6, API Version = 1.22
  - Version = 17.05.0-ce, API Version = 1.29

Extra port bindings do not work. Only port 22 will be opened, except for the Bind All Ports option.

**Comment by hypnoce** [comment]
Still not working with docker-plugin 1.0.3

**Comment by hypnoce** [comment]
So, I think this is the issue : 
* in [DockerCloud.java#provisionWithTemplate](https://github.com/jenkinsci/docker-plugin/blob/89e60667da297ad8e9a3d484820f5c65f0a4b84e/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L380) we fill the container config.
* in [DockerTemplateBase.java#fillContainerConfig](https://github.com/jenkinsci/docker-plugin/blob/0ef4cfcecb62b999e7bbd2b2ca5ac82cd00ce650/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java#L382) we set the bindings
* Back to [DockerCloud.java#provisionWithTemplate](https://github.com/jenkinsci/docker-plugin/blob/89e60667da297ad8e9a3d484820f5c65f0a4b84e/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L382) we call the beforeContainerStarted.
* In [DockerComputerSSHConnector.java#beforeConatinerStarted](https://github.com/jenkinsci/docker-plugin/blob/d342195d1107bb7c69a0084dae855c2b5362017a/docker-plugin/src/main/java/io/jenkins/docker/connector/DockerComputerSSHConnector.java#L145) we override the port bindings. So the one previously set are lost.
