### ISSUE TITLE
Option "disable SSH key management" is not saved

### ISSUE THREAD

**Issue by magn2** [jenkinsci/docker-plugin#534]
I am using the latest (1.0.1 docker plugin) with jenkins 2.85, i was wondering why all jobs run as root now.
I found that the setting "disable SSH key management" is not saved.
Steps to reproduce:
-> select option
-> save
-> option gone

**Comment by magn2** [comment]
also same version, when i use JNLP launcher, the user setting is not respected.

**Comment by niQo** [comment]
same problem

**Comment by ndeloof** [comment]
"SSH key" option not being saved is already fixed in master branch.
it also offers an option to select the unix user to run jenkins agent and avoid running as root.

JNLP launched needs a fix
