### ISSUE TITLE
Mapping Workspace On Master Does Not Honor Custom Workspace Definition

### ISSUE THREAD

**Issue by David-Villeneuve** [jenkinsci/docker-plugin#540]
If you get some troubles with docker-plugin, please report
 - [0.16.2 ] docker-plugin version you use  (had ssh problems when upgrading plug-in)
 - [2.76 ] jenkins version you use
 - [17.05.0-ce] docker engine version you use
 - [ ] stack trace / logs / any technical details that could help diagnose this issue

When using a custom workspace name (ie: /builds/workspace/myshortname), the mapped NFS workspace could not be browsed when the container was no longer instantiated.  

Renaming the workspace to match the job name (ie: /builds/workspace/some-real-full-job-name) worked.  

I don't think the plug-in checks the custom workspace definition.

**Comment by ndeloof** [comment]
workspace mapping feature is deprecated, as it assumes a local docker daemon. 
so closing this issue as "won't fix"
