### ISSUE TITLE
Version 1.0.2 upgrade destroys current cloud settings and can't create new

### ISSUE THREAD

**Issue by marcusmaday** [jenkinsci/docker-plugin#541]
- docker-plugin version 1.0.2
 - jenkins version 2.73.2
 - docker engine version 17.06
 
When upgrading to the Docker Plugin version 1.0.2 from 0.16.2, the first thing that I noticed was that there was no longer any Docker Clouds listed on my configure system page.  All I see is the "Add a new cloud" dropdown where I can try to select "Docker".  If I do try to select "Docker", nothing happens and I can't add the new Docker Cloud.  As you might expect, the config.xml <clouds> section is empty as well.

**Comment by crisp2u** [comment]
Same here. Downgrade does not help. :(

**Comment by ndeloof** [comment]
duplicate https://github.com/jenkinsci/docker-plugin/issues/542
fixed in 1.0.3
