### ISSUE TITLE
Configuration remove when updating from 0.18 to 1.0.2

### ISSUE THREAD

**Issue by RNiveau** [jenkinsci/docker-plugin#542]
Hi guys,

I update the docker-plugin from 0.18 to 1.0.2.
When jenkins restarted after update (jenkins 2.73.2), I lost all my configuration (30 docker templates).

I had to rewrite all configuration (fortunately, I had a backup to help me).

**Comment by ndeloof** [comment]
I'm able to reproduce this issue
(unfortunately, XStream doesn't report failure converting configuration on logs :P)
I didn't detected this before as I first tested update to 1.0 then 1.0.2

**Comment by ndeloof** [comment]
Can you please try this CI build and confirm the fix let you reload configuration from 0.16.x format ?
https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/1.0.x/lastSuccessfulBuild/artifact/docker-plugin/target/docker-plugin.hpi
if confirmed I'll release 1.0.3
cc @pteichner

**Comment by pteichner** [comment]
Thanks, I'm glad to see that I'm not the only one

**Comment by pteichner** [comment]
Migration from 1.0.1 to this version preserved the configuration - however I'm still unable to add new items.

**Comment by ndeloof** [comment]
Ok, so at least this one is fixed
