### ISSUE TITLE
"Cloud" button on global configuration doesn't work

### ISSUE THREAD

**Issue by ndeloof** [jenkinsci/docker-plugin#546]
initially reported on https://github.com/jenkinsci/docker-plugin/issues/525 by @pteichner 

JS stacktrace on browser:
```
Stack Trace
 
hudson-behavior.js:2952 Uncaught TypeError: Cannot read property 'parentNode' of null
    at eval (eval at geval (hudson-behavior.js:391), <anonymous>:5:28)
    at eval (eval at geval (hudson-behavior.js:391), <anonymous>:37:9)
    at eval (<anonymous>)
    at geval (hudson-behavior.js:391)
    at hudson-behavior.js:598
    at next (hudson-behavior.js:616)
    at hudson-behavior.js:599
    at next (hudson-behavior.js:616)
    at hudson-behavior.js:599
    at next (hudson-behavior.js:616)
 
 
 
 
In the following code – looks like document.getElementById('id4331'); returns null
 
      (function() {
       
        var master = document.getElementById('id4331');
        var table = master.parentNode;
        table.removeChild(master);
     
        makeButton($('id4331button'), function (e) {
         
          var name = $('id4331text').value;
          if(name=="") {
            alert("Please enter a user name or a group name");
            return;
          }
...
```

this comes from [matrix-auth-plugin](https://github.com/jenkinsci/matrix-auth-plugin/blob/master/src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly)

**Comment by ndeloof** [comment]
`/configure` page doesn't show any cloud instance
"Add Cloud" button doesn't work or require to click twice.

xml configuration still has
```
  <clouds>
    <com.nirima.jenkins.plugins.docker.DockerCloud> ...
```
no error reported 
docker slaves are provisioned as expected (until one override configuration)

**Comment by ndeloof** [comment]
it looks like there's some confusion as the docker plugin web UI do use twice the `<f:advanced>` jelly tag.

**Comment by pteichner** [comment]
Any further development on this?

**Comment by ndeloof** [comment]
@pteichner I can't reproduce this issue. My comment on `<f:advanced>` being used twice is not a diagnostic about this issue, just a side note.

imho this issue is mostly a matrix-auth-plugin's one. This one uses custom JS to render it's UI, there's some unexpected interaction at some point. But seems to depend on something else ... as I can't reproduce this issue.

**Comment by ndeloof** [comment]
SO this issue appears as Matrix-Auth NodeProperty is proposed as an option to configure DockerSlaveTemplate as one try to add a new Docker Cloud.

**Comment by ndeloof** [comment]
Created https://issues.jenkins-ci.org/browse/JENKINS-47697 to get matrix-authorization-plugin developers involved here.

**Comment by ndeloof** [comment]
closing this issue, will revert b07deb6 once a fix is found for JENKINS-47697

**Comment by ryan-gustafson** [comment]
I hit this problem yesterday trying to prototype a pipeline using docker.  I could not remove `matrix-auth` as it is a required transitive dependency.  It's not clear what downgrade versions of `docker-plugin` or `matrix-auth may` work together.  AFAICT this is a blocker for anyone trying to use the plugin for the first time (as I'm trying to do).  Maybe those with existing configurations are not so impacted.  In the meantime, I'll explore manually adding docker slaves.

Will there be a 1.0.4 release with the work-around present?  Or are there snapshot releases available somewhere?

**Comment by ndeloof** [comment]
1.0.4 just released (update center will be synched within ~ 24 hours)

**Comment by daniel-beck** [comment]
I think I fixed this problem on the matrix-auth side in 2.5 of that plugin.
