### ISSUE TITLE
SSH Launch Broken on Triton

### ISSUE THREAD

**Issue by magnayn** [jenkinsci/docker-plugin#552]
Triton (and probably others) give you an IP address per container.

DockerComputerSSHConnector is meant to cope with this case, but it's broken:

```
//get address, if docker on localhost, then use local?
        if (host == null || host.equals("0.0.0.0")) {
            String url = cloud.getDockerHost().getUri();
            host = getDockerHostFromCloud(cloud);

            if( url.startsWith("unix") && (host == null || host.trim().isEmpty()) ) {
                // Communicating with local sockets.
                host = "0.0.0.0";
            } else {

            /* Don't use IP from DOCKER_HOST because it is invalid or we are
             * connecting to a system that supports a single host abstraction
             * like Joyent's Triton. */
                if (host == null || host.equals("0.0.0.0")) {
                    // Try to connect to the container directly (without going through the host)
                    host = networkSettings.getIpAddress();
                    port = internalPort;
                }
            }
        }
```
The second half never now gets executed, because the host is always overwritten by "host = getDockerHostFromCloud(cloud);"

**Comment by ndeloof** [comment]
getDockerHostFromCloud returns `null` if no dockerHostname is configured and API address uses unix scheme. 
How do one connect to a Triton service ? (sorry, don't know much about this one)
I wonder this should be an extension point so a triton (or other) plugin could provide specific logic to resolve  infrastructure specific routing

**Comment by magnayn** [comment]
So the difference is that when you spin up a docker host on triton, it will
get a 'real' IP address - so talking to it using the docker host IP address
doesn't work.

I think changing the init part to this works (it's working for me, but I
haven't checked for non-triton)

if (host == null || host.equals("0.0.0.0")) {
    String url = api.getDockerHost().getUri();
    String dockerHost = getDockerHostFromCloud(api);

    if( url.startsWith("unix") && (dockerHost == null ||
dockerHost.trim().isEmpty()) ) {
        // Communicating with local sockets.
        host = "0.0.0.0";
    } else {

**Comment by ndeloof** [comment]
I assume triton doesn't document this allocated IP address to docker inspect API ?
would need to run some tests on my own ...

**Comment by ndeloof** [comment]
Looking at [previous implementation](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-parent-0.16.2/docker-plugin/src/main/java/com/nirima/jenkins/plugins/docker/launcher/DockerComputerSSHLauncher.java#L151) 

```java
        //get address, if docker on localhost, then use local?
        if (host == null || host.equals("0.0.0.0")) {
            String url = DockerCloud.getCloudByName(cloudId).getServerUrl();
            if( url.startsWith("unix") ) {
                // Communicating with local sockets.
                host = "0.0.0.0";
            } else {
                host = URI.create(url).getHost();

            /* Don't use IP from DOCKER_HOST because it is invalid or we are
             * connecting to a system that supports a single host abstraction
             * like Joyent's Triton. */
                if (host == null || host.equals("0.0.0.0") || usesSingleHostAbstraction(ir)) {
                    // Try to connect to the container directly (without going through the host)
                    host = networkSettings.getIpAddress();
                    port = sshConnector.port;
                }
            }
        }
```

if `serverUrl` is not a local unix domain socket, we use URL's host. As such the condition to switch to `networkSettings.ipAddress` only depends on usesSingleHostAbstraction, which itself is all about checking `driver == "sdc"`.

**Comment by ndeloof** [comment]
I have a fix for this but I wonder we have a really deterministic way to detect external IP here. I wonder docker-plugin should list candidate IPs from various potential sources and check each of them until it can establish a connection.

**Comment by ndeloof** [comment]
I've requested changes to Joyent's sdc expecting we won't have to handle such special cases in the future.
