### ISSUE TITLE
Environment variables not correctly saved

### ISSUE THREAD

**Issue by CyrilSiman** [jenkinsci/docker-plugin#553]
Hi, 

Plugin version : 1.0.4
Jenkins : 2.73.3

During configuration, if I add an environment variable in node Properties, save global configuration and comeback in Jenkins Configure System panel, my variable is disappeared.

Step one : add a new variable
![](https://i.imgur.com/4cO8Kp5.png) 

When I come back in panel a second time (none variable)
![](https://i.imgur.com/IfL8t9C.png)

**Comment by fxnn** [comment]
+1

(btw., this is https://issues.jenkins-ci.org/browse/JENKINS-47852)

**Comment by alexeygrigorovaurea** [comment]
I'm facing same issue

**Comment by vamsidhar5434** [comment]
same problem to me as well

**Comment by ndeloof** [comment]
I can reproduce this issue, will investigate a fix for 1.1.1

**Comment by fxnn** [comment]
Still reproducible with 1.1.1.

**Comment by ndeloof** [comment]
I've postponed fixing this, can't get `repeatableHeteroProperty` to work :'(

**Comment by fxnn** [comment]
Confirming the fix with 1.1.2. Thank you!
