### ISSUE TITLE
SSH Host Key Verifiers on docker slave

### ISSUE THREAD

**Issue by RNiveau** [jenkinsci/docker-plugin#555]
I have many docker slaves configured with "connect with ssh" method.

This generate the following alert on jenkins:

> SSH Host Key Verifiers are not configured for all SSH slaves on this Jenkins instance. This could leave these slaves open to man-in-the-middle attacks. Update your slave configuration to resolve this.

How can we configure docker plugin to avoid this alert ?

 - docker-plugin version: 1.0.4
 - jenkins version: 2.73.3
 - docker engine version: 1.13.1

**Comment by ndeloof** [comment]
docker plugin does not (yet) support configuration of a SshHostKeyVerificationStrategy.
I'd prefer to handle this internally without end-user having to manage this, so will need to check how we can get sshd host key.
