### ISSUE TITLE
"no pull access" after upgrade from 0.16.2

### ISSUE THREAD

**Issue by gilShin** [jenkinsci/docker-plugin#558]
I have upgraded from 0.16.2 to 1.0.4 and got an error of "pull does not exist or no pull access".
I haven't set any credentials for my docker registry and it worked just fine as it is with version 0.16.2.
I have tried to reconfigure the docker configurations in the system configuration page with no luck.

**Comment by ndeloof** [comment]
in 0.16.x registry credentials configuration was global, starting 1.x you need to explicitly configure registry URL and credentials to pull from a private registry

**Comment by gilShin** [comment]
Hi,

Thanks for the quick prompt!
What do you mean by globally and what do you mean by explicitly? 
The only configuration I could have found is in the Jenkins' system configuration. Where is the global configuration and where should I explicitly configure? In the job itself?

**Comment by ndeloof** [comment]
every docker image configuration form comes now with registry settings, so ou can select credentials to be used.
![capture d ecran 2017-11-29 a 11 28 20](https://user-images.githubusercontent.com/132757/33370705-a41c45c0-d4f8-11e7-8802-91acc0e9e781.png)

**Comment by gilShin** [comment]
OK
Saw that and set it to None because I do not have credentials in my private registry.
What am I doing wrong?

**Comment by ndeloof** [comment]
by definition a "private registry" require authentication

**Comment by gilShin** [comment]
BTW, we do not use docker registry but docker host.
This is something I was missing here. Is it still supported and how?

**Comment by ndeloof** [comment]
docker registry and docker host are two orthogonal concepts.
- registry is used to get images (push/pull) and require credentials to access private registries. If you use dockerhub, configure your dockerhub username/password
- docker host is node or API endpoint to manage docker containers and other ressources.
docker host URI and credentials (if needed) have to be configured as part of your Cloud global configuration.

**Comment by ndeloof** [comment]
as a side note, please join jenkins-user for such questions. This is a bug tracker not a forum :P

**Comment by gilShin** [comment]
But now I'm not sure if it is a question or a bug anymore.
I have configured the the docker host URI in the global configuration and as I have mentioned before, we do not have credentials for it. The URI is in the tcp:// format.

**Comment by ndeloof** [comment]
Please attach a full stack trace or error log f you want to report an issue (why didn't you used issue template ?)
Until you run unsecured (sic), `tcp://` access use TLS authentication with certificates, which have to be registered in Jenkins and selected as credentials to access Docker API

**Comment by gilShin** [comment]
First of all sorry for not using the template!
Attached is the stack trace from Jenkins' log.
[stackTrace.log](https://github.com/jenkinsci/docker-plugin/files/1514021/stackTrace.log)

Not sure I understand your last sentence. This docker host is just for testing.

**Comment by ndeloof** [comment]
docker host used for testing still expose your infrastructure to abuses, anyway your decision to run without security enabled.
That being said, the reported error is not about failing to run docker commands on this host, but failure to pull image "slave-ci2". From your previous comments I've understood this one is a private repository, so it **require** registry credentials configured.

Please follow-up on jenkins-users mailing list, this issue tracker is not designed for user assistance.
