### ISSUE TITLE
Docker Agent templates : Container setting are not saving 

### ISSUE THREAD

**Issue by vamsidhar5434** [jenkinsci/docker-plugin#559]
In jenkins configuration change the container settings save these changes , come back and see the changes are not saved 

docker-plugin : 1.0.5

we have a specific requirement when we creating docker container as a jenkins slave we have to mount the different volumes every time is there any way to achieve this using older version

**Comment by gamma** [comment]
Is there a reason for the lxcConfig missing now?

**Comment by ndeloof** [comment]
LXC isn't supported since 1.8 ... https://github.com/moby/moby/commit/3b5fac462d21ca164b3778647420016315289034#diff-83a075daa1f1fdbcfc9e8ff2364b0788

**Comment by gamma** [comment]
Ok, I was wondering why it did never really work but also there was no commit with an expressive description. Is there another way in moby to provide more options to the create command command? Is this something the docker-client will habe to provide first?

**Comment by ndeloof** [comment]
we indeed only can expose option supported by the underlying docker client library.
I have a test branch where I'm running docker-plugin with https://github.com/dockins/jocker, which is generated based on latest docker swagger API spec. This would allow to stay up-to-date way easier.

**Comment by gamma** [comment]
Thanks for the insight. Jocker Looks pro

**Comment by gamma** [comment]
Jocker looks promising. Looking forward to it :)
