### ISSUE TITLE
we don't have control on name of the newly created container 

### ISSUE THREAD

**Issue by vamsidhar5434** [jenkinsci/docker-plugin#563]
we have specific requirement where I have to link the newly created container to other containers using the name but i couldn't control the name given to the container 
we have --name flag which facilitate this feature when using Docker CLI and it would great if we can given the jenkins variable as name. but we don't have any such option in this plugin please add this feature as well

**Comment by ndeloof** [comment]
this is by intent : using a fixed name for agent container would prevent running them in parallel. Can't you establish this link the other way ? i.e. get your agent container linked to other ones ?

**Comment by vamsidhar5434** [comment]
My intension in not to give the fixed name but to give user control over name 
Example : Dockercontainer:${BUILD.NO} which creates new name every time

**Comment by ndeloof** [comment]
due to Jenkins design, agent is not created _for_ a specific job so we don't know which job will run it nor the build number.
