### ISSUE TITLE
number of executors for docker template not saved anymore using version 1.1

### ISSUE THREAD

**Issue by wumpz** [jenkinsci/docker-plugin#573]
I used successfully a docker build slave running 4 executors. (jenkins/jnlp-slave) with the previous version 1.0.3.

Now after upgrading to version 1.1, first I hat to completely configure docker and slave, because all of the configuration was gone.

The numbers of executors, even if it is mentioned as an experimental feature like in version 1.0.3, is not saved anymore. It is always set back to 1.

I see no regarding stacktrace or other unusual things with in jenkins log.

**Comment by wumpz** [comment]
Same problem using version 1.1.1.

**Comment by ndeloof** [comment]
This is by intent. >1 executor was an experimental feature (as documented in help tips) and doesn't make much sense as you loose agent isolation doing this.

**Comment by wumpz** [comment]
Nevertheless reusing a container to gain speed, e.g. reusing mavens repository is not a bad idea. To have more executors increased reusability of build data and therefore was/is faster. I hope you reconsider the status of this feature  again because IMHO it was a useful one.

**Comment by ndeloof** [comment]
maven repositories and such caches should be managed as volumes. 
file/data persistence is orthogonal to container to be (re)created on-demand.

**Comment by wumpz** [comment]
Understand. I was not sure if multiple docker instances could safely access one volume concurrently?

**Comment by ndeloof** [comment]
exactly the same way multiple maven process can access a shared local maven cache (a docker container is nothing but a running process with some isolation sugar :P)
