### ISSUE TITLE
nodeName naming convention should start with cloudId

### ISSUE THREAD

**Issue by bulanovk** [jenkinsci/docker-plugin#576]
If you get some troubles with docker-plugin, please report
 - docker-plugin version you use 1.1.1
 -  jenkins version you use 2.93

Starting from version 1.1 node naming convention was broken, it became static "docker-" + containerId.substring(0,12) and before it was cloudId+"-" + containerId.substring(0,12).

Without name of cloud as a part of Node name it's not possible to figure out where node was provisioned.

**Comment by ndeloof** [comment]
looks good, it also has been suggested in https://github.com/jenkinsci/docker-plugin/pull/514 to document the node the container is running on as a BuildAction (maybe with other infos) so this can be easily tracked.

**Comment by ndeloof** [comment]
Main benefit I see in using an action attached to the Run, is we can add many more informations there : the cloud which allocated node (if set), but also actual Node (in a swarm cluster) the container was executed on, and such infos we can collect from `docker inspect`.

**Comment by ndeloof** [comment]
DockerBuildAction attached to a build now tracks container, cloud (if set) as well as full docker inspect payload for diagnostic purpose

**Comment by bulanovk** [comment]
It solves issue partially: 

In log:
`
Running on docker-48a08fd2b022 on slave-03 in
`

But it still shows `docker-11acdabd8222` on node list window

**Comment by ndeloof** [comment]
on node list indeed, but if you need more info on this node when still alive you can just check it's computer page.

**Comment by bulanovk** [comment]
Yep, i found reference to the cloud Node info, Thank you for advise
