### ISSUE TITLE
Standby Executors as part of Strategy

### ISSUE THREAD

**Issue by neldridge** [jenkinsci/docker-plugin#578]
- docker-plugin: 0.16.2
 - jenkins: 2.89.1
 - varies, bust mostly 17.09.0-ce
 

Hi, I'm wondering if it's currently possible to configure standby idle executors.

I'd like to have 2 (or more) idle containers "running" at all times, waiting for jobs in the queue to become available. We are waiting anywhere between 0 and 5 minutes for a container to be provisioned and made available; we want this to work more efficiently. 

We do not want to re-use containers, or share a container between job executions. Each container should be fresh when a job executes.

I'm not sure if what I'm asking for is possible at the moment through another strategy, or what it would take to make this functionality available.

Thanks,
Nick

**Comment by thomassuckow** [comment]
A lot has changed to 1.1, I would upgrade before pushing this issue.

Full disclosure: I am also running 0.16.2

**Comment by ndeloof** [comment]
Jenkins Cloud API doesn't allow to provision agents "anticipating" future load.
Anyway I'm aware crazy delays to get a node allocated in some circumstances (https://github.com/jenkinsci/docker-plugin/issues/579)
When fixed, I guess this need will disappear as well.

**Comment by neldridge** [comment]
It's not "anticipating" future load if there's always 2 containers on standby; will look forward to an updated version that doesn't take so long to spawn containers.

Thanks!
