### ISSUE TITLE
Where did the Remote FS Root Mapping go?

### ISSUE THREAD

**Issue by farahfa** [jenkinsci/docker-plugin#583]
Hello,

Where did this option go? It was the only way we can make Jenkins know where the workspace is at? People cannot view their workspace from Jenkins UI anymore because of this! Please bring this helpful feature back!

Thanks,

**Comment by ndeloof** [comment]
Hi.
This feature was removed as it doesn't make sense when docker daemon is not running on same host as the jenkins master. This just was an irrelevant design.
I plan to re-implement this in near future using an explicit volume for workspace, that one could browse using a transient container.

**Comment by farahfa** [comment]
@ndeloof, Okay, but the problem that we're facing now (since the option has been removed) is that we cannot view the workspace from the Jenkins UI after the job has finished, even though I've mounted the workspace directory (from the slave VM to the master VM).

Like when I go to `/var/lib/jenkins/workspace` on the master VM I can see the jobs' workspace directories there (as it should), but in the UI, I cannot view the workspace because it says:

<img width="515" alt="screen shot 2018-01-01 at 12 01 48 pm" src="https://user-images.githubusercontent.com/9218600/34469375-98501246-eeeb-11e7-8320-b32998f124ac.png">


```
ubuntu@jenkinsmaster:/var/lib/jenkins$ ls -la /var/lib/jenkins/workspace/
total 2596
drwxrwxrwx 589 ubuntu  ubuntu   59392 Jan  1 17:01 .
drwxr-xr-x  27 jenkins jenkins  12288 Jan  1 16:51 ..
drwxrwxr-x   6 ubuntu  ubuntu    6144 Dec 18 12:24 Test-job
```

**Comment by ndeloof** [comment]
there's no standard way to access a file within a stopped container. If not using a volume docker-plugin can't offer this feature. The fact you use a shared mount between two VMs can't be considered a standard setup in the plugin.

**Comment by farahfa** [comment]
@ndeloof Hmm, can you point me to the right direction on how to do this? Before, it used to work with the `FS Root Mapping` option (even with the container stopped, we can still view the workspace).

**Comment by ndeloof** [comment]
There's no way so far. As container created to host the build is stopped (and removed) the workspace is lost. This one could be made persistent with a volume, but this remains invisible from master as there's no guarantee the docker host running this container shares filesystem with the master (this only happens with a special setup, or for single node usage).
What I plan to do is to introduce a custom  implementation for `WorkspaceBrowser` (an API I introduced some years ago for a comparable use-case :P) to allow accessing the stopped container _or_ a volume (not sure yet) used to host the build. Another alternative is to use `docker cp` to create a copy on master for the workspace, but this will consume much disk.

**Comment by farahfa** [comment]
Oh ok. Alright then we'll revert back to 0.16.x to get the Root FS Mapping option back and will wait until the new implementation (`WorkspaceBrowser`) is done. Thanks for the info.

**Comment by adityagu0910** [comment]
HI @ndeloof 
is it possible to make this Root FS Mapping feature available for people who are running docker slave containers on master node itself ?

**Comment by ndeloof** [comment]
I'm not active on this plugin anymore, please join jenkins-users mailing list for questions
