### ISSUE TITLE
Unit Tests were broken for LTS 2.89.1

### ISSUE THREAD

**Issue by bulanovk** [jenkinsci/docker-plugin#584]
If you get some troubles with docker-plugin, please report
 - docker-plugin version you use  1.1.1
 - jenkins version you use 2.89.1

All unit test trying to run slave are broken when testing on LTS 2.89.1, because CommandLuncher moved from Jenkins core to CommandLauncher Plugin starting from 2.86 version of Jenkins

**Comment by ndeloof** [comment]
If you run tests by changing jenkins.version property in pom.xml, then this is expected.
Any reason you want to change core requirement ?

**Comment by bulanovk** [comment]
It's requires to pass tests on LTS 2.89.1, because Command Launcher was removed from Jenkins core starting from Jenkins 2.86. By default docker plugin are tested againsts 2.60, 2.73 and 2.89 Jenkins version.

If we ommit  this changes, we will got false negative unit test results and error on PR

**Comment by ndeloof** [comment]
right, but docker-plugin does not rely on CommandLauncher ...
So, shouldn't this be transparent for plugin ? What I mean is : it makes sense to test plugin on various LTS, but this should not impact plugin (or all of them will need to add this hack !). Shouldn't this be managed by plugin parent pom.xml (or `buildPlugin` shared library) ? 



I'm also confused by the profile configured by `jenkins.version != any`. What's the intent here ?

**Comment by bulanovk** [comment]
Yes, in right way it should come from some of transitive, and now it just WA to got Green test while it will be fixed some where it realy reuqires this plugin.

I'm also confused by the profile configured by jenkins.version != any. What's the intent here ?
it just maven WA to got multiple maven profile activated in the same time, to avoid duplicate depends

**Comment by ndeloof** [comment]
Sorry still don't get it. If multiple profiles are enable, dependencies will just get merges in effective pom.

The "jenkins_after_2_86" looks good as a temporary workaround. Would better test jenkins.version >= 2.86 but I guess this is the best maven let us do (sic).

**Comment by bulanovk** [comment]
Maven documentation said:
```
This profile will automatically be active for all builds unless another profile in the same POM is activated using one of the previously described methods. All profiles that are active by default are automatically deactivated when a profile in the POM is activated
```

So if we just left <activeByDefault>true</activeByDefault> it will be diactivated when second profile will be triggered by a condition. To avoid such case there is a WA you need to specify any condition that alway will be true.

Yes, "jenkins_after_2_86" just a temp WA, until dependasies will be fixed on Jenkins\Plugins side.

We also have to add new profile per version >=2.86 we want to test against, now it's created for 2.89.1

**Comment by ndeloof** [comment]
What I mean is : we don't need those dependencies in a profile, if we want them to be always declared.
build is fixed on Linux for all LTS https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fdocker-plugin/detail/master/94/pipeline/14
Windows still has to be fixed (or skipped ?)

**Comment by bulanovk** [comment]
Yes, i missed this apporach.

```
Connection refused: no further information: localhost/127.0.0.1:2375
```
For windows it look's like there is no docker daemon, so i sugest to skip this test for windows platform for now.

**Comment by ndeloof** [comment]
yes indeed.

**Comment by ndeloof** [comment]
CI fixed ! https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fdocker-plugin/detail/master/95/pipeline

**Comment by ndeloof** [comment]
thanks a lot for your contribution !
