### ISSUE TITLE
JNLP UnitTests were failed under Windows and Linux

### ISSUE THREAD

**Issue by bulanovk** [jenkinsci/docker-plugin#586]
If you get some troubles with docker-plugin, please report
 - docker-plugin version you use 1.1.1
 - jenkins version you use 2.73.3/2.89.1

Test using unix soc on Windows OS family are fails as Windows dosen't have Unix Soc support

JNLP Test fails on Linux because it's not possible to connect to Jenkins started on localhost from Docker container

**Comment by ndeloof** [comment]
I understand failure on Windows, but not on Linux.
org.jvnet.hudson.test.JenkinsRule#configRoundtrip() do rely on a full featured WebClient, so jenkins is definitively available on loopback interface, and should be reachable from local docker daemon.

**Comment by bulanovk** [comment]
As you could see in JenkinsRule bind jenkins port to localhost 
https://github.com/jenkinsci/jenkins-test-harness/blob/d7acb8e67e3da73297b6ca1d3c6987d5de0f8e6a/src/main/java/org/jvnet/hudson/test/JenkinsRule.java#L681

For linux it means that you could reach this port only from the same machine. More over container itself also have localhost mapped to loopback interface of a container.

You could perform simple test:

1)start Nginx binded to Localhost:
docker run -it -p 127.0.0.1:3333:80 nginx

2)try to curl it from another docker container:
docker run hiromasaono/curl curl 127.0.0.1:3333

as a result you got:
curl: (7) Failed to connect to 127.0.0.1 port 3333: Connection refused

In case of docker for Mac you have a VM with alpine inside of HyperKit, and this translation done some were there

**Comment by ndeloof** [comment]
ok got it.
I indeed had to configure my local test instance to get jenkins configured with external IP address to run tests with `hpi:run`, I forgot this "detail".

Something I dislike here is we rely on external host IP, which assumes the computer is connected to some network (or has been configured with a static IP).
I wonder we could force container being created with `--network="host"` as a workaround

**Comment by ndeloof** [comment]
I'm suggesting this as an alternative https://github.com/ndeloof/docker-plugin/commit/67e19558127c362e5086f828ae53dfb825b82583

**Comment by bulanovk** [comment]
Yes, we relay, but for linux we will have at least docker0 interafce with IP.

```
 if (SystemUtils.IS_OS_LINUX) {
           template.getDockerTemplateBase().setNetwork("host");
        }
```
This one will fails when you run  DockerComputerSSHConnectorTest because it will try to ocupy port 22

```
[root@jenkins-lab jenkins]# docker run -it --network="host" jenkins/ssh-slave
+ [[ '' == ssh-* ]]
+ [[ 0 -gt 0 ]]
+ env
+ grep _
+ ssh-keygen -A
ssh-keygen: generating new host keys: RSA1
+ exec /usr/sbin/sshd -D -e
Bind to port 22 on 0.0.0.0 failed: Address already in use.
Bind to port 22 on :: failed: Address already in use.
Cannot bind any address.
```

**Comment by ndeloof** [comment]
confirmed build success on my Linux box.
I don't have a windows one (yet) to run tests, waiting for CI status.

**Comment by ndeloof** [comment]
unfortunately CI do stop on first test failure, and get killed by missing CommandLauncher
