### ISSUE TITLE
Failed container provisioning 'locks' the associated label

### ISSUE THREAD

**Issue by saxonww** [jenkinsci/docker-plugin#592]
I'm trying to get container-driven builds set up on both Windows- and Linux-based docker hosts. What I have noticed is that if anything prevents the launch of a container matching a particular label expression, then that label expression becomes locked and will not work again. If I stop the associated job (which is in the state of 'waiting for next available executor on 'label') and restart it, I don't see any log entries for provisioning, and no traffic is sent to my Docker host.

I am able to work around the issue by adding new labels to the agent template, then changing the label expression on the job and rerunning it. I'm not sure if this is solved by restarting Jenkins or not, or if there is a built-in refresh/retry period (I haven't seen it retry).

This can't work for me in a production scenario because in a failure scenario I have to either touch every job or (potentially) restart Jenkins, both of which are very disruptive.

**Comment by ndeloof** [comment]
Which version of docker-plugin are you using ? Please check this still happens with 1.1.2

**Comment by saxonww** [comment]
Yes it does. This is repeatable in my environment:

Set up a new Cloud and Agent Template with label 'myLabel'. The template should reference an image that doesn't work for some reason. Configure a job to use 'myLabel' and start the job. Depending on how badly broken the image is, in jenkins.log you will either see a docker error or repeated provisioning attempts. In the web UI, the job will be queued with a status like "pending: all nodes of label 'myLabel' are offline" waiting on next available executor for myLabel.

If the provisioning result was an error (e.g. image doesn't exist, requires login, etc.) then that appears to be the last time I can use 'myLabel' without changing template configuration or restarting Jenkins. The exception is that I can change the agent template config to set up a new label, then go set it back.

If the provisioning result is an ongoing cycle, e.g. my image entrypoint is wrong and Jenkins just spins it up over and over, I can fix the image behind the scenes and it will eventually work.

**Comment by ndeloof** [comment]
oh ok, I better understand this scenario

**Comment by maxime066** [comment]
Hi ndeloof, I see that you just added a [commit](https://github.com/jenkinsci/docker-plugin/commit/142b73c13e4e847fd8cd7b16596060823fef954d) trying to fix this issue. If it works, can you create a release ? We are having problems to manually configure our Docker cloud with the latest versions of this plugin and I'm wondering if this bug doesn't prevent any attempts we do to fix our configuration.

Thank you.

**Comment by roman-vynar** [comment]
We have seen the same issue with 1.1.2.
Would be great to release this fix. Thanks!

**Comment by crazy-max** [comment]
Same issue for me :(

**Comment by MichaelGreco** [comment]
Yeah I'm seeing the exact same thing ... I started getting "Jenkins doesn't have label XYZ" on a label thats been in my docker config for over a year. The strange thing is it didn't happen for all of them ...

**Comment by MichaelGreco** [comment]
Interesting Roman ...I back up our jenkins data : 

 docker run --name orchestration_data -v orchestration:/var/jenkins_home -i -t bash -c "tar czvpf /orchestration.tgz var/jenkins_home"

and then I "docker commit orchestration_data (repo):orchestration_data:J2.99-01_24_18"  where (repo) is my private dock registry ... and then I push that up to that repo.

I'm going to go get the latest master build of the docker plugin from https://ci.jenkins.io/

**Comment by MichaelGreco** [comment]
oh my ... oh my ... yeah I loaded the latest build from : 

https://ci.jenkins.io/job/Plugins/job/docker-plugin/job/master/106/

and not only did it fix the label issue but it also fixed some other strange issue where my container seemed wedged. Upon jenkins restart the container in question had that step rerun ... 🥇

**Comment by ndeloof** [comment]
I plan to publish release next week

**Comment by saxonww** [comment]
The dependency issue was with the bouncycastle plugin I believe. Fixing
bouncycastle didn't immediately restore the docker configuration though. I
had to disable it, restart, then re-enable it before the clouds section
showed up again in global config. I think the disable/restart/enable is
what actually erased the config.

I was very glad that we only had 5 templates across 3 clouds.

**Comment by roman-vynar** [comment]
Yes, bouncycastle plugin wiped the config. I have simply upgraded Jenkins and plugins w/o changing anything else.

**Comment by alexindigo** [comment]
Seeing similar symptoms, when it fails to pull image from Artifactory, it locks "template", so I had to delete and recreate it.

**Comment by scotty-g** [comment]
Any update on a release containing this fix?

**Comment by leodutra-aurea** [comment]
Happening.

**Comment by pjdarton** [comment]
Earlier versions of the plugin could "leak" resources, which could cause these kind of symptoms. That's believed to be fixed in recent releases though.
If you're having issues, raise a new one, include lots of logs, and if you think it's similar to this one then mention it in the description.
