### ISSUE TITLE
Docker build fails with Authentication problem when Dockerfile FROM requires authentication

### ISSUE THREAD

**Issue by pteichner** [jenkinsci/docker-plugin#593]
If you get some troubles with docker-plugin, please report
 - [ ] docker-plugin; 1.1.2
 - [ ] jenkins version: 2.73.2
 - [ ] docker engine version you use:  17.09.0-ce
 - [ ] stack trace / logs / any technical details that could help diagnose this issue

The docker step is as follows: 
`step([$class: 'DockerBuilderPublisher', cleanImages: false, cleanupWithJenkinsJobDelete: false, cloud: 'build-docker-01', dockerFileDirectory: '.', pullCredentialsId: 'uex-repo', pushCredentialsId: '', pushOnSuccess: false, tagsString: "${env.dkr_RF_MIT}/caa:${FORMATTEDVERSION}"])`

The issues in output

```[Pipeline] step
Docker Build
Docker Build: building image at path /home/jenkins/workspace/UK2/CAA
Step 1/7 : FROM opf-dkr-local.uex-repo.hq.k.grp/nagra/nagra-nginx:1.9.16

[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (❸ Artifactory Upload)
Stage '❸ Artifactory Upload' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (❹ Module Integration Test)
Stage '❹ Module Integration Test' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (❺ Artifactory Promotion)
Stage '❺ Artifactory Promotion' skipped due to earlier failure(s)
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] script
[Pipeline] {
[Pipeline] echo
ChannelName
[Pipeline] echo
uk2
[Pipeline] echo
UK2/CAA (<http://uex-sp-cd.hq.k.grp/job/UK2/job/CAA/181/|181>) failure
[Pipeline] mattermostSend
Mattermost Send Pipeline step configured values from global config - connector: true, icon: false, channel: false, color: false[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // retry
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
com.github.dockerjava.api.exception.DockerClientException: Could not build image: Get https://opf-dkr-local.uex-repo.hq.k.grp/v2/nagra/nagra-nginx/manifests/1.9.16: unknown: Authentication is required
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.buildImage(DockerBuilderPublisher.java:353)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher$Run.run(DockerBuilderPublisher.java:286)
	at com.nirima.jenkins.plugins.docker.builder.DockerBuilderPublisher.perform(DockerBuilderPublisher.java:423)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE```

**Comment by ndeloof** [comment]
I wonder : can't you just use a shell script step in your pipeline to run `docker build && docker push` ? This DockerBuilderPublisher seems to have ridiculous added value as just syntactic sugar (as well as being duplicated with Docker build'n publish plugin)

**Comment by ndeloof** [comment]
duplicates https://github.com/jenkinsci/docker-plugin/issues/589 it seems ?

**Comment by pteichner** [comment]
We don't push through docker shell because we collect the build information - so we use artifactory. As to using Docker build'n publish plugin I haven't tried it, but we've been using this.

**Comment by ndeloof** [comment]
I don't understand how using docker CLI would prevent doing the same. What do you mean by "_we collect the build information - so we use artifactory_" ? docker-plugin's build step doesn't provide any special feature but just wrap the /build API call into a jenkins builder

**Comment by pteichner** [comment]
Using the Docker proxy with Artifactory allows you to capture certain build information and upload it to Artifactory linked to the docker image upload

**Comment by ndeloof** [comment]
right, so [this guy](https://wiki.jenkins.io/display/JENKINS/Jenkins+Artifactory+Plugin+-+Setting+Up+Docker+Build+Info). but AFAIK you can do the same with plain CLI, can't you ?
There's nothing in docker-plugin to enable this feature, or even make it easier to setup.

**Comment by pteichner** [comment]
that's what we're using - but first we need to build the image right? And for that we use this plugin and tag it. Part of the docker build involves downloading from a private registry (happens to be Artifactory as well) which requires authentication hence it's failing

**Comment by ndeloof** [comment]
Sure, my question was to understand which added value this builder provides to you vs using plain docker commands in a shell script build step.

**Comment by pteichner** [comment]
it's a 1 liner to execute, the plugin takes care of making the docker file available to the agent it's running on. It nicely stores the image id as part of the build in Jenkins

**Comment by ndeloof** [comment]
> making the docker file available to the agent
I guess you mean the docker API socket. Makes sense, this is interesting feature to let agent run docker commands without the need for it to have explicit access to the underlying docker infrastructure.
Docker traceability also makes perfect sense (despite docker-traceability-plugin not being integrated)

**Comment by pteichner** [comment]
That's why it makes sense 
![image](https://user-images.githubusercontent.com/28305157/34205092-fff35452-e578-11e7-8ada-dda24d42790f.png)

**Comment by ndeloof** [comment]
right. from this point of view integration with https://github.com/jenkinsci/docker-traceability-plugin would also make sense, as it would track usage in other jobs as well.
