### ISSUE TITLE
Display docker name in build executor status

### ISSUE THREAD

**Issue by karthikeyan-malaisamy** [jenkinsci/docker-plugin#597]
We add multiple docker slave machines and name them according to their functions. For example,

*`Docker-frontend`*

- `agent template 1`
- `agent template 2`

*`Docker backend`*

- `agent template 1`

When a container is running, build executor currently status shows, 

`docker-containerid`

It will be great if we can have,

*`Docker-frontend-containerid`*

*`Docker-backend-containerid`*

It will help us actively distinguish the machines that are running.

**Comment by ndeloof** [comment]
on build details there's a dedicated link with information on the container created to host it and the cloud selected to provision agent.
Any technical reason ou segregate those templates with distinct cloud names, and not just use adequate docker image ? using a general purpose docker infrastructure would give you more flexibility and build elasticity.

**Comment by cperezprieto** [comment]
I don't agree with the reason for closing this. It would be a nice enhancement if the agents nodes where named using the Docker Cloud Name instead of the static label "docker".

If there is a technical problem to handle this change I would agree with the reason but as it is possible to add more than one Docker Cloud (whatever the reason is) makes sense, from my point of view, to be able to know which agents belong to each Cloud

**Comment by pjdarton** [comment]
The Names are configurable within the templates - it's now entirely under Jenkins-admin control.
It _used_ to be hard-coded as "docker" (and that's what it'll default to if you don't set it) but you're free to set it to anything you like.
As the help text for "Name" says:
> Name prefix to use for all the Jenkins nodes created from this template. 
> Jenkins will append a unique ID to this name in order to create individual node names.
> If blank or just whitespace, a default of "docker" will be used.

So if you assign a name based on the cloud name to all templates within a cloud, you'll easily see at a glance which slave nodes are on which cloud.
