### ISSUE TITLE
feature request: Using a tagged container as start of a new job.

### ISSUE THREAD

**Issue by aikomastboom** [jenkinsci/docker-plugin#60]
We are trying to configure a build-chain in which every job is a step towards production.
For example: init_ws -> sanity_check -> build -> unit_test -> coverage -> package
We would like to start the sanity_check with the resulting (tagged) image from the init_ws job, then use the resulting image for build step, and reuse the build result for unit and coverage steps. Then use the clean build step to create a package.

If only we could pass the current jobs image tag to the next job which in turn will run that container as starting point.

**Comment by KostyaSha** [comment]
@magnayn is this related to your jenkins PR?

**Comment by ndeloof** [comment]
if you want multiple steps to run within the same container context, why split this into multiple jobs ? Also, sounds to me what you're looking for a reusing a volume, not container

**Comment by ndeloof** [comment]
please reopen if still relevant
