### ISSUE TITLE
Feature: Reenable control of retention policies for configured docker templates

### ISSUE THREAD

**Issue by mattjohnson** [jenkinsci/docker-plugin#607]
I was previously using a retention policy to keep docker slaves up and running with great success. This speeds up builds as it doesn't have to clone the entire git repo(ours is unfortunately large) each time and and tools required from the Jenkins global tools configuration are already installed. By removing this feature it adds extra setup overhead to each build. If there is no technical reason is was removed I would like to see that feature enabled again. If that change is accepted I would be happy to work on a PR for it.

**Comment by ndeloof** [comment]
Using a fresh new docker container enforce resources get cleaned-up after build completion. To avoid getting a fresh clone on every build, just assign a named volume as root directory to your agent template, so it will be reused by future containers on same template.

**Comment by mattjohnson** [comment]
I had the same thought about using named volumes. However the named volume for the template would be static and multiple jobs running that use the same template will also share that volume and will cause workspace conflicts. Is there something that can avoid this? Or am I not understanding how this works?
