### ISSUE TITLE
Jenkins doesn't get beyond "Trying to run container for"

### ISSUE THREAD

**Issue by Aman-Osman-Bose** [jenkinsci/docker-plugin#608]
-  [1.1.2 ] docker-plugin version you use
-  [Jenkins ver. 2.89.2] jenkins version you use
-  [Version = 17.09.1-ce, API Version = 1.32] docker engine version you use

The container gets launched in the docker and I see the container in the docker ps -a, but nothing is happening after that. 

**stack trace / logs / any technical details that could help diagnose this issue**

- Jenkins Logs

Jan 16, 2018 11:31:51 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Asked to provision 1 slave(s) for: test-docker
Jan 16, 2018 11:31:51 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud provision
Will provision 'test-auto', for label: 'test-docker', in cloud: 'docker'
Jan 16, 2018 11:31:51 AM INFO com.nirima.jenkins.plugins.docker.DockerCloud addProvisionedSlave
Provisioning 'test-auto' number '2' on 'docker'; Total containers: '2'
Jan 16, 2018 11:31:51 AM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Image of test-auto from docker with 1 executors. Remaining excess workload: 0
Jan 16, 2018 11:31:51 AM INFO com.nirima.jenkins.plugins.docker.DockerTemplate provisionNode
Trying to run container for test-auto (edited)

**Comment by pjdarton** [comment]
Closing due to lack of response.

If it's still a problem after doing the above, provide additional information and re-open the issue.
