### ISSUE TITLE
RFE: "--no-cache" option for build / publish docker image build step

### ISSUE THREAD

**Issue by jbnance** [jenkinsci/docker-plugin#612]
When building Docker images from the CLI one has the ability to pass the `--no-cache` option which instructs Docker to pull fresh copies of source images (the `FROM`) during the build.  Please add an equivalent option to the "Build / Publish Docker Image" build step.

**Comment by curi0s** [comment]
Any news on this?

**Comment by pjdarton** [comment]
Nope; nobody seems to want this enough to implement it.

If you want it and are willing to implement it, please create a PR - I'd be happy to review it and merge it in once it's complete.

**Comment by curi0s** [comment]
I'm not a java developer sorry. Therefor I have to remove it and do it oldschool
