### ISSUE TITLE
Docker Plugin / Dockerized Jenkins + Slave Issue

### ISSUE THREAD

**Issue by gsugambit** [jenkinsci/docker-plugin#613]
- [ 1.1.2] docker-plugin version you use
 - [2.89.3 ] jenkins version you use
 - [17.12.0-ce ] docker engine version you use

I have a latest version dockerized [jenkins ](https://hub.docker.com/_/jenkins/) in which I have updated to 2.89.3. Inside this jenkins I plan to use the Docker Plugin in order to have slaves that are spun up from template rather. (I run this with compose which has sonar/jenkins/nexus/gitlab in it).

I have updated my docker on the host to expose tcp 2375. I am able to hit "Test Connection" inside the UI of the Docker Plugin and it's successful and shows the response. So, I configured it with the jenkins/ci slave and specified the docker network of my compose file and everything worked perfectly, the slaves would instantly spin up and complete the tasks.

So, I decided I would run all of my slaves on a different remote machine. This machine has the same docker version. I expose 2375 on this machine and the "Test Connection" option inside the jenkins UI worked. However, when I create builds, the resulting docker container [on the remote PC] would spin up and never do anything. The Jenkins UI would have the build stuck in waiting. I looked at the jenkins logs I could see where it initiated the container run but there were no logs afterwards about any issues. I could sh into the resulting container on the other PC but didn't see anything useful. I also did a wget for the ip:2375/version of the docker on host machine and could retrieve the version file so I know the communication works. 

I have to manually clean up the container when this happens as well as jenkins not trying to build any other containers under the "label" that represents the remote cloud. Should the current plugin behave this way and we can only run this plugin if the dockerized jenkins and jenkins slaves are running on the same host?

![image](https://user-images.githubusercontent.com/13861767/35896392-8b68874a-0b81-11e8-9e21-6e71deb0df24.png)
![image](https://user-images.githubusercontent.com/13861767/35896420-b1f2d096-0b81-11e8-8443-d6f946f0f0f6.png)

**Comment by ndeloof** [comment]
which launch mechanism are you using ?

**Comment by gsugambit** [comment]
@ndeloof What do you mean by launch mechanism? For the nodes? It's all through the docker plugin

**Comment by pjdarton** [comment]
Launch mechanism = SSH, JNLP or Attached (the latter is still experimental).
I'd suggest that you start out trying JNLP and using the "official" docker image "jenkins/jnlp-slave".
If that fails, use SSH and the "jenkins/ssh-slave" image.
Or you can use the "Attach" method and use the "jenkins/slave" image.

All of these are used during the docker-plugin automated build & test so they're a known-good configuration, i.e. if they don't work for you, it's down to your environment, not the plugin.
e.g. I have a VM with an old version of docker where the "Attach" method doesn't work.

**Comment by pjdarton** [comment]
Closing issue due to lack of response.
If you can provide additional information and this is still a problem with the latest plugin code, feel free to re-open.
If you find that it's no longer a problem with the latest plugin code then please say so here ;-)
