### ISSUE TITLE
Unable to connect to Docker Host

### ISSUE THREAD

**Issue by missweetcxx** [jenkinsci/docker-plugin#637]
#### Issue:  
It prompts "Permission denied: /var/run/docker.sock" when testing connection to Docker Host URL which is "unix:///var/run/docker.sock".
#### Operation steps:  
1. Add public key (rsa_id.pub) on Jenkins master to authorized_key file of Docker Host  (both under ~/.ssh);
2. Install docker-plugin on Jenkins, enter "configure -> Cloud -> Docker" and input "unix:///var/run/docker.sock" in "Docker Host URI" field;
3. Add Jenkins Credentials by "SSH Username with private key", but it won't display on drop-down box of "Server Credentials";  (K.O)
![2018-03-20 9 55 25](https://user-images.githubusercontent.com/30889036/37631478-d8217b1e-2c24-11e8-80b1-a43a9865df40.png)

4. Try to test connection, but failed.
#### Version Info:  
docker-plugin version: 1.1.3
jenkins version: 2.60.3
docker engine: 17.09.1-ce

**Comment by pjdarton** [comment]
Sounds like Jenkins is complaining that it isn't permitted to access the Docker socket.
That's unlikely to be a problem with the Docker plugin; more likely that the unix user being used to run Jenkins isn't in the "docker" user group so the Jenkins process isn't permitted to directly access the socket.

You can either add the Jenkins user to the docker group or tell Jenkins to connect to the TCP socket instead.

**Comment by abhijangid123** [comment]
### Docker Jenkins Issue
---------------------------------------------------------------------------------------------------------------------------

Make a new file if not existing..
```
# vim /etc/default/docker
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375
```

Edit service file
```
# vim /lib/systemd/system/docker.service
ExecStart=/usr/bin/dockerd -H fd://                <--- before
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:2375    <--- After
```
Add additional hosts for Jenkins. and reload & restart docker service
```
# systemctl daemon-reload
# systemctl restart docker
```
