### ISSUE TITLE
Environment variables are not passed to containers

### ISSUE THREAD

**Issue by sadovnikov** [jenkinsci/docker-plugin#642]
In order to avoid Jenkins JEP-200 troubles we upgraded the plugin from `1.0.4` to `1.1.3`. However the new version seems to have a problem with passing environment variables to the containers.

Below are 
- a fragment of Docker Agent template configuration in Jenkins and 
- the value of the same environment variable as it's seen in the running container (copied from `docker inspect`).

![image](https://user-images.githubusercontent.com/4749332/38354356-9df5ed84-38b9-11e8-83cc-89c6986e9666.png)

````
"Config": {
	"Hostname": "93eccfe73b47",
	"Domainname": "",
	"User": "jenkins",
	"AttachStdin": false,
	"AttachStdout": false,
	"AttachStderr": false,
	"Tty": true,
	"OpenStdin": false,
	"StdinOnce": false,
	"Env": [
		"JENKINS_HOME=/var/jenkins_home",
		"JENKINS_LOG=/var/jenkins_log",
		"HOST_HOSTNAME=luuNNNd",
		"LANG=en_US.UTF-8",
		"LANGUAGE=en_US.UTF-8",
		"LC_CTYPE=en_US.UTF-8",
		"LC_ALL=en_US.UTF-8",
		"JAVA_HOME=/usr/lib/jvm/zulu-8"
	],
````

`luuNNNd` is default value, which is defined in the docker image and which is expected to be set through ` --env HOST_HOSTNAME` in `docker run` command. This worked as expected in `1.0.4`

Below is `DockerCloud` configuration from `config.xml`
````
<com.nirima.jenkins.plugins.docker.DockerCloud plugin="docker-plugin@1.1.3">
  <name>docker.luu182d</name>
  <templates>
	<com.nirima.jenkins.plugins.docker.DockerTemplate>
	  <configVersion>2</configVersion>
	  <labelString>jenkins-agent</labelString>
	  <connector class="io.jenkins.docker.connector.DockerComputerJNLPConnector">
		<user></user>
		<jnlpLauncher>
		  <vmargs>-Dhudson.diyChunking=false -Djava.security.krb5.conf=/etc/krb5.conf -Djava.security.auth.login.config=/etc/jaas-krb5.conf -Djavax.security.auth.useSubjectCredsOnly=true -Dsvnkit.http.methods=Negotiate -Dsvnkit.negotiate.type=spnego</vmargs>
		  <workDirSettings>
			<disabled>false</disabled>
			<internalDir>remoting</internalDir>
			<failIfWorkDirIsMissing>false</failIfWorkDirIsMissing>
		  </workDirSettings>
		</jnlpLauncher>
		<jenkinsUrl></jenkinsUrl>
	  </connector>
	  <remoteFs>/var/jenkins_home</remoteFs>
	  <instanceCap>15</instanceCap>
	  <mode>NORMAL</mode>
	  <retentionStrategy class="com.nirima.jenkins.plugins.docker.strategy.DockerOnceRetentionStrategy">
		<timeout>10</timeout>
	  </retentionStrategy>
	  <dockerTemplateBase>
		<image>containerhub:6666/jenkins-agent:latest</image>
		<pullCredentialsId></pullCredentialsId>
		<dockerCommand></dockerCommand>
		<hostname></hostname>
		<dnsHosts/>
		<network></network>
		<volumes>
		  <string>/etc/luu182d.keytab:/etc/luu182d.keytab</string>
		  <string>/work/jenkins-enterprise/krb5.conf:/etc/krb5.conf</string>
		  <string>/work/jenkins-enterprise/jaas-krb5.conf:/etc/jaas-krb5.conf</string>
		  <string>/work/jenkins-enterprise/.ssh:/var/jenkins_home/.ssh</string>
		  <string>/work/jenkins-enterprise/.m2:/var/jenkins_home/.m2</string>
		  <string>/work/jenkins-enterprise/.npmrc:/var/jenkins_home/.npmrc</string>
		  <string>/var/run/docker.sock:/var/run/docker.sock</string>
		  <string>m2-local-repo:/work/m2_repo</string>
		</volumes>
		<volumesFrom2/>
		<environment>
		  <string>HOST_HOSTNAME=luu182d</string>
		</environment>
		<bindPorts></bindPorts>
		<bindAllPorts>false</bindAllPorts>
		<privileged>false</privileged>
		<tty>true</tty>
		<extraHosts class="empty-list"/>
	  </dockerTemplateBase>
	  <removeVolumes>false</removeVolumes>
	  <pullStrategy>PULL_LATEST</pullStrategy>
	  <nodeProperties class="empty-list"/>
	</com.nirima.jenkins.plugins.docker.DockerTemplate>
  </templates>
  <dockerApi>
	<dockerHost plugin="docker-commons@1.11">
	  <uri>tcp://luu182d:2376</uri>
	</dockerHost>
	<connectTimeout>3</connectTimeout>
	<readTimeout>60</readTimeout>
  </dockerApi>
  <containerCap>100</containerCap>
  <exposeDockerHost>false</exposeDockerHost>
</com.nirima.jenkins.plugins.docker.DockerCloud>
````

 - docker-plugin: 1.1.3
 - jenkins version: 2.107.1.2
 - docker engine version: Version = 17.04.0-ce, API Version = 1.28

**Comment by pjdarton** [comment]
Aha!  While working through some other issues in the code, I think I've sussed this one.
`DockerComputerJNLPConnector.java` has a `beforeContainerCreated` method which wants to set the `JAVA_OPT` environment variable.
It looks like the code _replaces_ all the environment variables with just the `JAVA_OPT` variable instead of _adding_ the `JAVA_OPT` variable into the list of environment variables.

To fix this, the code `cmd.withEnv("JAVA_OPT=" + vmargs.trim());` would need to take existing env vars into account.

To workaround this until the plugin is fixed, I'd suggest that you try *removing* the JVM arguments from the JNLP configuration and instead add `JAVA_OPT=-Dhudson.diyChunking=false -Djava.security.krb5.conf=/etc/krb5.conf -Djava.security.auth.login.config=/etc/jaas-krb5.conf -Djavax.security.auth.useSubjectCredsOnly=true -Dsvnkit.http.methods=Negotiate -Dsvnkit.negotiate.type=spnego` into your environment variables.

**Comment by sadovnikov** [comment]
Thanks a lot !!! I'll give it a try tomorrow

**Comment by pjdarton** [comment]
Code changes have been merged.  Will be fixed in the next release (which will probably be 1.1.5).
