### ISSUE TITLE
Docker Slave plugin is conflicting with Artifactory plugin in Jenkins

### ISSUE THREAD

**Issue by SudarshanNarasimha** [jenkinsci/docker-plugin#652]
Please don't use the issue tracker to ask questions, join jenkins-users mailing list.

If you get some troubles with docker-plugin, please report
 - [ ] docker-plugin version you use- docker slaves plugin version 1.0.5
 - [ ] jenkins version you use - 2.65
 - [ ] docker engine version you use
 - [ ] details of the docker container(s) involved and details of how the docker-plugin is connecting to them
 - [ ] stack trace / logs / any technical details that could help diagnose this issue

docker slave plugin is conflicting with Artifactory plugin ..
Both these plugins are installed in our Jenkins instance..
Please help to fix this ussue

**Comment by pjdarton** [comment]
This is the github for [docker-plugin](https://plugins.jenkins.io/docker-plugin).
You're reporting a problem with the [docker-slaves plugin](https://plugins.jenkins.io/docker-slaves).
These are two different plugins.

Also, I would strongly suggest that, as you're not reporting a bug, you go to the jenkins-users mailing list and/or irc and/or google group and ask for assistance there.  Bug reports are not intended as a general support channel.
