### ISSUE TITLE
Docker agent sets wrong workdir

### ISSUE THREAD

**Issue by derryx** [jenkinsci/docker-plugin#663]
Hi!

I have this pipeline snippet:
```
      stage('Build') {
           agent {
		        docker {
		            image 'node:8'
                    args '-v ${WORKSPACE}/frontend://app -w /app -e HOME=/app -e NPM_CONFIG_PREFIX=/app/.npm-global'
		            reuseNode true
   		        }
           }
           steps {
              script {
                  sh 'npm install'
                  sh 'npm run build -- --prod'
              }
           }
      }
```

The generated command line is:
`docker run -t -d -u 1000:1000 -v ${WORKSPACE}/frontend://app -w /app -e HOME=/app -e NPM_CONFIG_PREFIX=/app/.npm-global -w /var/jenkins_home/workspace/Thomas/Frontend --volumes-from 10147e9dd09cae6d023cce0f03500f661a2f2668751997d40aac31dab8120b4b -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** node:8 cat`

As you see we end up with TWO -w parts. And the one generated by Jenkins is WRONG because -w sets the workdir INSIDE the Docker container. But the path set is the one on the Jenkins host.

Docker Pipeline Plugin Version is 1.17 on Jenkins ver. 2.121.1

A similar problem is #561 which has been closed.

CU
Thomas

**Comment by derryx** [comment]
Sorry. I now have understood how this works. It works now.

**Comment by swensorm** [comment]
Ran into this issue as well because we were having issues with the long 80 character alpha-numeric string Jenkins tacks on to Multi-branch Pipeline workspaces.  Is the workaround to wrap all steps inside a `dir('/app') { ... }`?

**Comment by escouvois** [comment]
Hi @derryx 

Could you explain how you figured out this problem?
I also tried something like `docker.image(xxxx).inside('-w workdir')` to override the former workdir, but it doesn't seem to work...
