### ISSUE TITLE
thread leak dockerjava-netty

### ISSUE THREAD

**Issue by alexeygrigorovaurea** [jenkinsci/docker-plugin#669]
- [1.0.4 ] docker-plugin version you use
 - [2.89.4 ] jenkins version you use
 - [ 1.8.5] docker engine version you use
 - [ I'm using Windows and Linux docker hosts , both connection over TCP] details of the docker container(s) involved and details of how the docker-plugin is connecting to them
 - [ ] stack trace / logs / any technical details that could help diagnose this issue

I'm facing up to ~7k of threads in monitoring plugin like this :

dockerjava-netty-10-174
sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:752)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
java.lang.Thread.run(Thread.java:748)

image
![image](https://user-images.githubusercontent.com/28352910/42403076-6171ed56-8187-11e8-9f8e-1f19bdf26a50.png)

Threads number is growing with ~1-2k per day in my case. When it reaches 8-10k threads jenkins instance become very slow and i have o reboot it.
![image](https://user-images.githubusercontent.com/28352910/42403347-3058f564-8189-11e8-81a0-90feeaffb303.png)

Any idea how to debug/avoid this?

**Comment by alexeygrigorovaurea** [comment]
I am also trying to interrupt them via script 
Thread.getAllStackTraces().keySet().grep{it.name =~ /dockerjava-netty.*/ }.each {
  it.interrupt()              
 }.size()
but it seem doesn't give anything  size is same every time

**Comment by pjdarton** [comment]
Plugin version 1.0.4 is not the latest, and I believe that later revisions implement connection caching which should eliminate this kind of leak.
You're running Jenkins 2.89.4, so you can upgrade to plugin version 1.1 (which requires Jenkins 2.60+) and beyond.

Upgrade to the latest version - that should resolve the issue.
 - If it does, close this issue.
 - If it doesn't, provide information that's based on the latest version of the plugin.

**Comment by alexeygrigorovaurea** [comment]
well after attempt to upgrade to latest it  fail smoketest.  So far I cannot upgrade on production to put it on real load to check leakage.

**Comment by pjdarton** [comment]
FYI there was a known issue where upgrading from very old versions to newer ones can loose some configuration - e.g. authentication information for connecting to registries has moved (to where it's needed, rather than centrally).
If you go through your docker-plugin configuration and ensure that everything is configured, it should work (it does for me and many others).

**Comment by pjdarton** [comment]
If you can provide details of the problems you encountered, I may be able to assist getting you upgraded to the latest code.
Until then, I'm going to close this - feel free to re-open it if/when you provide additional information.
