### ISSUE TITLE
[regression] Confusion between image and repository + ":" + tag

### ISSUE THREAD

**Issue by guilhem** [jenkinsci/docker-plugin#68]
There is some confusion in code between this docker notions.

Before 0.7, it was not a problem as we can set image to `repo:tag` like `guilhem/vagrant-ubuntu:14.04`.
But it's not possible anymore because (in particular) of this line: `src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java#L255` as it oblige tag `latest` (and fail if a `:` is given)

What we have to do is to add 2 new params, `repository` and `tag`.
If an image is given (a SHA) we can use it but can pull it.
If a repo + tag (by default "latest") is given, we can pull it if necessary.

I try coding it... it's over my java skills :(

**Comment by KostyaSha** [comment]
i have "asdfasdf:b25" and it spins "asdfasdf:b25", probably issue resolved.
Please try #210 and reopen if it still reproduces
