### ISSUE TITLE
docker command input has no effect to the docker run command

### ISSUE THREAD

**Issue by nichamon** [jenkinsci/docker-plugin#684]
**Setup**
- docker plugin version: 1.1.5
- jenkins version: 2.140
- docker engine version: 18.06.0-ce, build 0ffa825
- The jenkins master runs in a docker container. The connection method of the slave docker container is JNLP.

**symptom**
The --device options were specified in the docker command field. Containers were started successfully. Jenkins builds can run on the container if it didn't depend on the devices.

![screenshot 79](https://user-images.githubusercontent.com/22683157/45057977-de6d8780-b05c-11e8-8e5a-6847e4e34c0e.png)

However, the devices weren't present in the container. Below is the docker inspect output.

[docker.inspect.log](https://github.com/jenkinsci/docker-plugin/files/2350267/docker.inspect.log)

**Comment by pjdarton** [comment]
I think you've misunderstood what the `dockerCommand` field does.
This field is equivalent to the `docker run`'s [CMD](https://docs.docker.com/engine/reference/run/#cmd-default-command-or-options) argument.  It is not a general set of additional arguments provided to a `docker run` command (FYI the plugin doesn't do a `docker run` commands; it uses a Java docker client called `docker-java`).

Also FYI, at present, the docker plugin has no support for the `docker-java`'s `CreateContainerCmd.withDevices(...)` method (which is the `docker-java` equivalent of passing `--device=` arguments to a `docker run` command); it probably wouldn't be too difficult to do - it'd make a good first PR ;-)
