### ISSUE TITLE
Docker nodes/slaves do not show their current build

### ISSUE THREAD

**Issue by muhlba91** [jenkinsci/docker-plugin#691]
Hi,

I am running on the newest Docker, Jenkins and plugin versions (fresh installations on a test system).

After configuring my `pipelineJob` using `dockerNode`, the job runs through very well but the issue I‘m facing is that although Jenkins picks up the new slave and shows it in its overview but I‘m not able to see which build is runing on them.

For example, if I start 4 jobs I see 4 new slaves being created in Jenkins but I have no idea which builds they belong to and are running.

I suppose/hope it‘s just a simple configuration error on my side. Do I have to work with the `connector` property of `dockerNode` so that the nodes can reply back their current build?
If so, do I have to use `jnlp` and how do I have to configure it? When I tried using `dockerNode(...., connector: jnlp())` I got a NotSerializable exception for the JNLP class.

Thanks! :)

**Comment by pjdarton** [comment]
Please do not use this issue tracker to ask questions. This facility is for reporting (and fixing) bugs in the code. Please seek help elsewhere. e.g. the [jenkins-users google group](https://groups.google.com/forum/#!forum/jenkinsci-users).
