### ISSUE TITLE
PullImage, removeContainer, and startContainer get stuck forever

### ISSUE THREAD

**Issue by joonasky** [jenkinsci/docker-plugin#701]
When 
 - [ ] docker-plugin 1.1.5
 - [ ] jenkins version 2.138.1
 - [ ] docker swarm/1.2.5, API Version = 1.22
 - [ ] stack trace of a stuck startContainer:
`Computer.threadPoolForRemoting [#199]" daemon prio=5 WAITING
sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
com.github.dockerjava.netty.InvocationBuilder$AsyncResultCallback.awaitResult(InvocationBuilder.java:127)
com.github.dockerjava.netty.InvocationBuilder.post(InvocationBuilder.java:274)
com.github.dockerjava.netty.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:28)
com.github.dockerjava.netty.exec.StartContainerCmdExec.execute(StartContainerCmdExec.java:11)
com.github.dockerjava.netty.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
com.github.dockerjava.core.command.StartContainerCmdImpl.exec(StartContainerCmdImpl.java:46)
com.nirima.jenkins.plugins.docker.DockerTemplate.doProvisionNode(DockerTemplate.java:579)
com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:544)
com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:376)
jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)`

- [ ] stack trace of a stuck pullImage:

`Computer.threadPoolForRemoting [#4205]" daemon prio=5 WAITING
                           sun.misc.Unsafe.park(Native Method)
java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
com.github.dockerjava.core.async.ResultCallbackTemplate.awaitCompletion(ResultCallbackTemplate.java:92)
com.nirima.jenkins.plugins.docker.DockerTemplate.pullImage(DockerTemplate.java:503)
com.nirima.jenkins.plugins.docker.DockerTemplate.provisionNode(DockerTemplate.java:523)
com.nirima.jenkins.plugins.docker.DockerCloud$1.run(DockerCloud.java:376)
jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
`

So these hanging threads lead to a situation where Jenkins is stuck since no containers can be provisioned.

I managed to correct the pullImage by adding timeout in [awaitCompletion](https://github.com/jenkinsci/docker-plugin/blob/master/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplate.java#L500) but to correct the startContainer and RemoveContainer, I had to change com.github.dockerjava.netty.InvocationBuilder$AsyncResultCallback.awaitResult to use java.util.concurrent.CountDownLatch.await with a timeout.

**Comment by pjdarton** [comment]
This certainly used to be an issue until timeouts were introduced in an earlier version (see [this comment](https://github.com/jenkinsci/docker-plugin/issues/594#issuecomment-357663827), #610 and #633).
My guess is that you've got `Read Timeout` set to zero (or blank, or negative) on the cloud, and the `Pull timeout` set similarly in the template - blank/zero/negative values will disable the timeout functionality and mean that, if your docker endpoint accepts connections but doesn't respond to commands, you'll get hanging threads.

Try setting `Read Timeout` to 10 seconds (or whatever time you believe is the worst-case time it takes your swarm to start a new container) and the `Pull timeout` to 300 seconds (or whatever time you believe is the worst-case time it takes your swarm to pull an image).

**Comment by joonasky** [comment]
Thanks for quick response. I should have mentioned that Read Timeout and pull Timeout were set to 100 s, and 250 s, respectively. It seems that these hanging threads appear when there is some network problems.

**Comment by pjdarton** [comment]
Sorry for the late response, but if you could share the change(s) you made to the docker-plugin (ideally in a PR), i.e. whatever you did to do "I managed to correct the pullImage by adding timeout in awaitCompletion" then that'd be appreciated.

Changes to dockerjava are, as you might expect, out of scope for this issue/repository and should be addressed in the dockerjava repo ... but by all means cross-reference here.

I'm not sure, but given that `pullImage` calls `cmd.exec(`...`).awaitCompletion()` and you were able to sort that out, maybe it'd be possible to change the way the docker plugin calls the dockerjava code so we can ensure there's a timeout?

**Comment by pjdarton** [comment]
@joonasky Can you please share the changes you made?
> I managed to correct the pullImage by adding timeout in awaitCompletion but to correct the startContainer and RemoveContainer, I had to change com.github.dockerjava.netty.InvocationBuilder$AsyncResultCallback.awaitResult to use java.util.concurrent.CountDownLatch.await with a timeout.

I don't need a full PR (although I wouldn't turn one down ;-) ) but if you can provide a code example of "before" and "after" then I could look at including that kind of fix in a future version.

**Comment by pjdarton** [comment]
Closing due to lack of response
