### ISSUE TITLE
Enh: ability to specify tmpdir when starting container

### ISSUE THREAD

**Issue by sroth80021** [jenkinsci/docker-plugin#714]
First off, very nice plugin!   It seems to support most of the Docker run functionality, and seems very stable.

One feature which would be very useful is to be able to specify the --tmpfs (or --mount) options (0..n times) for a particular path.  

A tmpfs option to docker run is needed in order to run a container w/systemd in non-privileged mode, as described at 
 https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/
which suggests starting a container w/systemd like this:
   docker run -d --tmpfs /tmp --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro httpd

and which according to this page: https://docs.docker.com/storage/tmpfs/
I believe is equivalent to this (--mount allows for additional tmpfs config options such as size and mode):
   docker run -d --mount type=tmpfs,destination=/tmp  --mount type=tmpfs,destination=/run  -v /sys/fs/cgroup:/sys/fs/cgroup:ro httpd

Today, it does not seem possible to specify this when starting up the build agent containers.   Adding either the --tmpfs or --mount options would allow this to be specified.

This would allow systemd-based containers to run in non-privileged mode, which would be very useful in a Jenkins-based testing environment.

A workaround (the only one I know of right now) for this issue is to run the docker template/container in privileged mode.

**Comment by sroth80021** [comment]
The --tmpfs / --mount option is also used a workaround to run Oracle DB in a container (since Oracle DB requires /dev/shm to have exec privs, and Docker does mounts it with noexec) -- see slide 56 at https://www.slideshare.net/gvenzl/oracle-database-on-docker-best-practices-92806097

which says the way to run a container with Oracle DB is:
docker run -v /dev/shm --tmpfs /dev/shm:rw,nosuid,nodev,exec,size=1g ...

so it seems that adding the --tmpfs/--mount option to the docker plugin will also allow Oracle DB to work properly in docker containers launched by the Docker plugin.

**Comment by DamirCiganovic-Jankovic** [comment]
Can someone pls respond to this, this will speed up our jenkins build by a lot because we have many integration tests with database

**Comment by pjdarton** [comment]
It's not quite that simple...
- The `docker-plugin` code relies on the Jenkins plugin `docker-java-api-plugin` to provide it with a Java API with which it accesses the docker API.
- The `docker-java-api-plugin` in turn is a front for the `docker-java` library.
- ...but the `docker-java` library doesn't have any provision for either `--tmpfs` or `--mount`.

So, if you want this feature added, the first thing you'll need to do is to get new methods added to the [CreateContainerCmd class](https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java) to support `withTmpfs` and `withMount`, then get the `docker-java-api-plugin` to update to a version of `docker-java` that includes this functionality.
Once that's done, it'd then be possible to enhance the `docker-plugin` to take advantage of that new functionality.

**Comment by avaiss** [comment]
docker-java does support tmpfs since the merge of https://github.com/docker-java/docker-java/pull/1022

**Comment by pjdarton** [comment]
OK, cool - hadn't spotted that option hidden away in the host config...

The next step would be to implement some code that'll add a used-editable field to the docker template such that we can construct a `Map<String,String>` that can then (if the template's map is not null or empty) be passed to a call to `withTmpFs` on the create-container cmd's host config.

If someone creates a PR for that I'd be happy to advise and/or review it.

**Comment by bguerin** [comment]
`--tmpfs` and `--volume` options can all be replaced by `--mount` one, which allow more things.

Once docker-java/docker-java#523 done, maybe all can be switched to it ?

**Comment by chbieri** [comment]
Any use on this feature? This would speed up our ci/cd pipelines significally.

**Comment by pjdarton** [comment]
As stated above, a PR implementing this feature would be welcomed ... but none have been forthcoming.

If you want it, please implement it and raise a PR; I'd be happy to advise, review the changes and, once it's all ok, merge it into the next release.

**Comment by bguerin** [comment]
There is one, but need works :
https://github.com/jenkinsci/docker-plugin/pull/767

**Comment by bguerin** [comment]
New up-to-master and working PR available: #826

**Comment by ericcitaire** [comment]
Upgrading the plugin to 1.2.3, Jenkins fails to start when volumes are configured with JCasC (field `volumes` doesn't exist anymore). It would have been nice to keep backward compatibility.

**Comment by bguerin** [comment]
@ericcitaire sorry I missed something ... of course, I do not want to break backward compatibility at all
Is a simple @DataBoundSetter setter enough ?

**Comment by pwurbs** [comment]
We have the same issue. The existing mounts configuration doesn't work anymore with this update, if the specified folder doesn't exist on the host.

**Comment by bguerin** [comment]
@pwurbs that seems the right way to me, at least you see the problem and can fix it
