### ISSUE TITLE
jenkinsfile slave node test

### ISSUE THREAD

**Issue by akmabrouk** [jenkinsci/docker-plugin#721]
Hello
I have this jenkins file used for testing pipeline if it works with the jenkins slave. where do I add slve node called 'slave01'  

it already works on the master however.

node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build("akmabrouk/webpage")
    }

    stage('Test image') {
        /* Ideally, we would run a test framework against our image.
         * Just an example */

        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }
}

Thank you so much in advance

**Comment by pjdarton** [comment]
[RTFM](https://github.com/jenkinsci/docker-plugin/blob/master/README.md) - last paragraph - you're asking in the wrong place.
