### ISSUE TITLE
Docker plugin is incompatible with docker buildkit 18.09.2

### ISSUE THREAD

**Issue by kshcherban** [jenkinsci/docker-plugin#722]
Following error is thrown intermittently:
```
Error: java.io.IOException: Cannot retrieve .Id from 'docker inspect debian:9-slim'
```

 - [x] docker-plugin version: 1.13
 - [x] jenkins version: 2.138.1
 - [x] docker engine version: 18.09.2, API version: 1.39, Git commit: 6247962

Following pipeline code is used:
```
docker.withRegistry(registry) {
   docker.build(image_repo + ":$tag", '-f docker/Dockerfile .').push()
   docker.image(image_repo + ":$tag").push(shortTag)
}
```

Configuration of docker daemon:
```
{
    "bip": "192.168.1.1/16",
    "data-root": "/srv/docker",
    "storage-driver": "overlay2",
    "features": { "buildkit": true }
}
```

**Comment by pjdarton** [comment]
The issue template says:
> If you get some troubles with docker and Jenkins then you first need to determine which plugin you are using.
> There is more than one plugin for Jenkins that provides docker-related capabilities, and this is just one of them.
> See the README.md file for further details.

If you read https://github.com/jenkinsci/docker-plugin/blob/master/README.md you'll see that it states:
> Note: There is more than one docker plugin for Jenkins and if you are using Jenkins pipeline / workflow / Jenkinsfile builds with code including terms like docker.withDockerRegistry or docker.image etc as provided by the docker-workflow plugin then this is not the repository you are looking for.

You are using pipeline/workflow code using code `docker.withDockerRegistry`.  That's provided by the [docker-workflow plugin](https://github.com/jenkinsci/docker-workflow-plugin), not this one.
