### ISSUE TITLE
Add options to customize user, group, uid, gid in Docker Agent templates

### ISSUE THREAD

**Issue by devster31** [jenkinsci/docker-plugin#724]
- [1.1.6] docker-plugin version
 - [2.150.3] jenkins version
 - [18.09.2] docker engine version

The current template options don't allow to customize user, group, uid or gid of the container being created.
This may cause issues when using `jenkins` to build docker images.
My current setup, for example, uses the default `jenkins/jnlp-agent-docker` which encounters the following error:
```
docker build -t <user>/<project> .
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.37/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=<sessionid>&shmsize=0&t=<user>%2F<project>&target=&ulimits=null: dial unix /var/run/docker.sock: connect: permission denied
```
which I believe could be avoided using `--user jenkins:<gid>` where `<gid>` corresponds to the group ID of the docker user on the host machine.

**Comment by idueppe** [comment]
I would prefer if you could configure the `group-add` argument of `docker run`.

For instance, in the config are two group ids defined: <gid_1> and <gid_2> then the run command should look like:

```
docker run --user jenkins --group-add <GID1> --group-add <GID2> ...
 ```

I guess this would be more flexible.

**Comment by ericcitaire** [comment]
Incremental builds are available :
* [docker-java-api](https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/docker-java-api/3.1.5-rc11.59b91388afe6/) built from https://github.com/jenkinsci/docker-java-api-plugin/pull/5
* [docker-plugin](https://repo.jenkins-ci.org/incrementals/io/jenkins/docker/docker-plugin/1.1.10-rc915.f7c9b174bfb4/) built from https://github.com/jenkinsci/docker-plugin/pull/777

Please give it a try and let me know. Feel free to up-vote and comment the 2 PRs! :)

**Comment by pjdarton** [comment]
I think this is complete, as the linked PRs are all merged.
