### ISSUE TITLE
Problem to mount volume from slave to master

### ISSUE THREAD

**Issue by JuniorCtba** [jenkinsci/docker-plugin#727]
Hello,

I have my jenkins master running in openshift with the latest version of jenkins and the docker-plugin.

I have one pvc in openshift that is binding my jenkins /var/_jenkins_home.

I have a VM with docker to run my slaves and the slaves are running fine.
The volume to my slaves are /home/jenkins.

I tried to bind the volumes from slaves to master, but was not able to have this work.

In the docker template i have added this configuration on the Volume
/home/jenkins:/var/_jenkins_home

Could you give me some help?

**Comment by pjdarton** [comment]
Sorry, but this isn't a general user-help forum - this is a bug report/RFE area.  If you need help, you'll have to go to the normal Jenkins help resources, chat rooms etc.
FYI mounting volumes within docker is something that's easily misunderstood and I'd recommend you read up on exactly what it means if you ask docker to mount a volume - 9 times out of 10 it can't work the way folks expect, and this plugin is merely a thin layer between Jenkins and docker - it can't do anything that docker can't to.
