### ISSUE TITLE
feature request: expose rest api for docker host/image configuration

### ISSUE THREAD

**Issue by michaelheyvaert** [jenkinsci/docker-plugin#73]
it would be nice to manage the build slave config from a rest api
instead of having to use the jenkins configuration.

Adding a new docker host currently requires to re-adding all slave configs for the new host,
automating this from the rest api make this easier.

**Comment by ndeloof** [comment]
Don't create multiple clouds for every docker nodes !
Run docker-swarm standalone so they appear as a single Docker API endpoint
