### ISSUE TITLE
Help setting up docker plugin using groovy

### ISSUE THREAD

**Issue by leandromoreirati** [jenkinsci/docker-plugin#765]
Hello,
I am trying to configure Docker via groovy and am getting the error below:

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 2: unable to resolve class com.nirima.jenkins.plugins.docker.DockerTemplate
 @ line 2, column 1.
   import com.nirima.jenkins.plugins.docker.DockerTemplate
   ^

Script1.groovy: 5: unable to resolve class io.jenkins.docker.connector.DockerComputerAttachConnector
 @ line 5, column 1.
   import io.jenkins.docker.connector.DockerComputerAttachConnector
   ^

Script1.groovy: 4: unable to resolve class com.nirima.jenkins.plugins.docker.launcher.AttachedDockerComputerLauncher
 @ line 4, column 1.
   import com.nirima.jenkins.plugins.docker.launcher.AttachedDockerComputerLauncher
   ^

Script1.groovy: 1: unable to resolve class com.nirima.jenkins.plugins.docker.DockerCloud
 @ line 1, column 1.
   import com.nirima.jenkins.plugins.docker.DockerCloud
   ^

Script1.groovy: 3: unable to resolve class com.nirima.jenkins.plugins.docker.DockerTemplateBase
 @ line 3, column 1.
   import com.nirima.jenkins.plugins.docker.DockerTemplateBase
   ^

5 error

I'm starting to work with groovy now, can you please give me a hint of what to research to solve this problem.

Below the plugin configuration:

import com.nirima.jenkins.plugins.docker.DockerCloud
import com.nirima.jenkins.plugins.docker.DockerTemplate
import com.nirima.jenkins.plugins.docker.DockerTemplateBase
import com.nirima.jenkins.plugins.docker.launcher.AttachedDockerComputerLauncher
import io.jenkins.docker.connector.DockerComputerAttachConnector
import jenkins.model.Jenkins

// parameters
def dockerTemplateBaseParameters = [
  bindAllPorts:       false,
  bindPorts:          '',
  cpuShares:          null,
  dnsString:          '',
  dockerCommand:      '',
  environmentsString: '',
  extraHostsString:   '',
  hostname:           '',
  image:              'jenkinsci/slave:latest',
  macAddress:         '',
  memoryLimit:        null,
  memorySwap:         null,
  network:            '',
  privileged:         false,
  pullCredentialsId:  '',
  sharedMemorySize:   null,
  tty:                true,
  volumesFromString:  '',
  volumesString:      ''
]

def DockerTemplateParameters = [
  instanceCapStr: '4',
  labelString:    'docker.local.jenkins.slave',
  remoteFs:       ''
]

def dockerCloudParameters = [
  connectTimeout:   3,
  containerCapStr:  '4',
  credentialsId:    '',
  dockerHostname:   '',
  name:             'docker.local',
  readTimeout:      60,
  serverUrl:        'unix:///var/run/docker.sock',
  version:          ''
]

// https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.1.2/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplateBase.java
DockerTemplateBase dockerTemplateBase = new DockerTemplateBase(
  dockerTemplateBaseParameters.image,
  dockerTemplateBaseParameters.pullCredentialsId,
  dockerTemplateBaseParameters.dnsString,
  dockerTemplateBaseParameters.network,
  dockerTemplateBaseParameters.dockerCommand,
  dockerTemplateBaseParameters.volumesString,
  dockerTemplateBaseParameters.volumesFromString,
  dockerTemplateBaseParameters.environmentsString,
  dockerTemplateBaseParameters.hostname,
  dockerTemplateBaseParameters.memoryLimit,
  dockerTemplateBaseParameters.memorySwap,
  dockerTemplateBaseParameters.cpuShares,
  dockerTemplateBaseParameters.sharedMemorySize,
  dockerTemplateBaseParameters.bindPorts,
  dockerTemplateBaseParameters.bindAllPorts,
  dockerTemplateBaseParameters.privileged,
  dockerTemplateBaseParameters.tty,
  dockerTemplateBaseParameters.macAddress,
  dockerTemplateBaseParameters.extraHostsString
)

// https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.1.2/src/main/java/com/nirima/jenkins/plugins/docker/DockerTemplate.java
DockerTemplate dockerTemplate = new DockerTemplate(
  dockerTemplateBase,
  new DockerComputerAttachConnector(),
  DockerTemplateParameters.labelString,
  DockerTemplateParameters.remoteFs,
  DockerTemplateParameters.instanceCapStr
)

// https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.1.2/src/main/java/com/nirima/jenkins/plugins/docker/DockerCloud.java
DockerCloud dockerCloud = new DockerCloud(
  dockerCloudParameters.name,
  [dockerTemplate],
  dockerCloudParameters.serverUrl,
  dockerCloudParameters.containerCapStr,
  dockerCloudParameters.connectTimeout,
  dockerCloudParameters.readTimeout,
  dockerCloudParameters.credentialsId,
  dockerCloudParameters.version,
  dockerCloudParameters.dockerHostname
)

// get Jenkins instance
Jenkins jenkins = Jenkins.getInstance()

// add cloud configuration to Jenkins
jenkins.clouds.add(dockerCloud)

// save current Jenkins state to disk
jenkins.save()

**Comment by pjdarton** [comment]
As the [issue template ](https://github.com/jenkinsci/docker-plugin/blob/master/ISSUE_TEMPLATE.md)states:
> Firstly, please do not use the issue tracker to ask questions, join jenkins-users mailing list.

This is a request for assistance; this github area is not a support area.
This github area is for bug reports regarding this plugin; this is not a bug report for this plugin.

I suggest you google the error message you're getting and/or ask for assistance in groovy support forums.
