### ISSUE TITLE
Use docker swarm standalone

### ISSUE THREAD

**Issue by Drimix20** [jenkinsci/docker-plugin#766]
Hi all,
we are using https://github.com/jenkinsci/docker-plugin for managing multiple docker hosts. We have used tcp://<docker_host>:<exposed_port>/ swarm/api/ configured value in 'Docker Host URI' configuration field. Docker container is correctly created, connected to Jenkins and assigned job passed successfully. But I noticed, that container is being always created on <docker_host> configured endpoint only. In Jenkins log file I can see, that plugin correctly detect other docker host connected in swarm, but containers are never created on other nodes. 

Can you please give me advice, what I'm doing wrong? 

Thank you. 

P.S I was trying to contact email google group based on [instructions for getting support](https://github.com/jenkinsci/.github/blob/master/SUPPORT.md) but I received non existing group error.

**Comment by pjdarton** [comment]
http://letmegooglethat.com/?q=jenkins+users+google+groups
