### ISSUE TITLE
how do i connect to kubernetes cluster?

### ISSUE THREAD

**Issue by encryptblockr** [jenkinsci/docker-plugin#771]
i am having issues resolving the kubernetes cluster api server inside the container of the docker pipeline
I have a docker helm image that i am using in my docker pipeline and want to run helm to install applications but need helm to be able to connect to the kubernetes cluster first

here is my *Jenkinsfile*

```
pipeline {
    agent none
    stages {
        stage('Helm') {
            agent {
                docker { image 'dtzar/helm-kubectl' }
            }
            steps {
              withCredentials([kubeconfigContent(credentialsId: 'k8s-cluster', variable: 'KUBECONFIG_CONTENT')]) {
                sh '''
                helm version
                helm ls
                kubectl get all -n test
                '''
              }

            }
        }
    }
}
```

and here is the error am getting which is that the helm docker container is unable to resolve dns of the kubernetes cluster api server

```
+ helm ls
Error: Kubernetes cluster unreachable
```

where is documentation of how to connect the docker pipeline to kubernetes cluster or have dns work to resolve external hostnames?

**Comment by pjdarton** [comment]
dns is up to your docker daemon; it typically uses the host's OS's DNS.  If that's not working, it's got nothing to do with this plugin.
Likewise, this plugin has nothing to do with k8s either.
I'd suggest you google and/or seek help as specified in the [docs](https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md).
