### ISSUE TITLE
"Docker Certificate Directory" kind not found in Jenkins credentials

### ISSUE THREAD

**Issue by DonConMan** [jenkinsci/docker-plugin#776]
Jenkins version: 2.219
Docker plugin: 1.1.9

Currently attempting to connect a Jenkins host with my docker host via TLS certs. I'm having an issue in Jenkins where the "Docker Certificate Directory" is not an available credential type for a docker cloud instance. I followed the instructions in https://github.com/jenkinsci/docker-plugin/issues/245#issuecomment-158012362 but I'm currently unable to find the kind specified.

What I'm currently seeing:
![image](https://user-images.githubusercontent.com/52182523/75170667-73a08800-56f8-11ea-9e05-e9c4bc74ad14.png)

**Comment by DelusionalLogic** [comment]
I just had the same problems. It has been renamed to X.509 Client Certificate (and you no longer use a directory, but upload them directly in the gui).
