### ISSUE TITLE
cant pass storage parameters to container 

### ISSUE THREAD

**Issue by AlexTzib** [jenkinsci/docker-plugin#780]
Hello 

I'm using the plugin for several scenarios and it's working great(docker cloud configuration via Jenkins config ).
for the new container I created, I need the storage to be a bit bigger than the 10G default.
using the docker command I was able to pass:` --storage-opt size=15G` and make the container a bit bigger. 
I wasn't able to pass this parameter not using the docker command filed or the environment filed. 
the result I get is:  it did not respond or got this error : 
```
eason: Template provisioning failed.
com.github.dockerjava.api.exception.BadRequestException: {"message":"OCI runtime create failed: container_linux.go:345: starting container process caused \"exec: \\\"--storage-opt\\\": executable file not found in $PATH\": unknown"}     
```   
is this functionalety missing ? 
how can i add this argument ? 

hope this question fits this place, if not feel free to delete it .
thanks!

**Comment by pjdarton** [comment]
This plugin doesn't provide access to the docker command line; if you have access to the docker command line from a Jenkins plugin, you're using a different Jenkins plugin.
See README.md for more info.
