### ISSUE TITLE
How to specify docker build path when Build/Publish Docker Image

### ISSUE THREAD

**Issue by zwidny** [jenkinsci/docker-plugin#781]
Hi guys, 
    I build task as **Freestyle project**, but I can not specify Docker build path when I want to build a image through a Dockerfile

![20200311150707](https://user-images.githubusercontent.com/3658733/76391345-4b788080-63aa-11ea-9641-0d3014f6950f.jpg)

thanks

 + docker-plugin:  1.1.9
 + jenkins: 2.204.2
 + docker engine: 18.09.5, build e8ff056

**Comment by pjdarton** [comment]
As the docs [state](https://github.com/jenkinsci/docker-plugin/blob/master/CONTRIBUTING.md):
* Please do not use the issue tracker to ask questions. This facility is for reporting (and fixing) bugs in the code. If you're not 100% sure it's a bug in the code then please seek help elsewhere. e.g. the [jenkins-users google group](https://groups.google.com/forum/#!forum/jenkinsci-users).

That field is relative to the workspace folder.
I suggest you add a shell build step that does `ls -al` so you can see what file(s) you've got in there; if they aren't there then that's your problem (and has nothing to do with this plugin).
