### ISSUE TITLE
Optionally disable --volumes-from functionality

### ISSUE THREAD

**Issue by tomlankhorst** [jenkinsci/docker-plugin#783]
Jenkins runs in a docker container with a bind-mount JENKINS_HOME. 

When running a job with a pipeline, that has a Docker agent, the docker-plugin automatically detects the host's container ID and appends the `--volumes-from` docker run flag.
Furthermore, the `docker-plugin` adds mounts to the various workspace directories. 

Now, I do not want the JENKINS_HOME mounted in the build container, the job workspace should be sufficient. 

There seems no way to override this `--volumes-from` behaviour. 

 - [x] 1.1.9 docker-plugin version 
 - [x] 2.222.1 jenkins version
 - [x] 19.03.8 docker engine version 
 - [x] D-in-D. Jenkins container has bind mount to JENKINS_HOME.

**Comment by pjdarton** [comment]
Without seeing the pipeline code that you're referring to, I can't be 100% certain, but I _suspect_ that the functionality you're describing is coming from the docker-workflow plugin, as that's generally what people are using when they're talking about pipelines + docker, especially when talking about docker CLI arguments (as this plugin doesn't use the docker CLI at all).
See https://github.com/jenkinsci/docker-plugin/blob/master/README.md for some hints as to how to verify this.

If, once you've RFTMed, you're 100% certain that it's this plugin then I'll need to see a pipeline that demonstrates the issue.

**Comment by tomlankhorst** [comment]
Thank for your reply! Closing for now.
