### ISSUE TITLE
Add docker cloud with https and basic auth.

### ISSUE THREAD

**Issue by mesudip** [jenkinsci/docker-plugin#801]
I am able to access docker endpoint with curl
```
curl https://user:password@docker.example.com/info # info endpoint
```
but the docker cloud supports only `unix` or `tcp` scheme. how do i add this as a docker cloud?

**Comment by ntwrkguru** [comment]
You would use the` tcp` option there and the full `https://docker.example.com` in the "Docker Hostname or IP address" field.
