### ISSUE TITLE
All nodes of label ‘second-docker-agent’ are offline

### ISSUE THREAD

**Issue by amirdamirov** [jenkinsci/docker-plugin#806]
If you are sure that this plugin is the source of your troubles then please report:
 - [ 1.1.9 ] docker-plugin version you use
 - [ Jenkins ver. 2.204.2 ] jenkins version you use
 - [ 19.03.6 ] docker engine version you use
 - [details of the docker container(s) involved and details of how the docker-plugin is connecting to them
    Connect method.   >> attach docker container

I have problem with my jenkins when i try use docker-agent. 
When i run build with label docker-agent it stuck with this log >> All nodes of label ‘second-docker-agent’ are offline

I can pull images, run container via remote api docker from jenkins. But when i run build jenkins see agent as offline. 
Is there any recomendation how to fix it ?

**Comment by amirdamirov** [comment]
I recreated the docker-host from Jenkins configuration and i worked.

**Comment by rakaupuv** [comment]
@amirdamirov , can you please elaborate on the solution that worked for you ? 
I'm having the exact same problem or atleast symptoms seems to be the same.  I've a VM defined as a docker cloud and I've agent templates defined with different label for docker images. The job always get hung on the same log message while there are other images running fine on the same host/VM. It some how seems to have problem with just this label

**Comment by pjdarton** [comment]
FYI the "all nodes with label ... offline" typically means that there's a problem with the docker-template being used for second-docker-agent and/or there's a problem with the image being used by that docker-template - quite often it's a mismatch between the two, e.g. one is expecting to use a user "jenkins" whereas the other uses "root".

If the docker-plugin fails to create a docker container from the image (the image specified in the docker template in the Jenkins cloud configuration) then that'll be logged in the Jenkins log (manage jenkins -> system log).
If the container is created OK but it then fails to come online then that'll sometimes appear in that agent's log, and if you're getting that far then any problems are usually a mismatch between the docker image's assumptions and what you've put in the docker-template (e.g. the filesystem root) - it's often a good idea to try using the official Jenkins docker images as a starting point and do any modifications step-by-step until you figure out where you broke it.

**Comment by yuchen822** [comment]
The message from our "Common Services" job: "All nodes of label ‘commonservices-jnlp-slave-ubuntu-test’ are offline"
And in a node event page: 

![Image](https://github.com/user-attachments/assets/2762b0d7-acf0-4c66-8a7c-a07f49e01008)
