### ISSUE TITLE
Can't Pull ECR Images

### ISSUE THREAD

**Issue by realsby** [jenkinsci/docker-plugin#809]
When I use my customized Docker Image in ECR (acc_id.dkr.ecr.eu-central-1.amazonaws.com/jenkins_slave:latest) it does not working. 

I installed amazon-ecr-credential-helper into the docker machine and when I call docker pull my self as root user, its working without any extra step with the role that attached to docker machine. 

But when I check logs it says in jenkins master

com.github.dockerjava.api.exception.InternalServerErrorException: {"message":"Get https://acc_id.dkr.ecr.eu-central-1.amazonaws.com/v2/jenkins_slave/manifests/latest: no basic auth credentials"}

I am not sure how to configure dockre api end point to use amazon-ecr-credential-helper. Or am I missing a configuration on jenkins master?

**Comment by realsby** [comment]
I believe i found some answers..

Jenkins master use docker daemon api and daemon has no idea about amazon-ecr-credential-helper.

> When pushing and pulling images with Docker, the Docker daemon (dockerd) doesn't have direct access to credentials. Instead, the client (like the Docker CLI docker) is responsible for sending credential information to the daemon whenever it performs image operations. This works well with push and pull operations; the Docker CLI can reliably know which image is being referenced and discover credential information prior to invoking daemon API so it can send it along.

**Comment by pjdarton** [comment]
I think this is a duplicate/symptom of #803
