### ISSUE TITLE
Docker plugin unsets DOCKER_TLS_VERIFY and DOCKER_CERT_PATH environment variables

### ISSUE THREAD

**Issue by luka-j** [jenkinsci/docker-plugin#812]
docker-plugin version: 1.2.0
jenkins version: 2.235.1
docker engine version: 18.09.5

I use this plugin to spin up custom images for Jenkins workers on different machines. Those images already have DOCKER_HOST, DOCKER_TLS_VERIFY and DOCKER_CERT_PATH environment variables set. However, when I inspect process running the build (shell or Gradle script) by `cat /proc/{pid}/environ`, they are missing. When I check the "Expose DOCKER_HOST" option in settings for this plugin, I can see the DOCKER_HOST is now visible to the process, but not the other two variables, so I suspect this plugin unsets them as well. This is definitely not the behaviour I'd expect.

**Comment by pjdarton** [comment]
The docker plugin doesn't unset env vars.

However, If you're connecting via SSH then your agents get the environment that sshd gives them, which can be this cut down version.
IME when one uses SSH, it's entirely possible for sshd to run using a minimalist environment and thus not get any env vars you've tried to set up - they'll all be set inside the container but not exposed by sshd.
