### ISSUE TITLE
update the registry login to use --password-stdin to avoid security warning

### ISSUE THREAD

**Issue by moshavnik** [jenkinsci/docker-plugin#824]
docker-plugin version: 1.2.1
jenkins version you use: 2.263.2
docker engine version you use: 20.10.2
details of the docker container(s) involved and details of how the docker-plugin is connecting to them: irrelevant, this has nothing to do with the containers....
stack trace / logs / any technical details that could help diagnose this issue: the following message appears...
--------------------------------
WARNING! Using --password via the CLI is insecure. Use --password-stdin
WARNING! Your password will be stored unencrypted in <the tmp folder of the job>
Configure a credential helper to remove this warning. See https://docs.docker.com/engine/reference/commandline/login/#credentials-store
--------------------------------

my request, to make it as simple as possible, is for you to update the cli you are using to make sure the credentials being used the proper way, in order to avoid this warning message.

**Comment by pjdarton** [comment]
This plugin doesn't use the docker cli.
My guess is that you're talking about the [docker pipeline plugin](https://github.com/jenkinsci/docker-workflow-plugin) - I think that _does_ use the docker command-line.

For more info, read the [README file](https://github.com/jenkinsci/docker-plugin/blob/master/README.md) for this plugin, especially the section starting "Note: There is more than one docker plugin for Jenkins."

**Comment by moshavnik** [comment]
correct.
I moved the issue to the correct plugin.
