### ISSUE TITLE
"Commit on successful build" actually works as the job's completion no matter success or failure

### ISSUE THREAD

**Issue by larrycai** [jenkinsci/docker-plugin#84]
If "Commit on successful build" is enabled and "Clean local images" are disabled, no matter the job successful or not. The image will be saved with "<job name>:#$BUILD_NUMBER"

- docker plugin version 0.7
- jenkins (LTS) 1.565.1
- docker : 1.1.2 (boot2docker)

**Comment by KostyaSha** [comment]
commit/tag/push will be resolved as part of separate issue. Trying to clean up/classify issues, so closing.
