### ISSUE TITLE
default docker image tag in job is not known to docker daemon ("#$BUILD_NUMBER")

### ISSUE THREAD

**Issue by larrycai** [jenkinsci/docker-plugin#85]
when the docker image is saved after job's completion, the tag name default is "#$BUILD_NUMBER" 

This looks not follow the docker image naming rules (`docker-demo` is my job name)

    docker@boot2docker:~$ docker rmi -f docker-demo:#2
    Error response from daemon: No such image: docker-demo:latest
    2014/08/20 10:33:36 Error: failed to remove one or more images

I have to delete with image id

Will be nice to change to like "B$BUILD_NUMBER", then it is `docker-demo:b2` 

- docker plugin version 0.7
- jenkins (LTS) 1.565.1
- docker : 1.1.2 (boot2docker)

**Comment by KostyaSha** [comment]
try #210 i temporary fixed tags until better implementation.
