### ISSUE TITLE
Configuration option to use the same build container throughout the whole build

### ISSUE THREAD

**Issue by pwurbs** [jenkinsci/docker-plugin#854]
### Feature Request

Any node reference to a Docker agent label in a stage leads to the creation of a new build container. It could be useful to perform all tasks in a build job over different stages (even in separated node declarations) in the same build container.  This could be made configurable in the Cloud agent configuration. 

See also bug report #853

**Comment by pjdarton** [comment]
If you want to execute multiple pipeline steps in a single node, you need to write your pipeline to do that.
As you've found, this plugin provides single-use agents that do the one thing they're told to do (whether that's to execute a full non-pipeline job, or execute part of a pipeline job) and then exit, and that's what it's intended to do. If you want more control than that, use the docker-workflow plugin.
