### ISSUE TITLE
resolve build variables in mount template

### ISSUE THREAD

**Issue by joel-schaal** [jenkinsci/docker-plugin#868]
### Feature Request

It would be fantastic if we could define a DockerTemplateBase with something like:
```type=volume,source=${workspace},target=/home/workspace```

so that we can easily share a persistent workspace across multiple executions of an agent. 

I guess this must be done in `DockerTemplateBase.parseMountsString(String mnt, List<Mount> mountListResult)`. 
I'd be glad to provide a PR, but I'm not sure how to give access to a "resolver" (that would translate variable names to their actual value) in there. 

Maybe there are other ways to achieve this ? I don't want to overload my pipelines with docker args to specify the mount point each time, but so far this is the only fallback I have found.

**Comment by pjdarton** [comment]
There's no linkage between a build and the cloud provisioning context aside from the build labels.
If you've got a dozen builds all asking for a executor with label "foo" then all that demand for executors will look alike as far as the cloud provisioning code is concerned - the docker-plugin (or any other cloud plugin) doesn't get told which build is going where (at least, not until the build starts to run on the container, which happens long after the container is created and initialised and hence can't be known before the container is created).
i.e. your "fantastic" request is, unfortunately, purely in the realms of fantasy - you can't get to "there" from "here".

You can _either_ have a label (or combination of labels) for each kind of execution environment you need (and a docker template to match), _or_ you need to use pipelines to control the execution environment (at which point your builds have full control over the container configuration).

In your particular case, it sounds like you want to make each build run share an underlying folder on the docker host; if you want to do that (and I wouldn't really recommend it), you could always specify a workspace folder in the job configuration so they all use the same folder and can therefore all use the same mountpoint.
... but you'll need to ensure that you don't get more than one build running simultaneously in the same folder - Jenkins will think that folders on different agents are different folders - it won't know about the mountpoint and hence it won't know that your environment can't handle more than one build at a time.
If you want workspaces that persist between build runs, you probably don't want your builds to run within docker containers - the whole point of docker containers is that they're disposable and nothing from one run affects the next. You may be better off having a Linux VM set up as a Jenkins remote agent with a number of executors configured (and then, as Jenkins will know it's on one filesystem, it'll make sure no builds tread on each others toes "for free").
