### ISSUE TITLE
"Add a new template to all docker clouds" is in job configuration

### ISSUE THREAD

**Issue by larrycai** [jenkinsci/docker-plugin#87]
"Add a new template to all docker clouds" section is in system configuration to update the docker globally, this is correct.

While it appears in "Build step" in Job configuration as well.

I guess it shall be removed.

- docker plugin version 0.7
- jenkins (LTS) 1.565.1
- docker : 1.1.2 (boot2docker)

**Comment by KostyaSha** [comment]
Please try #210 and reopen if issue still exists.
