### ISSUE TITLE
docker is failed to stop & rm container that was already stopped and exit with error

### ISSUE THREAD

**Issue by dsaydon90** [jenkinsci/docker-plugin#871]
When I'm using the `inside` method to run my unit test inside my docker and when the test is failed the container will be exit with error and will be removed, but the docker plugin will try to stop & rm container which is not exist any more.

![image](https://user-images.githubusercontent.com/22152786/147243836-a6bce2d2-faa4-4f62-b046-eb4d6ca89625.png)

### Reproduction steps

 docker.image(img_name).inside(-u root:root --entrypoint=){
  sh "exit 1"
}

### Results

Expected result:

The docker stop and rm should exit with 0 by checking if container exist, if yes kill it, if not skip

Actual result:

docker stop and rm exit with exit error 1

**Comment by pjdarton** [comment]
Wrong plugin.

_This_ docker plugin doesn't use the native docker command line client.
If this plugin stops a container, it uses the docker-java library.

You're using a different plugin; most likely the docker pipeline/workflow plugin as that does use the docker command line.
