### ISSUE TITLE
The second job doesn't work with same configuration ,error "All nodes of label ‘docker-slave’ are offline "

### ISSUE THREAD

**Issue by new-ninja2020** [jenkinsci/docker-plugin#873]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
Docker plugin : 1.2.3
Docker host : 20.10.10
Docker API : 1.41.1
Connection: attach docker container
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Hi , i am using docker as node in jenkins , first i configured the host with tls mode in jenkins the connection test is good ,
after i added docker agent template with attach docker container connection mode 

### Reproduction steps

when i was trying to start the job for the first is working fine , but when i am  trying  to run it another time i get this message ```All nodes of label ‘docker-slave’ are offline```  and no container is  started in  the docker host (slave), i can reproduce this behavior by restarting Jenkins instance .

### Expected Results

Slave created and the job run !

### Actual Results

``` 
All nodes of label ‘docker-slave’ are offline
```
Logs:
```
Asked to provision 1 agent(s) for: docker-slave
Jan 07, 2022 4:48:01 PM FINE com.nirima.jenkins.plugins.docker.DockerCloud provision
Not provisioning additional agents for docker-slave; we have 1 executors being started already
Jan 07, 2022 4:48:01 PM FINEST io.jenkins.docker.FastNodeProvisionerStrategy
Available executors=0, connecting=0, planned=0
Jan 07, 2022 4:48:01 PM FINE io.jenkins.docker.FastNodeProvisionerStrategy
Available capacity=0, currentDemand=1
Jan 07, 2022 4:48:01 PM FINE com.nirima.jenkins.plugins.docker.DockerCloud provision
```

**Comment by pjdarton** [comment]
Looks like your docker-daemon is locking up.

I'd suggest that you specify timeouts (in the Advanced... section) so that the docker plugin can detect that; it won't help fix the docker daemon, but you'll get more informative logging.

If you can provide a full repro-case (how the cloud is configured, how the template is configured etc) then feel free to re-open.
