### ISSUE TITLE
Switching method of connection from SSH to JNLP and users

### ISSUE THREAD

**Issue by kubinski** [jenkinsci/docker-plugin#877]
### Describe your use-case which is not covered by existing documentation.

I recently switched our docker cloud connection method from SSH to JNLP due to the ipv6 bug (839?) that caused many of our connections to fail.  I have got JNLP working in our containers just fine, however the one problem I am having which doesn't seem to be very well documented (or at least understood on my part) is how the users work.
With connection method SSH I assume since we had a user specified (username/password) that the Jenkins job would SSH as that user into the container and then run the whole job as that user.
Since switching to JNLP every job seems to run as root.  Either directly or via sudo.  I have tried setting all the different user options in the plugin but I am still getting the same result.  How do I ensure that my jobs still run as the jenkins user we used to specify in SSH?

**Comment by pjdarton** [comment]
With SSH, the docker plugin asks the docker daemon to run a docker container and doesn't give it any specific commands to run, so it is the container's responsibility to run sshd ... and then Jenkins logs into SSH using the credentials it was told to use which, if sshd is configured normally, results in processes running within the container as the user that were given to sshd by Jenkins.

With JNLP, the docker plugin tells the docker daemon a specific command to run within the container (see "EntryPoint Arguments" for details), telling it the exact command ... and can also specify which user the command should be run as (see the "User" field just above that).
So, with JNLP, it's effectively doing "docker run --user=... <entrypoint arguments>". If you want the JNLP process (and hence the build processes) to run as user "foo" then you need to put that into the docker template's "User" field (within the "Connect with JNLP" section").
