### ISSUE TITLE
multi-platform builds

### ISSUE THREAD

**Issue by GyrosGeier** [jenkinsci/docker-plugin#879]
### What feature do you want to see added?

My Jenkins server has access to a swarm with amd64 and ppc64le processors, and emulation for arm64.

I would like to have a convenient way to build a multi-arch image, perhaps similar to the `--platform` [parameter](https://docs.docker.com/engine/reference/commandline/buildx_build/#platform) in the BuildX extension: accepting multiple values, building multiple platform dependent images on appropriate hosts, and then merging the resulting images using a manifest.

**Comment by pjdarton** [comment]
This plugin is intended to be a Jenkins cloud plugin which uses existing docker-images and a docker daemon to provide Jenkins agents made from docker containers; that's it's primary purpose; it's not intended to be a "everything about docker, on Jenkins" plugin.
This plugin was never intended to be a buildx plugin - if you want that, you want a different plugin.

You might be able to achieve this kind of effect using a multi-configuration build, running multiple image builds in parallel on different environments, using the "build image" step that this plugin requires.
Or just a single build that ran each in sequence.
...but only if the version of the docker-java library provided by the docker-api-plugin gives this plugin access to the API(s) required to chose a particular architecture; I've no idea if it does that, and I'm fairly sure that this plugin doesn't let you chose architecture.

My guess is that you're probably better off having a build run on a Jenkins agent that's got the build tooling you require and issue the command-line commands that do the build that you want.
This plugin could be used to spin up a docker container from which those commands could be run ... but you'd need to set up your own docker image that included the tooling you wanted.
