### ISSUE TITLE
Regression: privilege flag not honoured in v0.7, ok in 0.6.2

### ISSUE THREAD

**Issue by wwadge** [jenkinsci/docker-plugin#88]
Verified via docker inspect. Running a container with the privileged flag switched on does not work in 0.7

**Comment by KostyaSha** [comment]
And as usual, please provide steps for reproduce (even if it obvious for you). I will check, but will be glad to see steps from requester.

**Comment by KostyaSha** [comment]
Works on current master (and should be on 0.9.0-rc1).
