### ISSUE TITLE
adding host to docker container (--add-host option)

### ISSUE THREAD

**Issue by farshid616** [jenkinsci/docker-plugin#893]
### Describe your use-case which is not covered by existing documentation.

I want to use **--add-host** option but I can't find it on available documents. 
Also I tried to add my host by **docker command** but I can't find any example to how can I use **docker command** properly without conflicting SSH launcher.

**Comment by pjdarton** [comment]
If you want to use the docker command line then you need a different plugin, e.g. the docker-workflow plugin.

If you want the docker-plugin to support this, and the underlying docker-java library (which is what's used instead of calling a native docker client) supports it, feel free to submit a PR.

**Comment by farshid616** [comment]
No I don't want to use the command line, I'm just trying to find a way ta add a host to my docker agent with this plugin.

**Comment by pjdarton** [comment]
Have you tried the "Extra Hosts" field?
That's described as:

> A list of new line separated hostnames/IP mappings to be added to the container’s /etc/hosts file. Specified in the form "hostname:IP". 

That sounds like it's exactly what you're asking for.
You'll find that setting within the "Container settings..." area of the template.

Hint: When looking for stuff within the Jenkins UI, click on all the "..." buttons to expand everything - lots of not-commonly-used fields get hidden behind "Advanced..." buttons etc.

**Comment by farshid616** [comment]
Yes, that was exactly one I was looking for. I'm wondering why I didn't see that on the configuration page!
By the way thank you for that.
