### ISSUE TITLE
How to use the docker agent template to configure --cpu-count

### ISSUE THREAD

**Issue by ravisalamani** [jenkinsci/docker-plugin#894]
### Jenkins and plugins versions report

Jenkins: 2.303.1
OS: Linux - 4.18.0-348.7.1.el8_5.x86_64
---
docker-commons:1.19
docker-java-api:3.1.5.2
docker-plugin:1.2.6
...

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS: Windows10 Build 21H1
For use with the Windows base container. We must indicate the number of CPUs required; by default, only two CPUs are available.

Docker run -it —cpu-count 58 windows base image command is an example.

Any instructions on how to set it up on a Docker agent template would be quite helpful.

### Reproduction steps

* Complete the required setup for the Docker plugin * 
* Try to set the —cpu-count in the Docker Agent templates.

### Expected Results

Extra commands for starting the container should be added to the docker agent template.
Ex:   --cpu-count 

### Actual Results

No option to set   --cpu-count

**Comment by ravisalamani** [comment]
Thanks @CJCombrink 
Tested the hpi, #895 LGTM

**Comment by ravisalamani** [comment]
@here I'm now utilizing the plugin by downloading the hpi file; do you know when it will be released as part of it?

**Comment by Peter-Darton-i2** [comment]
Once I've got confirmation that everything looks OK from enough people then I'll push out a new release.
You can speed up that process by going to #904 and helping test the latest build.
