### ISSUE TITLE
[1.2.9] Build fails when Dockerfile is located in repo root path

### ISSUE THREAD

**Issue by roelandg** [jenkinsci/docker-plugin#908]
### Jenkins and plugins versions report

Jenkins: 2.362
OS: Linux - 3.10.0-1160.71.1.el7.x86_64
---
ace-editor:1.1
active-directory:2.25.1
ant:475.vf34069fef73c
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-138.v4e7d9a_7b_a_e61
authentication-tokens:1.4
authorize-project:1.4.0
bitbucket:223.vd12f2bca5430
bootstrap4-api:4.6.0-5
bootstrap5-api:5.1.3-7
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-timeout:1.21
build-token-trigger:1.0.0
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.4
cloudbees-disk-usage-simple:170.va_fd5b_4ee6858
cloudbees-folder:6.758.vfd75d09eea_a_1
command-launcher:84.v4a_97f2027398
conditional-buildstep:1.4.2
credentials:1139.veb_9579fca_33b_
credentials-binding:523.vd859a_4b_122e6
dashboard-view:2.447.vda_124dd35f11
disk-usage:0.28
display-url-api:2.3.6
docker-commons:1.19
docker-java-api:3.2.13-37.vf3411c9828b9
docker-plugin:1.2.9
docker-workflow:1.29
durable-task:496.va67c6f9eefa7
echarts-api:5.3.3-1
email-ext:2.91
embeddable-build-status:237.v37e2c03964c9
extended-read-permission:3.2
external-monitor-job:192.ve979ca_8b_3ccd
font-awesome-api:6.1.1-1
git:4.11.4
git-client:3.11.1
git-parameter:0.9.17
git-server:99.va_0826a_b_cdfa_d
github:1.34.5
github-api:1.303-400.v35c2d8258028
github-branch-source:1677.v731f745ea_0cf
global-build-stats:244.v27c8a_2e50a_34
gradle:1.39.4
handlebars:3.0.8
instance-identity:116.vf8f487400980
jackson2-api:2.13.3-285.vc03c0256d517
jakarta-activation-api:2.0.0-3
jakarta-mail-api:2.0.0-6
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-4
javax-mail-api:1.6.2-7
jaxb:2.3.6-1
jdk-tool:55.v1b_32b_6ca_f9ca
jjwt-api:0.11.5-77.v646c772fddb_0
job-dsl:1.81
jobConfigHistory:1163.ve82c7c6e60a_3
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-4
jsch:0.1.55.2
junit:1119.1121.vc43d0fc45561
ldap:2.11
lockable-resources:2.16
mailer:438.v02c7f0a_12fa_4
mapdb-api:1.0.9-28.vf251ce40855d
matrix-auth:3.1.5
matrix-project:785.v06b_7f47b_c631
maven-plugin:3.19
mercurial:2.16.2
metrics:4.2.10-389.v93143621b_050
mina-sshd-api-common:2.8.0-36.v8e25ce90d4b_1
mina-sshd-api-core:2.8.0-36.v8e25ce90d4b_1
momentjs:1.1.1
okhttp-api:4.9.3-108.v0feda04578cf
pam-auth:1.8
parameterized-trigger:2.45
pipeline-build-step:2.18
pipeline-github-lib:38.v445716ea_edda_
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-groovy-lib:612.v84da_9c54906d
pipeline-input-step:449.v77f0e8b_845c4
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2114.v2654ca_721309
pipeline-model-definition:2.2114.v2654ca_721309
pipeline-model-extensions:2.2114.v2654ca_721309
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2114.v2654ca_721309
pipeline-stage-view:2.24
plain-credentials:139.ved2b_9cf7587b
plugin-util-api:2.17.0
popper-api:1.16.1-3
popper2-api:2.11.5-2
prometheus:2.0.11
publish-over:0.22
publish-over-ssh:1.24
resource-disposer:0.19
role-strategy:552.v14cb_85499b_89
run-condition:1.5
scm-api:620.v0a_5b_1f8054c0
script-security:1175.v4b_d517d6db_f0
simple-theme-plugin:103.va_161d09c38c7
snakeyaml-api:1.30.2-76.vc104f7ce9870
ssh:2.6.1
ssh-agent:295.v9ca_a_1c7cc3a_a_
ssh-credentials:295.vced876c18eb_4
ssh-slaves:1.834.v622da_57f702c
sshd:3.249.v2dc2ea_416e33
structs:324.va_f5d6774f3a_d
subversion:2.16.0
timestamper:1.18
token-macro:308.v4f2b_ed62b_b_16
trilead-api:1.67.vc3938a_35172f
uno-choice:2.6.3
variant:59.vf075fe829ccb
windows-slaves:1.8.1
workflow-aggregator:590.v6a_d052e5a_a_b_5
workflow-api:1188.v0016b_4f29881
workflow-basic-steps:986.v6b_9c830a_6b_37
workflow-cps:2759.v87459c4eea_ca_
workflow-durable-task-step:1199.v02b_9244f8064
workflow-job:1232.v5a_4c994312f1
workflow-multibranch:716.vc692a_e52371b_
workflow-scm-step:400.v6b_89a_1317c9a_
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:838.va_3a_087b_4055b
ws-cleanup:0.42

### What Operating System are you using (both controller, and any agents involved in the problem)?

Centos (EL7)

### Reproduction steps

1. Create Freestyle project
2. Select Source Code Management: GIT
3. Add Repo URL
4. Add build step: "Build / Publish Docker Image"
5. Leave "Directory for Dockerfile" empty, as the Dockerfile is located in the root of the repo. Using "." or "./" doesn't make a difference)
6. Choose the correct cloud. For us this is pointing to a docker cloud with Docker Host URI "unix:///var/run/docker.sock"
7. Save the configuration
8. Build the configuration

### Expected Results

An image that was build

### Actual Results

Docker Build: building image at path /var/lib/jenkins/workspace/<jenkins project name>
ERROR: Build step failed with exception
java.util.NoSuchElementException
       at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
       at java.base/java.util.ArrayDeque.remove(ArrayDeque.java:524)
       at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:267)
       at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:132)
       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:748)
       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:740)
       at io.netty.channel.AbstractChannelHandlerContext.access$2200(AbstractChannelHandlerContext.java:59)
       at io.netty.channel.AbstractChannelHandlerContext$Tasks$4.run(AbstractChannelHandlerContext.java:1142)
       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
       at java.base/java.lang.Thread.run(Thread.java:829) 

### Anything else?

- A configuration with the Dockerfile in the root of the repository has always worked for us
- Moving the dockerfile to a subdirectory, and use this subdirectory in step 5 I described, results in a correct build
- Reverting to docker-plugin 1.2.6 and  docker-java-api 3.1.5.2 solves the issue, however we would like to use the new BuildArgument feature of 1.2.9.

Last but not least; My gut feeling tells me that the new BuildArgument feature has todo with breaking the build command where an empty Dockerfile path is passed

**Comment by liu490663834** [comment]
i had a same problem,do you resolved it?

**Comment by roelandg** [comment]
No, we rolled back the upgrade to 1.2.6.

**Comment by liu490663834** [comment]
thank you,it worked.

**Comment by zeddD1abl0** [comment]
In version 1.2.10, if you leave the field empty, it will work with a Dockerfile in the root. I currently have this setup and it appears to be totally functional.

**Comment by pjdarton** [comment]
The error stacktrace here doesn't seem to mention the docker-plugin directly, but it does mention the netty transport layer (a lot), suggesting that the cause of the issue may actually be buried within netty.
...but there's just been a new [release](https://github.com/jenkinsci/docker-plugin/releases/tag/docker-plugin-1.3.0) of the docker-plugin that [replaces the netty transport layer](https://github.com/jenkinsci/docker-plugin/pull/934) so I'd strongly suggest you try that new version - it'll either work now (if so, please close this issue) or fail with a different (hopefully more informative!) message (if so, please describe it here).

**Comment by roelandg** [comment]
Yes, updating docker-plugin to newest version, solved the issue thanks
