### ISSUE TITLE
Commit / push if failure

### ISSUE THREAD

**Issue by hcguersoy** [jenkinsci/docker-plugin#91]
In addition to the 'commit / push on succes' it would be nice to have a functionality to commit and / or push a image of a failed build to inspect it.

In my case, the successful build images are not very interesting but it would be nice to have the possibility to inspect why a build fails.

**Comment by hcguersoy** [comment]
IMO it would be sufficient to commit / tag and optionally push.
Pushing large amounts of build containers into a private docker registry brings the problem of house keeping (in docker registry it's still not supported to delete images) so this should be optional.

**Comment by rskang** [comment]
@hcguersoy Yes we just commit / tag on failure, no pushing. For the exact reasons you mention.
Will hopefully get some time to rebase our code onto upstream and get it up here later this week.

**Comment by rskang** [comment]
Pull request here: https://github.com/jenkinsci/docker-plugin/pull/132 (only does tag / commit, no pushing related code at all)

**Comment by pjdarton** [comment]
Closing due to lack of response on PR
