### ISSUE TITLE
Failed to capture container inspection data

### ISSUE THREAD

**Issue by jshbrntt** [jenkinsci/docker-plugin#939]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Jenkins: 2.375.2
  OS: Windows Server 2016 - 10.0
  ---
  <snip>
  docker-commons:1.21
  docker-java-api:3.2.13-37.vf3411c9828b9
  docker-plugin:1.3.0
  docker-workflow:563.vd5d2e5c4007f
  <snip>
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Controller: Windows Server 2016 - 10.0
Agent: Debian 11.5, Docker Engine 20.10.21

### Reproduction steps

1. Create an agent Docker image using the following `Dockerfile`.

    ```dockerfile
    ARG DOCKER_VERSION=20.10.21

    FROM docker:${DOCKER_VERSION}-dind AS base

    ARG MAKE_VERSION=4.3
    ARG JAVA_VERSION=11.0.18

    RUN apk update && apk add --no-cache \
    make=~${MAKE_VERSION} \
    openjdk${JAVA_VERSION%%.*}-jre-headless=~${JAVA_VERSION}

    ENTRYPOINT dockerd & sh
    ```

2. Start a freestyle job using the agent configured with the above Docker image.

3. In the Jenkins web interface select the job and the `Built on Docker` section on the left hand side.

### Expected Results

It should show a JSON object from the output of `docker inspect`.

### Actual Results

It fails with the following error.

```
Failed to capture container inspection data: No serializer found for class java.lang.Object and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: com.github.dockerjava.api.command.InspectContainerResponse["Config"]->com.github.dockerjava.api.model.ContainerConfig["ExposedPorts"]->java.util.HashMap["2376/tcp"])
```

### Anything else?

It appears this issue does not happen when using the [`jenkins/agent` Docker image](https://hub.docker.com/r/jenkins/agent).

However, this image possesses all the requirements outlined in the **Connect method** section of **Configure Clouds**.

If you select the **Attach Docker Container** option, it outlines the following prerequisties.

>**Prerequisites:**
>- Docker image must have [Java](https://go.java/) installed.
>- Docker image CMD must either be empty or simply sit and wait forever, e.g. /bin/bash.
>The Jenkins remote agent code will be copied into the container and then run using the Java that's installed in the container.

**Comment by nilsmahlstaedt** [comment]
Possibly related to docker/cli#2868
They discuss, that Images built with BuildKit have no values in the `containerConfig` section of a `docker image inspect` response. 
When you test this, most (all?) values are present in the `config`section.
