### ISSUE TITLE
Prevent annoying message from being logged every 5 minutes

### ISSUE THREAD

**Issue by Pexers** [jenkinsci/docker-plugin#996]
### What feature do you want to see added?

Have the option to disable the below message from being logged every 5 minutes:
`Will not cleanup superfluous containers on DockerCloud [name=docker, dockerURI=unix:///var/run/docker.sock], as it is disabled`

Example:
```sh
Jul 30, 2023 12:48:31 PM INFO com.nirima.jenkins.plugins.docker.DockerContainerWatchdog processCloud
Will not cleanup superfluous containers on DockerCloud [name=docker, dockerURI=unix:///var/run/docker.sock], as it is disabled
Jul 30, 2023 12:53:31 PM INFO com.nirima.jenkins.plugins.docker.DockerContainerWatchdog processCloud
Will not cleanup superfluous containers on DockerCloud [name=docker, dockerURI=unix:///var/run/docker.sock], as it is disabled
Jul 30, 2023 12:58:31 PM INFO com.nirima.jenkins.plugins.docker.DockerContainerWatchdog processCloud
Will not cleanup superfluous containers on DockerCloud [name=docker, dockerURI=unix:///var/run/docker.sock], as it is disabled
Jul 30, 2023 1:03:31 PM INFO com.nirima.jenkins.plugins.docker.DockerContainerWatchdog processCloud
Will not cleanup superfluous containers on DockerCloud [name=docker, dockerURI=unix:///var/run/docker.sock], as it is disabled
```

**Comment by Peter-Darton-i2** [comment]
IMO you're right, it's just noise.
I don't think it needs to be made configurable; if someone really wants to see that message then they can add a logger specific to that class to say "I want debug messages from that class".

Best thing to do would be to submit a PR that downgrades that log message from INFO to DEBUG.
i.e. change `LOGGER.info` to `LOGGER.debug` on [that line](https://github.com/jenkinsci/docker-plugin/blob/docker-plugin-1.4/src/main/java/com/nirima/jenkins/plugins/docker/DockerContainerWatchdog.java#L223)

**Comment by Pexers** [comment]
Good suggestion @Peter-Darton-i2, will do that, thanks!
